//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-14 10:19:40
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Msg
{
    ///<summary>
    ///Msg_Message:站内信
    ///</summary>
    public class Msg_Message : BaseMsg
    {
        ///<summary>
        ///站内消息所用模板
        ///</summary>
        public long TemplateId { get; set; }

        ///<summary>
        ///消息所属环节
        ///</summary>
        public string Step { get; set; }

        ///<summary>
        ///站内消息标题
        ///</summary>
        public string Title { get; set; }

        ///<summary>
        ///内容
        ///</summary>
        public string Contents { get; set; }

        ///<summary>
        ///站内消息发送者
        ///</summary>
        public long SenderId { get; set; }

        ///<summary>
        ///站内消息接收者
        ///</summary>
        public long ReceiveId { get; set; }
        ///<summary>
        ///站内消息发送者公司
        ///</summary>
        public long SendeCompanyId { get; set; }
        ///<summary>
		///站内消息接收者公司
		///</summary>
		public long ReceiveCompanyId { get; set; }

        ///<summary>
        ///站内消息发送时间
        ///</summary>
        public DateTime SendTime { get; set; }

        ///<summary>
        ///站内消息已读时间，可为空
        ///</summary>
        public DateTime? ReadTime { get; set; }

        ///<summary>
        ///附加url链接
        ///</summary>
        public string LinkURL { get; set; }

        ///<summary>
        ///站内消息已读状态 0为未读，1为已读
        ///</summary>
        public bool State { get; set; }

        ///<summary>
        ///业务地址
        ///</summary>
        public string BusinessUrl { get; set; }

    }
}

