//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-14 10:19:41
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Msg
{
    ///<summary>
    ///Msg_MessageStrategy:消息发送策略
    ///</summary>
    public class Msg_MessageStrategy : BaseMsg
    {
        ///<summary>
        ///适用消息类型
        ///</summary>
        public string Type { get; set; }

        ///<summary>
        ///扫描时间，秒
        ///</summary>
        public int ScanTime { get; set; }

        ///<summary>
        ///重发次数
        ///</summary>
        public int ResendStra { get; set; }

        ///<summary>
        ///适用时间区间
        ///</summary>
        public string TimeSection { get; set; }

        ///<summary>
        ///发送策略是否启用，默认为0，启用
        ///</summary>
        public bool IsEnable { get; set; }

        ///<summary>
        ///发送策略是否确认，默认为1，未确认
        ///</summary>
        public bool IsConfirm { get; set; }

    }
}

