//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-07-28 13:45:43
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Msg
{ 
	///<summary>
	///Msg_MessageLog:发送日志
	///</summary>
	 public  class  Msg_MessageLog: BaseMsg
    { 
		///<summary>
		///消息发送者
		///</summary>
		public long Sender { get; set; }

		///<summary>
		///消息接收者
		///</summary>
		public long Recipient { get; set; }

		///<summary>
		///消息发送时间
		///</summary>
		public DateTime Time { get; set; }

		///<summary>
		///消息发送类型
		///</summary>
		public string Type { get; set; }

	}
}

