//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-14 10:19:42
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Msg
{ 
	///<summary>
	///Msg_MessageTemplete:站内信模板
	///</summary>
	 public  class  Msg_MessageTemplete: BaseMsg
    { 
		///<summary>
		///站内消息模板编号
		///</summary>
		public string No { get; set; }

		///<summary>
		///模板名称
		///</summary>
		public string Name { get; set; }

		///<summary>
		///站内消息适用环节
		///</summary>
		public string Step { get; set; }

		///<summary>
		///站内消息模板内容
		///</summary>
		public string TemplateCon { get; set; }

        ///<summary>
        ///站内消息标题内容
        ///</summary>
        public string TitleCon { get; set; }

        ///<summary>
        ///站内消息参数说明
        ///</summary>
        public string ParameterDes { get; set; }

		///<summary>
		///站内消息模板启用状态
		///</summary>
		public bool IsEnable { get; set; }

		///<summary>
		///站内消息确认状态
		///</summary>
		public bool IsConfirm { get; set; }

        ///<summary>
        ///附加url链接
        ///</summary>
        public string LinkURL { get; set; }

    }
}

