//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-14 10:19:42
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Msg
{
    ///<summary>
    ///Msg_SMS:
    ///</summary>
    public class Msg_SMS : BaseMsg
    {
        ///<summary>
        ///短信所用模板
        ///</summary>
        public long TemplateId { get; set; }

        ///<summary>
        ///短信服务商模板编号
        ///</summary>
        public string ServerNo { get; set; }

        ///<summary>
        ///消息所属环节
        ///</summary>
        public string Step { get; set; }

        ///<summary>
        ///短信发送者
        ///</summary>
        public long SenderId { get; set; }

        ///<summary>
        ///发送者号码
        ///</summary>
        public string SenderPhone { get; set; }

        ///<summary>
        ///短信接收者
        ///</summary>
        public long ReceiveId { get; set; }

        ///<summary>
        ///接收人电话
        ///</summary>
        public string ReceivePhone { get; set; }

        ///<summary>
        ///短信内容
        ///</summary>
        public string SmsCon { get; set; }
        /// <summary>
        /// 签名
        /// </summary>
        public string SignName { get; set; }

        /// <summary>
        /// 序列化后的参数
        /// </summary>
        public string Params { get; set; }

        ///<summary>
        ///短信发送时间
        ///</summary>
        public DateTime? SenderTime { get; set; }

        ///<summary>
        ///短信提交时间
        ///</summary>
        public DateTime SubmissionTime { get; set; }

        ///<summary>
        ///短信发送状态  0为发送失败，1为发送成功
        ///</summary>
        public bool State { get; set; }

        ///<summary>
        ///发送次数
        ///</summary>
        public int SendCount { get; set; }

        ///<summary>
        ///站内消息发送者公司
        ///</summary>
        public long SendeCompanyId { get; set; }
        ///<summary>
		///站内消息接收者公司
		///</summary>
		public long ReceiveCompanyId { get; set; }

    }
}

