//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-14 10:19:43
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Msg
{
    ///<summary>
    ///Msg_SMSSetting:短信接口设置
    ///</summary>
    public class Msg_SMSSetting : BaseMsg
    {
        ///<summary>
        ///短信接口编号
        ///</summary>
        public string No { get; set; }

        ///<summary>
        ///短信接口名称
        ///</summary>
        public string Name { get; set; }

        ///<summary>
        ///短信接口URL
        ///</summary>
        public string URL { get; set; }

        ///<summary>
        ///短信接口AppId
        ///</summary>
        public string AppId { get; set; }

        ///<summary>
        ///短信接口Key
        ///</summary>
        public string AppKey { get; set; }
        ///<summary>
        ///短信接口Secret
        ///</summary>
        public string AppSecret { get; set; }
        ///<summary>
        ///短信接口费用
        ///</summary>
        public decimal Cost { get; set; }

        ///<summary>
        ///字数限制
        ///</summary>
        public int CharacterLimit { get; set; }

        ///<summary>
        ///短信接口返回值说明
        ///</summary>
        public string ReturnValDes { get; set; }

      

        ///<summary>
        ///短信接口启用状态，默认0，启用
        ///</summary>
        public bool IsEnable { get; set; }

        ///<summary>
        ///短信接口确认状态，默认1，未确认
        ///</summary>
        public bool IsConfirm { get; set; }

    }
}

