//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-14 10:19:41
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Msg
{ 
	///<summary>
	///Msg_MsgLog:发送日志
	///</summary>
	 public  class  Msg_MsgLog: BaseMsg
    { 
		///<summary>
		///消息发送者
		///</summary>
		public long SenderId { get; set; }

		///<summary>
		///消息接收者
		///</summary>
		public long ReceiveId { get; set; }

		///<summary>
		///消息发送时间
		///</summary>
		public DateTime Time { get; set; }

		///<summary>
		///消息Id
		///</summary>
		public long TableId { get; set; }

		///<summary>
		///消息类型
		///</summary>
		public string TableName { get; set; }

		///<summary>
		///状态
		///</summary>
		public string State { get; set; }

		///<summary>
		///说明
		///</summary>
		public string Contents { get; set; }

	}
}

