//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-14 10:19:40
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Msg
{ 
	///<summary>
	///Msg_EmailSetting:邮件接口设置
	///</summary>
	 public  class  Msg_EmailSetting: BaseMsg
    { 
		///<summary>
		///邮件接口编号
		///</summary>
		public string No { get; set; }

		///<summary>
		///邮件接口名称
		///</summary>
		public string Name { get; set; }

		///<summary>
		///邮件接口服务器
		///</summary>
		public string Servers { get; set; }

		///<summary>
		///邮件协议
		///</summary>
		public string MailProtocol { get; set; }

		///<summary>
		///SSL端口号
		///</summary>
		public string SSL { get; set; }

		///<summary>
		///邮件接口用户名
		///</summary>
		public string UserName { get; set; }

		///<summary>
		///邮件接口密码
		///</summary>
		public string PassWord { get; set; }

		///<summary>
		///返回值状态码说明
		///</summary>
		public string ReturnValDes { get; set; }

		///<summary>
		///是否启用，默认为0，启用
		///</summary>
		public bool IsEnable { get; set; }

		///<summary>
		///是否确认，默认为1，未确认
		///</summary>
		public bool IsConfirm { get; set; }

	}
}

