//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hc.Plat.FileServer.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HCPlat_FileServerEntities : DbContext
    {
        public HCPlat_FileServerEntities()
            : base("name=HCPlat_FileServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DownloadLog> DownloadLog { get; set; }
        public virtual DbSet<FileGuid> FileGuid { get; set; }
        public virtual DbSet<StaticResource> StaticResource { get; set; }
        public virtual DbSet<TempFiles> TempFiles { get; set; }
        public virtual DbSet<Files> Files { get; set; }
    }
}
