//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-07-26 16:17:19
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Bp_ProjectNature:
	///</summary>
	 public  class  Bp_ProjectNature: BaseBusiness
    { 
		///<summary>
		///
		///</summary>
		public string NATURE_MC { get; set; }

		///<summary>
		///
		///</summary>
		public string NATURE_BH { get; set; }

		///<summary>
		///
		///</summary>
		public string NATURE_BZ { get; set; }

		///<summary>
		///
		///</summary>
		public string F_SYZT { get; set; }

		///<summary>
		///
		///</summary>
		public string F_CRDATE { get; set; }

		///<summary>
		///
		///</summary>
		public string F_CHDATE { get; set; }

	}
}

