//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-01-17 16:19:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Bp_Supplier:
    ///</summary>
    public class Bp_Supplier : BaseBusiness
    {
        ///<summary>
        ///
        ///</summary>
        public string HB_ID { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Code { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Name { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Address { get; set; }

        ///<summary>
        /// 状态，0:停用;1:使用;	
        ///</summary>
        public string State { get; set; }

    }
}

