//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-01-17 16:19:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Bp_User:
    ///</summary>
    public class Bp_User : BaseBusiness
    {
        ///<summary>
        ///
        ///</summary>
        public string HB_ID { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string UserCode { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string UserName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Sex { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string PassWord { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Phone { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Email { get; set; }

        ///<summary>
        /// 单位ID
        ///</summary>
        public string HB_CompanyID { get; set; }

        ///<summary>
        /// 身份证号
        ///</summary>
        public string IDNumber { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string BirthDate { get; set; }

    }
}

