//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_Contract:合同表
	///</summary>
	 public  class  Epm_Contract:BaseBusiness
	{ 
		///<summary>
		///项目表Id
		///</summary>
		public long? ProjectId { get; set; }

		///<summary>
		///合同编号
		///</summary>
		public string Code { get; set; }

		///<summary>
		///项目名称
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///合同名称
		///</summary>
		public string Name { get; set; }

		///<summary>
		///甲方Id
		///</summary>
		public long? FirstPartyId { get; set; }

		///<summary>
		///甲方Name
		///</summary>
		public string FirstPartyName { get; set; }

		///<summary>
		///乙方Id
		///</summary>
		public long? SecondPartyId { get; set; }

		///<summary>
		///乙方Name
		///</summary>
		public string SecondPartyName { get; set; }

		///<summary>
		///工期，单位天
		///</summary>
		public decimal? BuildDays { get; set; }

		///<summary>
		///生效时间
		///</summary>
		public DateTime? StartTime { get; set; }

		///<summary>
		///截止时间
		///</summary>
		public DateTime? EndTime { get; set; }

		///<summary>
		///合同金额，单位万元
		///</summary>
		public decimal? Amount { get; set; }

		///<summary>
		///签订时间
		///</summary>
		public DateTime? SignTime { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }
        //变更数
        [NotMapped]
        public string ChangeNum { get; set; }
        //签证数
        [NotMapped]
        public string VisaNum { get; set; }

        /// <summary>
        /// 合同类型
        /// </summary>
        public int? ContractType { get; set; }

    }
}

