//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-09-17 10:01:24
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_ConstituteCompany:
	///</summary>
	 public  class  Epm_ConstituteCompany:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string ConstituteKey { get; set; }

		///<summary>
		///
		///</summary>
		public string ConstituteName { get; set; }

		///<summary>
		///
		///</summary>
		public string CompanyNames { get; set; }

		///<summary>
		///
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///
		///</summary>
		public string CrtCompanyName { get; set; }

	}
}

