//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-08-26 11:30:17
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_TzStartsApply: 开工申请
    ///</summary>
    public class Epm_TzStartsApply : BaseBusiness
    {
        public Epm_TzStartsApply()
        {
            TzAttachs = new List<Epm_TzAttachs>();
        }

        ///<summary>
        ///【投资计划】项目ID
        ///</summary>
        public long? DataId { get; set; }

        ///<summary>
        ///标题
        ///</summary>
        public string Title { get; set; }

        ///<summary>
        ///标题id
        ///</summary>
        public long? TitleID { get; set; }

        ///<summary>
        ///申请人
        ///</summary>
        public string Applicant { get; set; }

        ///<summary>
        ///申请人ID
        ///</summary>
        public long? ApplicantID { get; set; }

        ///<summary>
        ///所属单位
        ///</summary>
        public string Unit { get; set; }

        ///<summary>
        ///所属单位ID
        ///</summary>
        public long? UnitID { get; set; }

        ///<summary>
        ///申请日期
        ///</summary>
        public DateTime? ApplyDate { get; set; }

        ///<summary>
        ///所属部门
        ///</summary>
        public string Department { get; set; }

        ///<summary>
        ///所属部门ID
        ///</summary>
        public long? DepartmentID { get; set; }

        ///<summary>
        ///联系电话
        ///</summary>
        public string PhoneNumber { get; set; }

        ///<summary>
        ///报告文号
        ///</summary>
        public string Titanic { get; set; }

        ///<summary>
        ///建设项目名称
        ///</summary>
        public string ProjectName { get; set; }

        ///<summary>
        ///设计规模或能力
        ///</summary>
        public string DesignAbility { get; set; }

        ///<summary>
        ///项目建议书批准文号
        ///</summary>
        public string ApprovalNumber { get; set; }

        ///<summary>
        ///估算投资(万元)
        ///</summary>
        public decimal? BudgetInvestment1 { get; set; }

        ///<summary>
        ///可研报告批准文号  
        ///</summary>
        public string EstimateInvestment { get; set; }

        ///<summary>
        ///估算投资(万元)
        ///</summary>
        public decimal? BudgetInvestment2 { get; set; }

        ///<summary>
        ///立项批复或初步设计批准文号
        ///</summary>
        public string DesignApprovalNumber { get; set; }

        ///<summary>
        ///批复投资或概算投资(万元)
        ///</summary>
        public decimal? ReplyInvestment { get; set; }

        ///<summary>
        ///资金来源编码
        ///</summary>
        public string MoneySourceType { get; set; }

        ///<summary>
        ///资金来源
        ///</summary>
        public string MoneySourceName { get; set; }

        ///<summary>
        ///当年计划投资情况（万元）
        ///</summary>
        public string ThatYearPlanInvestment { get; set; }

        ///<summary>
        ///计划建设开始日期
        ///</summary>
        public DateTime? StartTime { get; set; }

        ///<summary>
        ///计划建设结束日期
        ///</summary>
        public DateTime? EndTime { get; set; }

        ///<summary>
        ///计划建设工期（天）
        ///</summary>
        public int? TimeLimit { get; set; }

        ///<summary>
        ///工程项目概况及主要工程内容和主要工程
        ///</summary>
        public string ProjectOverview { get; set; }

        ///<summary>
        ///项目管理机构及人员到位情况
        ///</summary>
        public string TheStaff { get; set; }

        ///<summary>
        ///工程建设总体部署(或施工组织设计)编制情况
        ///</summary>
        public string PrepareTheSituation { get; set; }

        ///<summary>
        ///设计单位及图纸落实情况(主要设计单位、施工图交付计划情况)
        ///</summary>
        public string CarryOutTheSituation { get; set; }

        ///<summary>
        ///施工单位
        ///</summary>
        public string ConstructionUnit { get; set; }

        ///<summary>
        ///项目经理
        ///</summary>
        public string ProjectManager { get; set; }

        ///<summary>
        ///安全考试成绩（施工）
        ///</summary>
        public string ConstructionGrade { get; set; }

        ///<summary>
        ///施工单位落实及施工队伍、机具进场情况(主要施工单位、合同签订情况)
        ///</summary>
        public string InCase { get; set; }

        ///<summary>
        ///监理单位
        ///</summary>
        public string SupervisionUnit { get; set; }

        ///<summary>
        ///监理工程师
        ///</summary>
        public string SupervisoryEngineer { get; set; }

        ///<summary>
        ///安全考试成绩（监理）
        ///</summary>
        public string EngineerGrade { get; set; }

        ///<summary>
        ///监理单位、质量监督部门落实情况
        ///</summary>
        public string EngineerCarryOutTheSituation { get; set; }

        ///<summary>
        ///施工前期准备情况(包括征地、拆迁、四通一平等)
        ///</summary>
        public string PrepareSituation { get; set; }

        ///<summary>
        ///主要设备、材料订货、到货情况
        ///</summary>
        public string AOGSituation { get; set; }

        ///<summary>
        ///环境影响、劳动安全卫生、消防等审批手续办理情况
        ///</summary>
        public string Procedures { get; set; }

        ///<summary>
        ///工程形象进度计划表附于此页
        ///</summary>
        public string Plan { get; set; }

        ///<summary>
        ///工程建设部门负责人id
        ///</summary>
        public long? HeaderID { get; set; }

        ///<summary>
        ///工程建设部门负责人
        ///</summary>
        public string HeaderName { get; set; }

        ///<summary>
        ///分公司工程建主管领导id
        ///</summary>
        public long? LeaderID { get; set; }

        ///<summary>
        ///分公司工程建主管领导
        ///</summary>
        public string LeaderName { get; set; }

        ///<summary>
        ///签字意见
        ///</summary>
        public string SignIdea { get; set; }

        ///<summary>
        ///当前状态
        ///</summary>
        public string StateType { get; set; }

        ///<summary>
        ///状态编码
        ///</summary>
        public string StateName { get; set; }

        /// <summary>
        /// 当前审批人
        /// </summary>
        public string ApprovalName { get; set; }

        /// <summary>
        /// 当前审批人Id
        /// </summary>
        public long? ApprovalNameId { get; set; }

        /// <summary>
        /// 开工报告审批时间（本次流程全部审批完成时间（年月日），若还未完成审批，不显示）
        /// </summary>
        public DateTime? WorkStartApprovalTime { get; set; }

        /// <summary>
        /// 状态 参考枚举：XtBusinessDataState
        /// </summary>
        public int? State { get; set; }

        /// <summary>
        /// 流程申请 ID
        /// </summary>
        public string WorkFlowId { get; set; }

        [NotMapped]
        public List<Epm_TzAttachs> TzAttachs { get; set; }

        [NotMapped]
        public string SignIdeaHtml { get; set; }

        [NotMapped]
        public string PlanHtml { get; set; }
    }
}

