//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-11-04 18:14:37
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_TzBidResult:招标结果
    ///</summary>
    public class  Epm_TzBidResult:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		//public long ID { get; set; }

		///<summary>
		///所属项目ID
		///</summary>
		public string ProjectId { get; set; }

		///<summary>
		///招标申请ID
		///</summary>
		public long? BidTd { get; set; }

		///<summary>
		///项目名称
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///项目批复号
		///</summary>
		public string ApprovalNo { get; set; }
		///<summary>
		///招标联系人
		///</summary>
		public string UndertakeContacts { get; set; }

		///<summary>
		///招标方式编码
		///</summary>
		public string BidType { get; set; }

		///<summary>
		///招标方式名称
		///</summary>
		public string BidName { get; set; }

		///<summary>
		///联系电话
		///</summary>
		public string UndertakeTel { get; set; }

		///<summary>
		///公示公司一
		///</summary>
		public string BidderOne { get; set; }

		///<summary>
		///公示价格一
		///</summary>
		public string QuotationOne { get; set; }

		///<summary>
		///公示备注一
		///</summary>
		public string RemarkOne { get; set; }

		///<summary>
		///公示公司二
		///</summary>
		public string BidderTwo { get; set; }

		///<summary>
		///公示价格二
		///</summary>
		public string QuotationTwo { get; set; }

		///<summary>
		///公示备注二
		///</summary>
		public string RemarkTwo { get; set; }

		///<summary>
		///公示公司三
		///</summary>
		public string BidderThree { get; set; }

		///<summary>
		///公示价格三
		///</summary>
		public string QuotationThree { get; set; }

		///<summary>
		///公示备注三
		///</summary>
		public string RemarkThree { get; set; }

		///<summary>
		///公示公司四预留
		///</summary>
		public string BidderFour { get; set; }

		///<summary>
		///公示价格四预留
		///</summary>
		public string QuotationFour { get; set; }

		///<summary>
		///公示备注四预留
		///</summary>
		public string RemarkFour { get; set; }

		///<summary>
		///拟推荐单位
		///</summary>
		public string RecommendUnit { get; set; }

		///<summary>
		///推荐理由
		///</summary>
		public string RecommendReason { get; set; }

		///<summary>
		///暂存、待审核、审核通过、审核不通过
		///</summary>
		public int? State { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }

        /// <summary>
        /// 招标名称
        /// </summary>
      
        public string TenderingName { get; set; }
        /// <summary>
        /// 审核流程Id
        /// </summary>

        public string WorkFlowId { get; set; }

        [NotMapped]
        public Epm_TzTenderingApply TzTenderingApply { get; set; }

        ///<summary>
        ///当前状态
        ///</summary>
        public string StateType { get; set; }

        ///<summary>
        ///状态编码
        ///</summary>
        public string StateName { get; set; }

        /// <summary>
        /// 当前审批人
        /// </summary>
        public string ApprovalName { get; set; }

        /// <summary>
        /// 当前审批人Id
        /// </summary>
        public long? ApprovalNameId { get; set; }

        /// <summary>
        /// 开工报告审批时间（本次流程全部审批完成时间（年月日），若还未完成审批，不显示）
        /// </summary>
        public DateTime? WorkStartApprovalTime { get; set; }
    }
}

