//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_OilSales:油品销量表
	///</summary>
	 public  class  Epm_OilSales:BaseBusiness
	{ 
		///<summary>
		///加油站表Id
		///</summary>
		public long? OilStationId { get; set; }

		///<summary>
		///加油站Code
		///</summary>
		public string OilStationCode { get; set; }

		///<summary>
		///加油站Name
		///</summary>
		public string OilStationName { get; set; }

		///<summary>
		///抢号
		///</summary>
		public string RobbingNo { get; set; }

		///<summary>
		///设备编号
		///</summary>
		public string DeviceCode { get; set; }

		///<summary>
		///销售时间
		///</summary>
		public DateTime? SaleTime { get; set; }

		///<summary>
		///油品
		///</summary>
		public string OilCode { get; set; }

		///<summary>
		///型号
		///</summary>
		public string OilModel { get; set; }

		///<summary>
		///单价，单位元
		///</summary>
		public decimal? UnitPrice { get; set; }

		///<summary>
		///升
		///</summary>
		public decimal? Rise { get; set; }

		///<summary>
		///公斤
		///</summary>
		public decimal? Kg { get; set; }

		///<summary>
		///密度
		///</summary>
		public decimal? Density { get; set; }

		///<summary>
		///预留与本省系统对接
		///</summary>
		public string Code1 { get; set; }

		///<summary>
		///预留与本省系统对接
		///</summary>
		public string Code2 { get; set; }

		///<summary>
		///预留与本省系统对接
		///</summary>
		public string Code3 { get; set; }

		///<summary>
		///预留与本省系统对接
		///</summary>
		public string Code4 { get; set; }

		///<summary>
		///预留与本省系统对接
		///</summary>
		public string Code5 { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

	}
}

