//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-08-15 09:04:34
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_ConstituteWorkMainPoints:
    ///</summary>
    public class Epm_ConstituteWorkMainPoints : BaseBusiness
    {
        ///<summary>
        ///项目性质
        ///</summary>
        public string ProjectNatureCode { get; set; }

        ///<summary>
        ///项目性质
        ///</summary>
        public string ProjectNatureName { get; set; }

        ///<summary>
        ///批复构成Id
        ///</summary>
        public long? ConstituteId { get; set; }

        ///<summary>
        ///工程要点Id
        ///</summary>
        public string WorkMainPointsId { get; set; }

    }
}

