//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-10-29 15:11:32
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_TzProjectReveiews:项目评审记录
	///</summary>
	 public  class  Epm_TzProjectReveiews:BaseBusiness
	{ 
		///<summary>
		///所属项目ID
		///</summary>
		public long ProjectId { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? ReveiewDate { get; set; }

		///<summary>
		///主持人
		///</summary>
		public string HostUser { get; set; }

		///<summary>
		///评审地点
		///</summary>
		public string Address { get; set; }

		///<summary>
		///评审结论编码
		///</summary>
		public string ConclusionCode { get; set; }

		///<summary>
		///评审结论名称： 同意、原则同意、不同意
		///</summary>
		public string ConclusionName { get; set; }

		///<summary>
		///其他信息
		///</summary>
		public string OtherInfo { get; set; }

		///<summary>
		///特邀专家
		///</summary>
		public string InvitedExperts { get; set; }

		///<summary>
		///参会人员
		///</summary>
		public string Attendees { get; set; }

		///<summary>
		///完善内容
		///</summary>
		public string PerfectContent { get; set; }

		///<summary>
		///
		///</summary>
		public int? State { get; set; }
        /// <summary>
        /// 相关附件(扩展字段)
        /// </summary>
        [NotMapped]
        public List<Epm_TzAttachs> TzAttachs { get; set; }
        /// <summary>
        /// 流程申请 ID
        /// </summary>
        public string WorkFlowId { get; set; }

        ///<summary>
        ///当前状态
        ///</summary>
        public string StateType { get; set; }

        ///<summary>
        ///状态编码
        ///</summary>
        public string StateName { get; set; }

        /// <summary>
        /// 当前审批人
        /// </summary>
        public string ApprovalName { get; set; }

        /// <summary>
        /// 当前审批人Id
        /// </summary>
        public long? ApprovalNameId { get; set; }

        /// <summary>
        /// 开工报告审批时间（本次流程全部审批完成时间（年月日），若还未完成审批，不显示）
        /// </summary>
        public DateTime? WorkStartApprovalTime { get; set; }
    }
}

