//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-02-14 14:04:36
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_InspectScore:
    ///</summary>
    public class Epm_InspectScore : BaseBusiness
    {
        ///<summary>
        /// 检查单Id
        ///</summary>
        public long? InspectId { get; set; }

        ///<summary>
        /// 检查项表Id
        ///</summary>
        public long? InspectItemId { get; set; }

        ///<summary>
        /// 得失分单位Id
        ///</summary>
        public long? GainLossCompanyId { get; set; }

        ///<summary>
        /// 得失分单位
        ///</summary>
        public string GainLossCompanyName { get; set; }

        ///<summary>
        /// 得失分人员Id
        ///</summary>
        public long? GainLossUserId { get; set; }

        ///<summary>
        /// 得失分人员
        ///</summary>
        public string GainLossUserName { get; set; }
    }
}

