//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:52
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_QuestionTrack:问题回复表
	///</summary>
	 public  class  Epm_QuestionTrack:BaseBusiness
	{ 
		///<summary>
		///问题表Id
		///</summary>
		public long? QuestionId { get; set; }

		///<summary>
		///回复单位Id
		///</summary>
		public long? SubmitCompanyId { get; set; }

		///<summary>
		///回复单位Name
		///</summary>
		public string SubmitCompanyName { get; set; }

		///<summary>
		///回复内容
		///</summary>
		public string Content { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name	
		///</summary>
		public string CrtCompanyName { get; set; }

	}
}

