//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-10-29 15:11:31
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_MeetingFileReport: 上会材料上报
    ///</summary>
    public class  Epm_MeetingFileReport:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public long ProjectId { get; set; }

		///<summary>
		///状态
		///</summary>
		public int State { get; set; }

        /// <summary>
        /// 相关附件(扩展字段)
        /// </summary>
        [NotMapped]
        public List<Epm_TzAttachs> TzAttachs { get; set; }

        ///<summary>
        ///估计气日销量(CNG)/单位：千方
        ///</summary>
        [NotMapped]
        public decimal? CNG { get; set; }

        ///<summary>
        ///估计气日销量(LNG)/单位：千方
        ///</summary>
        [NotMapped]
        public decimal? LNG { get; set; }

        ///<summary>
        ///估计油日销量
        ///</summary>
        [NotMapped]
        public decimal? OilSalesTotal { get; set; }
        /// <summary>
        /// 流程申请 ID
        /// </summary>
        public string WorkFlowId { get; set; }

        ///<summary>
        ///当前状态
        ///</summary>
        public string StateType { get; set; }

        ///<summary>
        ///状态编码
        ///</summary>
        public string StateName { get; set; }

        /// <summary>
        /// 当前审批人
        /// </summary>
        public string ApprovalName { get; set; }

        /// <summary>
        /// 当前审批人Id
        /// </summary>
        public long? ApprovalNameId { get; set; }

        /// <summary>
        /// 开工报告审批时间（本次流程全部审批完成时间（年月日），若还未完成审批，不显示）
        /// </summary>
        public DateTime? WorkStartApprovalTime { get; set; }
    }
}

