//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_NewTarget:新闻分类表
	///</summary>
	 public  class  Epm_NewTarget:BaseBusiness
	{ 
		///<summary>
		///类型编号
		///</summary>
		public string TargetCode { get; set; }

		///<summary>
		///类型名称
		///</summary>
		public string TargetName { get; set; }

		///<summary>
		///描述
		///</summary>
		public string Description { get; set; }

		///<summary>
		///排序
		///</summary>
		public int? Sort { get; set; }

		///<summary>
		///状态 1 启用 0 禁用
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

		///<summary>
		///创建人Id
		///</summary>
		public long? CrateUserId { get; set; }

		///<summary>
		///创建人Name
		///</summary>
		public string CrateUserName { get; set; }

		///<summary>
		///创建时间
		///</summary>
		public DateTime? CrateTime { get; set; }

	}
}

