//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_MilepostData:里程碑关联资料表
	///</summary>
	 public  class  Epm_MilepostData:BaseBusiness
	{ 
		///<summary>
		///里程碑表Id
		///</summary>
		public long? MilepostId { get; set; }

		///<summary>
		///里程碑名称
		///</summary>
		public string MilepostName { get; set; }

		///<summary>
		///项目资料表Id
		///</summary>
		public long? DataConfigId { get; set; }

		///<summary>
		///编码
		///</summary>
		public string DataCode { get; set; }

		///<summary>
		///名称
		///</summary>
		public string DataName { get; set; }

		///<summary>
		///是否必须，1是，0否，枚举
		///</summary>
		public bool? IsRequire { get; set; }

		///<summary>
		///排序
		///</summary>
		public int? Sort { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

	}
}

