//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_PlanComponent:计划关联构件表
	///</summary>
	 public  class  Epm_PlanComponent:BaseBusiness
	{ 
		///<summary>
		///计划表Id
		///</summary>
		public long? PlanId { get; set; }

		///<summary>
		///计划名称
		///</summary>
		public string PlanName { get; set; }

		///<summary>
		///模型Id
		///</summary>
		public long BIMId { get; set; }

		///<summary>
		///模型Naem
		///</summary>
		public string BIMName { get; set; }

		///<summary>
		///构件Id
		///</summary>
		public string ComponentId { get; set; }

		///<summary>
		///构件名称
		///</summary>
		public string ComponentName { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

		///<summary>
		///状态
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

	}
}

