//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-11-04 18:14:38
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_TzSupplyMaterialApply:甲供物资申请单
    ///</summary>
    public class  Epm_TzSupplyMaterialApply:BaseBusiness
	{ 
		///<summary>
		///所属项目ID
		///</summary>
		public long? ProjectId { get; set; }

		///<summary>
		///项目编码（冗余）
		///</summary>
		public string ProjectCode { get; set; }

		///<summary>
		///项目名称（冗余）
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///项目批复后（冗余）
		///</summary>
		public string ApprovalNo { get; set; }

		///<summary>
		///项目性质数据字典编码（冗余）
		///</summary>
		public string Nature { get; set; }

		///<summary>
		///项目性质名称（冗余）
		///</summary>
		public string NatureName { get; set; }

		///<summary>
		///项目提出日期（冗余）
		///</summary>
		public DateTime? ApplyTime { get; set; }

		///<summary>
		///库站ID
		///</summary>
		public long? StationId { get; set; }

		///<summary>
		///库站协同编码（冗余）
		///</summary>
		public string StationCodeXt { get; set; }

		///<summary>
		///库站名称（冗余）
		///</summary>
		public string StationName { get; set; }

		///<summary>
		///地市公司ID（冗余）
		///</summary>
		public long? CompanyId { get; set; }

		///<summary>
		///地市公司协同编码
		///</summary>
		public string CompanyCodeXt { get; set; }

		///<summary>
		///地市公司名称（冗余）
		///</summary>
		public string CompanyName { get; set; }

		///<summary>
		///申请标题
		///</summary>
		public string ApplyTitle { get; set; }

		///<summary>
		///申请人ID
		///</summary>
		public long? ApplyUserId { get; set; }

		///<summary>
		///申请人
		///</summary>
		public string ApplyUserName { get; set; }

		///<summary>
		///申请人协同编码
		///</summary>
		public string ApplyUserCodeXt { get; set; }

		///<summary>
		///申请部门ID
		///</summary>
		public long? ApplyDepartmentId { get; set; }

		///<summary>
		///申请部门协同编码
		///</summary>
		public string ApplyDepartmentCodeXt { get; set; }

		///<summary>
		///申请部门
		///</summary>
		public string ApplyDepartment { get; set; }

		///<summary>
		///申请分公司ID
		///</summary>
		public long? ApplyCompanyId { get; set; }

		///<summary>
		///
		///</summary>
		public string ApplyCompanyCodeXt { get; set; }

		///<summary>
		///申请分公司
		///</summary>
		public string ApplyCompanyName { get; set; }

		///<summary>
		///合同ID，合同表
		///</summary>
		public long? ContractId { get; set; }

		///<summary>
		///合同编码
		///</summary>
		public string ContractCode { get; set; }

		///<summary>
		///合同名称
		///</summary>
		public string ContractName { get; set; }

		///<summary>
		///合同附件路径（预留）
		///</summary>
		public string ContractEnclosure { get; set; }

		///<summary>
		///合同报审序号
		///</summary>
		public string ContractNumber { get; set; }

		///<summary>
		///ERP订单
		///</summary>
		public string ErpCode { get; set; }

		///<summary>
		///到货联系人
		///</summary>
		public string ArrivalContacts { get; set; }

		///<summary>
		///到货联系电话
		///</summary>
		public string ArrivalContactsTel { get; set; }

		///<summary>
		///到货联系地址
		///</summary>
		public string ArrivalAddress { get; set; }

		///<summary>
		///供应商ID，可为空，非空管理供应商表
		///</summary>
		public long? SupplierId { get; set; }

		///<summary>
		///供应商编码
		///</summary>
		public string SupplierCode { get; set; }

		///<summary>
		///供应商名称
		///</summary>
		public string Supplier { get; set; }

		///<summary>
		///供应商邮编
		///</summary>
		public string SupplierZipCode { get; set; }

		///<summary>
		///供应商联系人
		///</summary>
		public string SupplierContacts { get; set; }

		///<summary>
		///供应商联系电话
		///</summary>
		public string SupplierTel { get; set; }

		///<summary>
		///供应商地址
		///</summary>
		public string SupplierAddress { get; set; }

		///<summary>
		///分管领导ID
		///</summary>
		public long? LeadershipId { get; set; }

		///<summary>
		///分管领导协同编码
		///</summary>
		public string LeadershipCodeXt { get; set; }

		///<summary>
		///分管领导
		///</summary>
		public string LeadershipName { get; set; }

		///<summary>
		///申请总金额
		///</summary>
		public decimal? ApplyAmount { get; set; }

		///<summary>
		///状态：暂存、待审核、审核通过、审核不通过
		///</summary>
		public int? State { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }
        /// <summary>
        /// 验收状态
        /// </summary>
        public bool UseType { get; set; }

        /// <summary>
        /// 数量
        /// </summary>
        public decimal? Number { get; set; }
        /// <summary>
        /// 协同
        /// </summary>
        public string WorkFlowId { get; set; }



        [NotMapped]
        public List<Epm_TzAttachs> TzAttachs { get; set; }

        [NotMapped]
        public List<Epm_TzSupMatApplyList> TzSupMatApplyList { get; set; }


        public string StateName { get; set; }
        public string ApprovalName { get; set; }
        public long ApprovalNameId { get; set; }
        public DateTime? WorkStartApprovalTime { get; set; }
        public string StateType { get; set; }

        /// <summary>
        /// 申请时间
        /// </summary>
        public DateTime? SupApplyTime { get; set; }

        /// <summary>
        /// 合计数量
        /// </summary>
        [NotMapped]
        public decimal? TotleNum { get; set; }

        /// <summary>
        /// 合计金额
        /// </summary>
        [NotMapped]
        public decimal? TotleMoney { get; set; }

        /// <summary>
        /// 审批部门
        /// </summary>
        [NotMapped]
        public string ApprovalDep { get; set; }

        /// <summary>
        /// 签名地址
        /// </summary>
        [NotMapped]
        public string SignNameUrl { get; set; }
    }
}

