//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-08-14 09:32:30
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_PlanDelayCompany:
	///</summary>
	 public  class  Epm_PlanDelayCompany: BaseBusiness
    { 
		///<summary>
		///
		///</summary>
		public long ProjectId { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///
		///</summary>
		public long DelayId { get; set; }

		///<summary>
		///
		///</summary>
		public long CompanyId { get; set; }

		///<summary>
		///
		///</summary>
		public string CompanyName { get; set; }

		///<summary>
		///
		///</summary>
		public decimal DelayDay { get; set; }

		///<summary>
		///
		///</summary>
		public int State { get; set; }

	}
}

