//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_Notice:公告表
    ///</summary>
    public class Epm_Notice : BaseBusiness
    {
        ///<summary>
        ///标题
        ///</summary>
        public string Title { get; set; }

        ///<summary>
        ///内容
        ///</summary>
        public string Content { get; set; }

        ///<summary>
        ///发布人Id
        ///</summary>
        public long? SendUserId { get; set; }

        ///<summary>
        ///发布人Name
        ///</summary>
        public string SendUserName { get; set; }

        /// <summary>
        /// 发布时间
        /// </summary>
        public DateTime? SendTime { get; set; }

        /// <summary>
        /// 发布途径0无 1PC 2APP 3PC和APP
        /// </summary>
        public int? WayOfRelease { get; set; }

        ///<summary>
        ///状态 1 启用 0 禁用
        ///</summary>
        public int? State { get; set; }

        ///<summary>
        ///备注
        ///</summary>
        public string Remark { get; set; }

    }
}
