//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:52
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_Question:问题表
	///</summary>
	 public  class  Epm_Question:BaseBusiness
	{ 
		///<summary>
		///项目表Id
		///</summary>
		public long? ProjectId { get; set; }

		///<summary>
		///项目名称
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///标题
		///</summary>
		public string Title { get; set; }

		///<summary>
		///描述
		///</summary>
		public string Description { get; set; }

		///<summary>
		///建议
		///</summary>
		public string Proposal { get; set; }

		///<summary>
		///是否重大事故，1是，2不是，枚举
		///</summary>
		public bool? IsAccident { get; set; }

		///<summary>
		///业务类型Key
		///</summary>
		public string BusinessTypeNo { get; set; }

		///<summary>
		///业务类型Value
		///</summary>
		public string BusinessTypeName { get; set; }

		///<summary>
		///业务类型Key
		///</summary>
		public long? BusinessId { get; set; }

		///<summary>
		///提报人Id
		///</summary>
		public long? SubmitUserId { get; set; }

		///<summary>
		///提报人Name
		///</summary>
		public string SubmitUserName { get; set; }

		///<summary>
		///提报时间
		///</summary>
		public DateTime? SubmitTime { get; set; }

		///<summary>
		///提报单位Id
		///</summary>
		public long? SubmitCompanyId { get; set; }

		///<summary>
		///提报单位Name
		///</summary>
		public string SubmitCompanyName { get; set; }

		///<summary>
		///接收单位Id
		///</summary>
		public long? RecCompanyId { get; set; }

		///<summary>
		///接收单位Name
		///</summary>
		public string RecCompanyName { get; set; }

        ///<summary>
        ///接收UserId
        ///</summary>
        public long? RecUserId { get; set; }

        ///<summary>
        ///接收UserName
        ///</summary>
        public string RecUserName { get; set; }

        ///<summary>
        ///状态[1正常、2关闭]枚举
        ///</summary>
        public int? State { get; set; }

		///<summary>
		///关闭时间
		///</summary>
		public DateTime? CloseTime { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

        /// <summary>
        /// 问题类型名称
        /// </summary>
        public string ProblemTypeName { get; set; }

        /// <summary>
        /// 问题类型编码
        /// </summary>
        public string ProblemTypeNo { get; set; }

    }
}

