//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-02-14 14:04:37
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_Rectification:
    ///</summary>
    public class Epm_Rectification : BaseBusiness
    {
        ///<summary>
        ///
        ///</summary>
        public long? ProjectId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectName { get; set; }

        ///<summary>
        /// 检查单位Id
        ///</summary>
        public long? InsppectId { get; set; }

        ///<summary>
        /// 整改标题
        ///</summary>
        public string RectificateTitle { get; set; }

        ///<summary>
        /// 检查地址
        ///</summary>
        public string InspectAddress { get; set; }

        ///<summary>
        /// 检查日期
        ///</summary>
        public DateTime? InspectDate { get; set; }

        ///<summary>
        /// 检查人
        ///</summary>
        public long? InspectUserId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string InspectUserName { get; set; }

        ///<summary>
        /// 整改负责人Id
        ///</summary>
        public long? RectifRecordUserId { get; set; }

        ///<summary>
        /// 整改负责人
        ///</summary>
        public string RectifRecordUserName { get; set; }

        /// <summary>
        /// 待整改、已完成
        /// </summary>
        public int? State { get; set; }

    }
}

