//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-08-21 14:35:34
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
    ///<summary>
    ///Epm_TzCodeMap: 编码映射表
    ///</summary>
     public  class  Epm_TzCodeMap:BaseBusiness
    {
        ///<summary>
        /// 编码映射类型 参考枚举 CodeMapType
        ///</summary>
        public string CodeType { get; set; }

        ///<summary>
        /// 映射系统 参考枚举 SysMapType
        ///</summary>
        public string MapType { get; set; }

        ///<summary>
        /// 源系统编码
        ///</summary>
        public string From_Code { get; set; }

        ///<summary>
        /// 源系统名称
        ///</summary>
        public string From_Name { get; set; }

        ///<summary>
        /// 映射系统编码
        ///</summary>
        public string To_Code { get; set; }

        ///<summary>
        /// 映射系统名称
        ///</summary>
        public string To_Name { get; set; }

        ///<summary>
        /// 备注 1
        ///</summary>
        public string Remark1 { get; set; }

        ///<summary>
        /// 备注 2
        ///</summary>
        public string Remark2 { get; set; }

        ///<summary>
        /// 备注 3
        ///</summary>
        public string Remark3 { get; set; }

        ///<summary>
        /// 备注 4
        ///</summary>
        public string Remark4 { get; set; }

        ///<summary>
        /// 备注 5
        ///</summary>
        public string Remark5 { get; set; }

    }
}

