//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_Plan:施工计划进度表
    ///</summary>
    public class Epm_Plan : BaseBusiness
    {
        ///<summary>
        ///项目表Id
        ///</summary>
        public long? ProjectId { get; set; }

        ///<summary>
        ///项目名
        ///</summary>
        public string ProjectName { get; set; }

        ///<summary>
        ///父级计划表Id
        ///</summary>
        public long? ParentId { get; set; }

        ///<summary>
        ///里程碑计划名
        ///</summary>
        public string Name { get; set; }

        ///<summary>
        ///计划开工时间
        ///</summary>
        public DateTime? StartTime { get; set; }

        ///<summary>
        ///计划完工时间
        ///</summary>
        public DateTime? EndTime { get; set; }

        ///<summary>
        ///工期，单位天
        ///</summary>
        public decimal? BuildDays { get; set; }

        ///<summary>
        ///施工负责人Id
        ///</summary>
        public long? ContactUserId { get; set; }

        ///<summary>
        ///施工负责人Name
        ///</summary>
        public string ContactUserName { get; set; }

        ///<summary>
        ///施工单位Id
        ///</summary>
        public long? BuildCompanyId { get; set; }

        ///<summary>
        ///施工单位Name
        ///</summary>
        public string BuildCompanyName { get; set; }

        ///<summary>
        ///关键里程碑Id
        ///</summary>
        public long? MilepostId { get; set; }

        ///<summary>
        ///关键里程碑Name
        ///</summary>
        public string MilepostName { get; set; }

        ///<summary>
        ///状态[0草稿 30待审核 35审核通过 40审核不通过 60已废弃]
        ///</summary>
        public int? State { get; set; }

        ///<summary>
        ///实际开始时间
        ///</summary>
        public DateTime? StartDate { get; set; }

        ///<summary>
        ///实际完工时间
        ///</summary>
        public DateTime? EndDate { get; set; }

        ///<summary>
        ///是否完成[1是，0否]枚举
        ///</summary>
        public int? IsFinish { get; set; }

        ///<summary>
        ///滞后天数
        ///</summary>
        public decimal? DelayDays { get; set; }

        ///<summary>
        ///完成比例，例：0-10之间数
        ///</summary>
        public string FinishScale { get; set; }

        ///<summary>
        ///未完成原因
        ///</summary>
        public string NoFinishResean { get; set; }

        ///<summary>
        ///备注
        ///</summary>
        public string Remark { get; set; }

        ///<summary>
        ///创建单位Id
        ///</summary>
        public long? CrtCompanyId { get; set; }

        ///<summary>
        ///创建单位Name
        ///</summary>
        public string CrtCompanyName { get; set; }

        /// <summary>
        /// 批次号
        /// </summary>
        public string BatchNo { get; set; }

        /// <summary>
        /// 计划说明
        /// </summary>
        public string PlanContent { get; set; }

        /// <summary>
        /// 延期计划完工时间
        /// </summary>
        public DateTime? DelayTime { get; set; }
    }
}

