//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-30 10:01:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_Approver:
    ///</summary>
    public class Epm_Approver : BaseBusiness
    {
        ///<summary>
        ///标题
        ///</summary>
        public string Title { get; set; }

        ///<summary>
        ///内容
        ///</summary>
        public string Content { get; set; }

        ///<summary>
        ///提交人Id
        ///</summary>
        public long? SendUserId { get; set; }

        ///<summary>
        ///提交人Name
        ///</summary>
        public string SendUserName { get; set; }

        ///<summary>
        ///提交时间
        ///</summary>
        public DateTime? SendTime { get; set; }

        ///<summary>
        ///点击链接
        ///</summary>
        public string LinkURL { get; set; }

        ///<summary>
        ///是否已处理 0 未处理 1 已处理
        ///</summary>
        public bool? IsApprover { get; set; }

        ///<summary>
        ///待审批人Id
        ///</summary>
        public long? ApproverId { get; set; }

        ///<summary>
        ///待审批人Name
        ///</summary>
        public string ApproverName { get; set; }

        ///<summary>
        ///业务类型Key
        ///</summary>
        public string BusinessTypeNo { get; set; }

        /// <summary>
        /// 项目子类型
        /// </summary>
        public string BussinesChild { get; set; }

        /// <summary>
        /// 业务类型
        /// </summary>
        public int? BusinessState { get; set; }

        ///<summary>
        ///业务类型Value
        ///</summary>
        public string BusinessTypeName { get; set; }

        ///<summary>
        ///业务Id
        ///</summary>
        public long? BusinessId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public int? State { get; set; }

        ///<summary>
        ///备注
        ///</summary>
        public string Remark { get; set; }

        ///<summary>
        ///
        ///</summary>
        public long? CrtCompanyId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string CrtCompanyName { get; set; }

        /// <summary>
        /// 项目ID
        /// </summary>
        public long? ProjectId { get; set; }

        ///<summary>
        ///项目名称
        ///</summary>
        public string ProjectName { get; set; }

        public string Action { get; set; }
    }
}

