//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-08-23 11:11:20
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	/// 完工验收相关整改单位:
	///</summary>
	 public  class  Epm_CompletionRectifyCompany:BaseBusiness
	{ 
		///<summary>
		/// 所属项目
		///</summary>
		public long ProjectId { get; set; }

		///<summary>
		/// 所属项目名称
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		/// 所属完工验收
		///</summary>
		public long AcceptanceId { get; set; }

		///<summary>
		/// 整改单位 ID
		///</summary>
		public long CompanyId { get; set; }

		///<summary>
		/// 整改单位名称
		///</summary>
		public string CompanyName { get; set; }

		///<summary>
		/// 状态
		///</summary>
		public int State { get; set; }

	}
}

