//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:52
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_ProjectCompany:项目参与单位
    ///</summary>
    public class Epm_ProjectCompany : BaseBusiness
    {
        ///<summary>
        ///项目表Id
        ///</summary>
        public long? ProjectId { get; set; }

        ///<summary>
        ///参与单位Id
        ///</summary>
        public long? CompanyId { get; set; }

        ///<summary>
        ///参与单位Name
        ///</summary>
        public string CompanyName { get; set; }

        ///<summary>
        ///单位类型
        ///</summary>
        public string Type { get; set; }

        /// <summary>
        /// 负责人
        /// </summary>
        public long? LinkManId { get; set; }

        /// <summary>
        /// 负责人
        /// </summary>
        public string LinkMan { get; set; }

        /// <summary>
        /// 负责人电话
        /// </summary>
        public string LinkPhone { get; set; }
        ///<summary>
        ///项目经理状态 30待审核，35审核通过，40审核不通过
        ///</summary>
        public int? State { get; set; }

        ///<summary>
        ///备注
        ///</summary>
        public string Remark { get; set; }

        ///<summary>
        ///创建单位Id
        ///</summary>
        public long? CrtCompanyId { get; set; }

        ///<summary>
        ///创建单位Name
        ///</summary>
        public string CrtCompanyName { get; set; }
        /// <summary>
        /// 项目经理Id
        /// </summary>
        public long? PMId { get; set; }
        /// <summary>
        /// 项目经理Name
        /// </summary>
        public string PM { get; set; }
        /// <summary>
        /// 项目经理电话
        /// </summary>
        public string PMPhone { get; set; }

        /// <summary>
        /// 新项目经理
        /// </summary>
        public long? PMId_New { get; set; }
        /// <summary>
        /// 新项目经理
        /// </summary>
        public string PM_New { get; set; }
        /// <summary>
        /// 新项目经理电话
        /// </summary>
        public string PMPhone_New { get; set; }
        /// <summary>
        /// 新项目负责人
        /// </summary>
        public long? LinkManId_New { get; set; }
        /// <summary>
        /// 新项目负责人
        /// </summary>
        public string LinkMan_New { get; set; }
        /// <summary>
        /// 新项目负责人电话
        /// </summary>
        public string LinkPhone_New { get; set; }
        /// <summary>
        /// 项目负责人状态 30待审核，35审核通过，40审核不通过
        /// </summary>
        public int? LinkState { get; set; }
        /// <summary>
        /// 是否监理 1：监理
        /// </summary>
        public int? IsSupervisor { get; set; }
        /// <summary>
        /// 顺序
        /// </summary>
        public int? Sort { get; set; }
        /// <summary>
        /// 是否甲供设备 1是 0否
        /// </summary>
        public bool? IsAProvide { get; set; }

        public long? ContractId { get; set; }
        public string ContractName { get; set; }
        public long? OrderId { get; set; }
        public string OrderName { get; set; }
       // public string OrderCode { get; set; }
        

        /// <summary>
        /// 安全负责人Id
        /// </summary>
        public long? SafeManId { get; set; }
        /// <summary>
        /// 安全负责人
        /// </summary>
        public string SafeMan { get; set; }
        /// <summary>
        /// 安全负责人电话
        /// </summary>
        public string SafePhone { get; set; }
        /// <summary>
        /// 安全负责人Id
        /// </summary>
        public long? SafeManId_New { get; set; }
        /// <summary>
        /// 安全负责人
        /// </summary>
        public string SafeMan_New { get; set; }
        /// <summary>
        /// 安全负责人电话
        /// </summary>
        public string SafePhone_New { get; set; }


        /// <summary>
        /// 技术负责人Id
        /// </summary>
        public long? TechnologyManId { get; set; }
        /// <summary>
        /// 技术负责人
        /// </summary>
        public string TechnologyMan { get; set; }
        /// <summary>
        /// 技术负责人电话
        /// </summary>
        public string TechnologyPhone { get; set; }

        /// <summary>
        /// 技术负责人Id
        /// </summary>
        public long? TechnologyManId_New { get; set; }
        /// <summary>
        /// 技术负责人
        /// </summary>
        public string TechnologyMan_New { get; set; }
        /// <summary>
        /// 技术负责人电话
        /// </summary>
        public string TechnologyPhone_New { get; set; }

        /// <summary>
        /// 合同编码
        /// </summary>
        public string ContractCode { get; set; }
    }
}

