//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
    ///<summary>
    ///Epm_OilStation:加油站信息表
    ///</summary>
     public  class  Epm_OilStation:BaseBusiness
    { 
        ///<summary>
        ///编码
        ///</summary>
        public string Code { get; set; }

        ///<summary>
        ///名称
        ///</summary>
        public string Name { get; set; }

        ///<summary>
        ///地址
        ///</summary>
        public string Address { get; set; }

        ///<summary>
        ///油站介绍
        ///</summary>
        public string Content { get; set; }

        ///<summary>
        ///说明
        ///</summary>
        public string Description { get; set; }

        ///<summary>
        ///预留与本省系统对接
        ///</summary>
        public string Code1 { get; set; }

        ///<summary>
        ///预留与本省系统对接
        ///</summary>
        public string Code2 { get; set; }

        ///<summary>
        ///预留与本省系统对接
        ///</summary>
        public string Code3 { get; set; }

        ///<summary>
        ///预留与本省系统对接 Hos系统 油库编码(来源于协同基础数据同步)
        ///</summary>
        public string Code4 { get; set; }

        ///<summary>
        ///预留与本省系统对接 Fmis系统 油库编码(来源于协同基础数据同步)
        ///</summary>
        public string Code5 { get; set; }

        ///<summary>
        ///状态
        ///</summary>
        public int? State { get; set; }

        ///<summary>
        ///备注
        ///</summary>
        public string Remark { get; set; }

        ///<summary>
        ///创建单位Id
        ///</summary>
        public long? CrtCompanyId { get; set; }

        ///<summary>
        ///创建单位Name
        ///</summary>
        public string CrtCompanyName { get; set; }

        /// <summary>
        /// 所属单位 ID
        /// </summary>
        public long? OrgId { get; set; }

        /// <summary>
        /// 所属单位编码
        /// </summary>
        public string OrgCode { get; set; }

        /// <summary>
        /// 所属单位名称
        /// </summary>
        public string OrgName { get; set; }

        /// <summary>
        /// 经度
        /// </summary>
        public decimal? Longitude { get; set; }

        /// <summary>
        /// 纬度
        /// </summary>
        public decimal? Latitude { get; set; }

        /// <summary>
        /// 加油站地理位置类型
        /// </summary>
        public string PositionType { get; set; }

        /// <summary>
        /// 投资性质
        /// </summary>
        public string InvestType { get; set; }

        /// <summary>
        /// 站点类型
        /// </summary>
        public string StationType { get; set; }

        /// <summary>
        /// 经营方式
        /// </summary>
        public string OperatedType { get; set; }

        /// <summary>
        /// 加油站类别
        /// </summary>
        public string StationLevel { get; set; }

        /// <summary>
        /// 加油站经营状态
        /// </summary>
        public string OperatedState { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string Code6 { get; set; }

        public string Code7 { get; set; }

        /// <summary>
        /// 外部唯一标识
        /// </summary>
        public string ObjeId { get; set; }
    }
}

