//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_DangerousWork:危险作业表
	///</summary>
	 public  class  Epm_DangerousWork:BaseBusiness
	{ 
		///<summary>
		///项目表Id
		///</summary>
		public long? ProjectId { get; set; }

		///<summary>
		///项目名称
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///业主单位Id
		///</summary>
		public long? CompanyId { get; set; }

		///<summary>
		///业主单位Name
		///</summary>
		public string CompanyName { get; set; }

		///<summary>
		///作业名称
		///</summary>
		public string TaskName { get; set; }

		///<summary>
		///开始时间
		///</summary>
		public DateTime? StartTime { get; set; }

		///<summary>
		///结束时间
		///</summary>
		public DateTime? EndTime { get; set; }

		///<summary>
		///作业分类Key
		///</summary>
		public string TaskTypeNo { get; set; }

		///<summary>
		///作业分类Value
		///</summary>
		public string TaskTypeName { get; set; }

		///<summary>
		///作业区域
		///</summary>
		public string TaskArea { get; set; }

		///<summary>
		///作业内容
		///</summary>
		public string TaskContent { get; set; }

		///<summary>
		///防护措施
		///</summary>
		public string Protective { get; set; }

		///<summary>
		///作业单位Id
		///</summary>
		public long? WorkCompanyId { get; set; }

		///<summary>
		///作业单位Name
		///</summary>
		public string workCompanyName { get; set; }

		///<summary>
		///提报人Id
		///</summary>
		public long? SubmitUserId { get; set; }

		///<summary>
		///提报人Nmae
		///</summary>
		public string SubmitUserName { get; set; }

		///<summary>
		///提报单位Id
		///</summary>
		public long? SubmitCompanyId { get; set; }

		///<summary>
		///提报单位Name
		///</summary>
		public string SubmitCompanyName { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

	}
}

