//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-09-17 10:01:25
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_ConstituteCompanyDetails:
	///</summary>
	 public  class  Epm_ConstituteCompanyDetails:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public long? ConstituteCompanyId { get; set; }

		///<summary>
		///
		///</summary>
		public long? CompanyId { get; set; }

		///<summary>
		///
		///</summary>
		public string CompanyName { get; set; }

        public string ConstituteKey { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ConstituteName { get; set; }
        ///<summary>
        ///
        ///</summary>
        public long? CrtCompanyId { get; set; }

		///<summary>
		///
		///</summary>
		public string CrtCompanyName { get; set; }

	}
}

