//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-10-14 17:32:47
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_TzResearchOfLaw:现场法律调研
	///</summary>
	 public  class  Epm_TzResearchOfLaw:BaseBusiness
	{ 
		///<summary>
		///所属项目ID
		///</summary>
		public long ProjectId { get; set; }

		///<summary>
		///调研开始日期
		///</summary>
		public DateTime? ResearchStartDate { get; set; }

		///<summary>
		///调研截止日期
		///</summary>
		public DateTime? ResearchEndDate { get; set; }

		///<summary>
		///调研人ID
		///</summary>
		public long? ResearchUserId { get; set; }

		///<summary>
		///调研人姓名
		///</summary>
		public string ResearchUserName { get; set; }

		///<summary>
		///调研人协同OA 编码
		///</summary>
		public string ResearchUserXt { get; set; }

		///<summary>
		///职务编码(字典)
		///</summary>
		public string JobCode { get; set; }

		///<summary>
		///职务名称
		///</summary>
		public string JobName { get; set; }

		///<summary>
		///产权清晰
		///</summary>
		public string PropertyRights { get; set; }

		///<summary>
		///资产主体资格
		///</summary>
		public string AssetSubject { get; set; }

		///<summary>
		///纠纷判断
		///</summary>
		public string DisputesJudgment { get; set; }

		///<summary>
		///证照类型
		///</summary>
		public string License { get; set; }

		///<summary>
		///
		///</summary>
		public int State { get; set; }

		///<summary>
		///
		///</summary>
		//public long? OpearateUserId { get; set; }

		/////<summary>
		/////
		/////</summary>
		//public string OpearateUserName { get; set; }

		/////<summary>
		/////
		/////</summary>
		//public DateTime? OpearateTime { get; set; }

	}
}

