//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:52
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_QuestionBIM:问题关联构件表
    ///</summary>
    public class Epm_QuestionBIM : BaseBusiness
    {
        ///<summary>
        ///问题表Id
        ///</summary>
        public long? QuestionId { get; set; }

        ///<summary>
        ///模型Id
        ///</summary>
        public long BIMId { get; set; }

        ///<summary>
        ///模型Name
        ///</summary>
        public string BIMName { get; set; }

        ///<summary>
        ///构件Id
        ///</summary>
        public string ComponentId { get; set; }

        ///<summary>
        ///构件Name
        ///</summary>
        public string ComponentName { get; set; }

        ///<summary>
        ///顺序
        ///</summary>
        public long? Sort { get; set; }

        ///<summary>
        ///状态
        ///</summary>
        public int? State { get; set; }

        ///<summary>
        ///备注
        ///</summary>
        public string Remark { get; set; }

        ///<summary>
        ///创建单位Id
        ///</summary>
        public long? CrtCompanyId { get; set; }

        ///<summary>
        ///创建单位Name
        ///</summary>
        public string CrtCompanyName { get; set; }

        /// <summary>
        /// 构件坐标
        /// </summary>
        public string ComponentPosition { get; set; }
    }
}

