//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:52
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_Visa:签证表
    ///</summary>
    public class Epm_Visa : BaseBusiness
    {
        ///<summary>
        ///项目表Id
        ///</summary>
        public long? ProjectId { get; set; }

        ///<summary>
        ///项目名称
        ///</summary>
        public string ProjectName { get; set; }

        ///<summary>
        ///变更表Id
        ///</summary>
        public long? ChangeId { get; set; }

        ///<summary>
        ///变更名称
        ///</summary>
        public string ChangeName { get; set; }

        ///<summary>
        ///签证号
        ///</summary>
        public string VisaNo { get; set; }

        ///<summary>
        ///标题
        ///</summary>
        public string VisaTitle { get; set; }

        ///<summary>
        ///原因
        ///</summary>
        public string VisaResean { get; set; }

        ///<summary>
        ///内容
        ///</summary>
        public string VisaContent { get; set; }

        ///<summary>
        ///金额，单位万元
        ///</summary>
        public decimal? VisaAmount { get; set; }

        ///<summary>
        ///签证开始时间
        ///</summary>
        public DateTime? VisaStartTime { get; set; }

        ///<summary>
        ///签证结束时间
        ///</summary>
        public DateTime? VisaEndTime { get; set; }

        ///<summary>
        ///签证工期，单位天
        ///</summary>
        public decimal? VisaDays { get; set; }

        ///<summary>
        ///发起人Id
        ///</summary>
        public long? SubmitUserId { get; set; }

        ///<summary>
        ///发起人Name
        ///</summary>
        public string SubmitUserName { get; set; }

        ///<summary>
        ///发起时间
        ///</summary>
        public DateTime? SubmitTime { get; set; }

        ///<summary>
        ///状态[10待处理,20审核通过,30已驳回,40已废弃]枚举
        ///</summary>
        public int? State { get; set; }

        ///<summary>
        ///备注
        ///</summary>
        public string Remark { get; set; }

        ///<summary>
        ///创建单位Id
        ///</summary>
        public long? CrtCompanyId { get; set; }

        ///<summary>
        ///创建单位Name
        ///</summary>
        public string CrtCompanyName { get; set; }

        /// <summary>
        /// 签证类型
        /// </summary>
        public string VisaTypeName { get; set; }

    }
}

