//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-08-14 08:57:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///EPM_ProjectContract:
    ///</summary>
    public class Epm_ProjectContract : BaseBusiness
    {
        ///<summary>
        ///项目Id
        ///</summary>
        public long? ProjectId { get; set; }

        ///<summary>
        ///合同Id
        ///</summary>
        public long? ContractId { get; set; }

        ///<summary>
        ///服务商
        ///</summary>
        public long? SecondPartyId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string SecondPartyName { get; set; }

    }
}

