//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_MonitorDetails:安全质量检查明细表
	///</summary>
	 public  class  Epm_MonitorDetails:BaseBusiness
	{ 
		///<summary>
		///检查表Id
		///</summary>
		public long? MonitorId { get; set; }

		///<summary>
		///编号
		///</summary>
		public string Code { get; set; }

		///<summary>
		///名称
		///</summary>
		public string Name { get; set; }

		///<summary>
		///监测结果Key
		///</summary>
		public string MonitorResultNo { get; set; }

		///<summary>
		///监测结果Value
		///</summary>
		public string MonitorResultName { get; set; }

		///<summary>
		///顺序
		///</summary>
		public int? Sort { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

        ///<summary>
        /// 整改单位ID
        ///</summary>
        public long? RectifCompanyId { get; set; }

        ///<summary>
        /// 整改单位名称
        ///</summary>
        public string RectifCompanyName { get; set; }

        ///<summary>
        /// 问题 ID
        ///</summary>
        public long? QuestionId { get; set; }

        ///<summary>
        /// 限期整改日期
        ///</summary>
        public DateTime? Deadline { get; set; }

        ///<summary>
        /// 整改完成日期
        ///</summary>
        public DateTime? FinishDate { get; set; }
    }
}

