//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-10-29 15:11:32
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_TzProjectApprovalInfo:项目批复信息
    ///</summary>
    public class  Epm_TzProjectApprovalInfo:BaseBusiness
	{ 
		///<summary>
		///所属项目ID
		///</summary>
		public long ProjectId { get; set; }

		///<summary>
		///限下/限上编码
		///</summary>
		public string LimitCode { get; set; }

		///<summary>
		///限下/限上
		///</summary>
		public string LimitName { get; set; }

		///<summary>
		///示范/标准编码
		///</summary>
		public string StandardCode { get; set; }

		///<summary>
		///示范/标准
		///</summary>
		public string StandardName { get; set; }

		///<summary>
		///评审编码
		///</summary>
		public string ReviewCode { get; set; }

		///<summary>
		///
		///</summary>
		public string ReviewName { get; set; }

		///<summary>
		///拟稿人id
		///</summary>
		public long? DraftAuthorId { get; set; }

		///<summary>
		///拟稿人名称
		///</summary>
		public string DraftAuthorName { get; set; }

		///<summary>
		///拟稿人协同OA编码
		///</summary>
		public string DraftAuthorXt { get; set; }

		///<summary>
		///会签人id
		///</summary>
		public long? SignPeopleId { get; set; }

		///<summary>
		///会签人名称
		///</summary>
		public string SignPeopleName { get; set; }

		///<summary>
		///会签人协同OA编码
		///</summary>
		public string SignPeopleXt { get; set; }

		///<summary>
		///签发人id
		///</summary>
		public long? SignerId { get; set; }

		///<summary>
		///签发人名称
		///</summary>
		public string SignerName { get; set; }

		///<summary>
		///签发人协同OA编码
		///</summary>
		public string SignerXt { get; set; }

		///<summary>
		///现场负责人id
		///</summary>
		public long? FieldManagerId { get; set; }

		///<summary>
		///现场负责人名称
		///</summary>
		public string FieldManagerName { get; set; }

		///<summary>
		///现场负责人协同OA编码
		///</summary>
		public string FieldManagerXt { get; set; }

		///<summary>
		///决策负责人id
		///</summary>
		public long? DecisionMakerId { get; set; }

		///<summary>
		///决策负责人名称
		///</summary>
		public string DecisionMakerName { get; set; }

		///<summary>
		///决策负责人协同OA编码
		///</summary>
		public string DecisionMakerXt { get; set; }

		///<summary>
		///运营负责人id
		///</summary>
		public long? HeadOperationsId { get; set; }

		///<summary>
		///运营负责人名称
		///</summary>
		public string HeadOperationsName { get; set; }

		///<summary>
		///运营负责人协同OA编码
		///</summary>
		public string HeadOperationsXt { get; set; }

		///<summary>
		///生成批复（请示）文号
		///</summary>
		public string ApprovalNo { get; set; }

		///<summary>
		///总投资(万元）
		///</summary>
		public decimal? TotalInvestment { get; set; }

		///<summary>
		///合同款(万元）
		///</summary>
		public decimal? ContractPayment { get; set; }

		///<summary>
		///工程费用(万元）
		///</summary>
		public decimal? EngineeringCost { get; set; }

		///<summary>
		///土地费用(万元）
		///</summary>
		public decimal? LandCosts { get; set; }

		///<summary>
		///其他费用(万元）
		///</summary>
		public decimal? OtherExpenses { get; set; }

		///<summary>
		///已下达计划
		///</summary>
		public decimal? IssuedPlan { get; set; }

		///<summary>
		///首次取得投资计划日期
		///</summary>
		public DateTime? DateFirstScheme { get; set; }

		///<summary>
		///MDM编码
		///</summary>
		public string MdmCode { get; set; }

		///<summary>
		///下达投资额(万元）
		///</summary>
		public decimal? ReleaseInvestmentAmount { get; set; }

		///<summary>
		///批次
		///</summary>
		public string Batch { get; set; }

		///<summary>
		///年份
		///</summary>
		public DateTime? Year { get; set; }

		///<summary>
		///加油机（台）
		///</summary>
		public int? MachineOfOilStage { get; set; }

		///<summary>
		///加油机（枪）
		///</summary>
		public int? MachineOfOil { get; set; }

		///<summary>
		///加气机（枪）
		///</summary>
		public int? MachineOfGasStage { get; set; }

		///<summary>
		///加气机（台）
		///</summary>
		public int? MachineOfGas { get; set; }

		///<summary>
		///罩棚
		///</summary>
		public decimal? Shelter { get; set; }

		///<summary>
		///油罐
		///</summary>
		public decimal? OilTank { get; set; }

		///<summary>
		///站房
		///</summary>
		public decimal? StationRoom { get; set; }

		///<summary>
		///油罐数量
		///</summary>
		public int? TankNumber { get; set; }

		///<summary>
		///储气井（气罐）
		///</summary>
		public decimal? GasWells { get; set; }

		///<summary>
		///土地费用支付类型
		///</summary>
		public string LandPaymentType { get; set; }

		///<summary>
		///
		///</summary>
		public string LandPayment { get; set; }

		///<summary>
		///资产类型编码
		///</summary>
		public string AssetType { get; set; }

		///<summary>
		///资产类型
		///</summary>
		public string AssetTypeName { get; set; }

		///<summary>
		///股比
		///</summary>
		public string ProportionOfShare { get; set; }

		///<summary>
		///土地性质
		///</summary>
		public string LandStatusCode { get; set; }

		///<summary>
		///土地性质名称
		///</summary>
		public string LandStatus { get; set; }

		///<summary>
		///土地用途
		///</summary>
		public string LandUseCode { get; set; }

		///<summary>
		///土地用途名称
		///</summary>
		public string LandUse { get; set; }

		///<summary>
		///土地面积(平米)
		///</summary>
		public decimal? AreaOfLand { get; set; }

		///<summary>
		///土地费用备注
		///</summary>
		public string RemarkOnLandCost { get; set; }

		///<summary>
		///今年预计付款(万元）
		///</summary>
		public decimal? ExpectedPaymentThisYear { get; set; }

		///<summary>
		///预计达销时间
		///</summary>
		public int? EstimatedTimeOfSales { get; set; }

		///<summary>
		///可研编制单位
		///</summary>
		public string UnitFeasibilityCompilation { get; set; }

		///<summary>
		///变更后总投资(万元）
		///</summary>
		public decimal? TotalInvestmentAfterChange { get; set; }

		///<summary>
		///变更后批复文号
		///</summary>
		public string ChangeReplyNo { get; set; }

		///<summary>
		///股权投资形式
		///</summary>
		public string FormOfEquityInvestment { get; set; }

		///<summary>
		///注册资本(万元）
		///</summary>
		public decimal? RegisteredCapital { get; set; }

		///<summary>
		///控股比例
		///</summary>
		public string HoldingTheProportion { get; set; }

		///<summary>
		///资金来源编码(字典)
		///</summary>
		public string CapitalSourceCode { get; set; }

		///<summary>
		///资金来源
		///</summary>
		public string CapitalSource { get; set; }

		///<summary>
		///投资金额(万元）
		///</summary>
		public decimal? InvestmentAmount { get; set; }

		///<summary>
		///费用金额
		///</summary>
		public decimal? CostAmount { get; set; }

		///<summary>
		///租赁期
		///</summary>
		public string Leasehold { get; set; }

		///<summary>
		///年租赁费(万元）
		///</summary>
		public decimal? AnnualRent { get; set; }

		///<summary>
		///租赁开始日期
		///</summary>
		public DateTime? StratLeaseDate { get; set; }

		///<summary>
		///租赁结束日期
		///</summary>
		public DateTime? EndLeaseDate { get; set; }

		///<summary>
		///年均租赁费
		///</summary>
		public decimal? AvgLeaseDate { get; set; }

		///<summary>
		///付款方式
		///</summary>
		public string PaymentMethod { get; set; }

		///<summary>
		///租金利润率
		///</summary>
		public string ProfitRateOfRent { get; set; }

		///<summary>
		///柴油日销量
		///</summary>
		public decimal? DailyDieselSales { get; set; }

		///<summary>
		///汽油日销量
		///</summary>
		public decimal? DailyGasolineSales { get; set; }

		///<summary>
		///柴汽比
		///</summary>
		public string ChaiQibi { get; set; }

		///<summary>
		///气日销量 QCNG（扩建项目此处填增量）
		///</summary>
		public decimal? CNGY { get; set; }

        ///<summary>
        ///气日销量 QLNG（扩建项目此处填增量）
        ///</summary>
        public decimal? LNGQ { get; set; }

        /// <summary>
        /// 实施单位
        /// </summary>
        public string ImplementationCcompany { get; set; }
        
        ///<summary>
        ///投资回收期
        ///</summary>
        public string PayBackPeriod { get; set; }

		///<summary>
		///内部收益率
		///</summary>
		public string InternalRateReturn { get; set; }

		///<summary>
		///非油年收入
		///</summary>
		public decimal? AnnualNonOilIncome { get; set; }

		///<summary>
		///非油年成本
		///</summary>
		public decimal? NonOilAnnualCost { get; set; }

		///<summary>
		///预计投运时间
		///</summary>
		public DateTime? ScheduledComTime { get; set; }

		///<summary>
		///可研批复日期
		///</summary>
		public DateTime? FeasibleApprovalDate { get; set; }

		///<summary>
		///是否有工程信息
		///</summary>
		public string HasEInformation { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

        ///<summary>
		///地区公司
		///</summary>
		public string RegionCompany { get; set; }

        ///<summary>
		///项目类型
		///</summary>
		public string ProjectType { get; set; }

        /// <summary>
        /// /项目类型编号
        /// </summary>
        public string ProjectTypeCode { get; set; }

        /// <summary>
        /// 相关附件(扩展字段)
        /// </summary>
        [NotMapped]
        public List<Epm_TzAttachs> TzAttachs { get; set; }

        ///<summary>
        ///估计气日销量(CNG)/单位：千方
        ///</summary>
        [NotMapped]
        public decimal? CNG { get; set; }

        ///<summary>
        ///估计气日销量(LNG)/单位：千方
        ///</summary>
        [NotMapped]
        public decimal? LNG { get; set; }

        ///<summary>
        ///估计油日销量
        ///</summary>
        [NotMapped]
        public decimal? OilSalesTotal { get; set; }
        /// <summary>
        /// 流程申请 ID
        /// </summary>
        public string WorkFlowId { get; set; }

        ///<summary>
        ///当前状态
        ///</summary>
        public string StateType { get; set; }

        ///<summary>
        ///状态编码
        ///</summary>
        public string StateName { get; set; }

        /// <summary>
        /// 当前审批人
        /// </summary>
        public string ApprovalName { get; set; }

        /// <summary>
        /// 当前审批人Id
        /// </summary>
        public long? ApprovalNameId { get; set; }

        /// <summary>
        /// 开工报告审批时间（本次流程全部审批完成时间（年月日），若还未完成审批，不显示）
        /// </summary>
        public DateTime? WorkStartApprovalTime { get; set; }

        ///<summary>
        ///财务决算
        ///</summary>
        public decimal? FinanceAccounts { get; set; }

        ///<summary>
        ///财务决算操作人
        ///</summary>
        public string FinanceUserName { get; set; }

        ///<summary>
        ///财务决算操作人ID
        ///</summary>
        public long? FinanceUserId { get; set; }

        ///<summary>
        ///财务决算操作时间
        ///</summary>
        public DateTime? FinanceTime { get; set; }

        /// <summary>
        /// 项目名称
        /// </summary>
        [NotMapped]
        public string ProjectName { get; set; }

        /// <summary>
        /// 项目性质编码
        /// </summary>
        [NotMapped]
        public string Nature { get; set; }

        /// <summary>
        /// 项目性质名称
        /// </summary>
        [NotMapped]
        public string NatureName { get; set; }
    }
}

