//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:52
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_SpecialAcceptanceDetails:专项验收明细表
    ///</summary>
    public class Epm_SpecialAcceptanceDetails : BaseBusiness
    {
        ///<summary>
        ///专项验收表Id
        ///</summary>
        public long? SpecialCheckId { get; set; }

        /// <summary>
        /// 检查类型
        /// </summary>
        public string Type { get; set; }

        ///<summary>
        ///名称
        ///</summary>
        public string Name { get; set; }

        ///<summary>
        ///结果【合格、不合格、优良】枚举
        ///</summary>
        public string Result { get; set; }

        ///<summary>
        ///顺序
        ///</summary>
        public int? Sort { get; set; }

        ///<summary>
        ///状态
        ///</summary>
        public int? State { get; set; }

        ///<summary>
        ///备注
        ///</summary>
        public string Remark { get; set; }

        ///<summary>
        ///创建单位Id
        ///</summary>
        public long? CrtCompanyId { get; set; }

        ///<summary>
        ///创建单位Name
        ///</summary>
        public string CrtCompanyName { get; set; }

    }
}

