//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:52
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_ProjectData:项目关联资料表
	///</summary>
	 public  class  Epm_ProjectData:BaseBusiness
	{ 
		///<summary>
		///项目表Id
		///</summary>
		public long? ProjectId { get; set; }

		///<summary>
		///里程碑表Id
		///</summary>
		public long? MilepostId { get; set; }

		///<summary>
		///里程碑名称
		///</summary>
		public string MilepostName { get; set; }

		///<summary>
		///项目资料表Id
		///</summary>
		public long? DataFileId { get; set; }

		///<summary>
		///编码
		///</summary>
		public string FileCode { get; set; }

		///<summary>
		///资料Name
		///</summary>
		public string FileName { get; set; }

		///<summary>
		///是否必须，1是，2否，枚举
		///</summary>
		public bool? IsRequire { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

	}
}

