//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-10-14 17:32:47
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_TzResearchOfInvestment:现场投资调研
	///</summary>
	 public  class  Epm_TzResearchOfInvestment:BaseBusiness
	{ 
		///<summary>
		///所属项目Id
		///</summary>
		public long ProjectId { get; set; }

		///<summary>
		///调研开始日期
		///</summary>
		public DateTime? ResearchStartDate { get; set; }

		///<summary>
		///调研截止日期
		///</summary>
		public DateTime? ResearchEndDate { get; set; }

		///<summary>
		///调研人ID
		///</summary>
		public long? ResearchUserId { get; set; }

		///<summary>
		///调研人姓名
		///</summary>
		public string ResearchUserName { get; set; }

		///<summary>
		///调研人协同OA编码
		///</summary>
		public string ResearchUserXt { get; set; }

		///<summary>
		///职务编码(字典)
		///</summary>
		public string JobCode { get; set; }

		///<summary>
		///职务名称
		///</summary>
		public string JobName { get; set; }

		///<summary>
		///详细地理位置
		///</summary>
		public string Address { get; set; }

		///<summary>
		///周边环境编码
		///</summary>
		public string EnvironmentTypeCode { get; set; }

		///<summary>
		///周边环境名称
		///</summary>
		public string EnvironmentTypeName { get; set; }

		///<summary>
		///土地性质编码
		///</summary>
		public string LandNatureCode { get; set; }

		///<summary>
		///土地性质名称
		///</summary>
		public string LandNatureName { get; set; }

		///<summary>
		///土地用途编码
		///</summary>
		public string LandUseCode { get; set; }

		///<summary>
		///
		///</summary>
		public string LandUseName { get; set; }

		///<summary>
		///土地面积
		///</summary>
		public decimal? LandArea { get; set; }

		///<summary>
		///土地形状(临街长度)米
		///</summary>
		public decimal? LandShape { get; set; }

		///<summary>
		///是否符合地区建站规划
		///</summary>
		public string IsMeetAreaPlan { get; set; }

		///<summary>
		///周边车辆保有量(辆)
		///</summary>
		public int? AroundCarCount { get; set; }

		///<summary>
		///平均日车流辆
		///</summary>
		public int? DailyTraffic { get; set; }

		///<summary>
		///成品油销量测算(吨/日)
		///</summary>
		public decimal? OilSaleTotal { get; set; }

		///<summary>
		///柴汽比
		///</summary>
		public string DieselGasolineRatio { get; set; }

		///<summary>
		///土地价格(万元/亩)
		///</summary>
		public decimal? LandPrice { get; set; }

		///<summary>
		///气销量测算(千方/日)
		///</summary>
		public decimal? GasSaleTotal { get; set; }

		///<summary>
		///状态
		///</summary>
		public int State { get; set; }

	}
}

