//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-08-15 09:04:34
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_AttendanceList:
    ///</summary>
    public class Epm_AttendanceList : BaseBusiness
    {
        ///<summary>
        ///项目ID
        ///</summary>
        public long projectid { get; set; }

        ///<summary>
        //姓名ID
        ///</summary>
        public long? personid { get; set; }

        ///<summary>
        ///姓名
        ///</summary>
        public string name { get; set; }
        /// <summary>
        /// 许可
        /// </summary>
        public string permit { get; set; }
        /// <summary>
        /// 到场
        /// </summary>
        public string bepresent { get; set; }
        /// <summary>
        /// 工种ID
        /// </summary>
        public string workPeopleTypeId { get; set; }
        /// <summary>
        /// 工种
        /// </summary>
        public string workPeopleTypeName { get; set; }

        ///<summary>
        ///电话
        ///</summary>
        public string phone { get; set; }
        /// <summary>
        /// 供应商ID
        /// </summary>
        public string companyid { get; set; }
        /// <summary>
        /// 供应商名称
        /// </summary>
        public string companyname { get; set; }
        /// <summary>
        /// 详情ID
        /// </summary>

        public long? detailsid { get; set; }

    }
}

