//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-11-04 18:14:38
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_TzSupMatManagement:甲供物资管理
    ///</summary>
    public class Epm_TzSupMatManagement : BaseBusiness
    {
        ///<summary>
        ///供应商ID
        ///</summary>
        public long? SupplierId { get; set; }

        ///<summary>
        ///供应商编码，内部供应商
        ///</summary>
        public string SupplierCode { get; set; }

        ///<summary>
        ///供应商名称
        ///</summary>
        public string SupplierName { get; set; }

        ///<summary>
        ///供应商联系人
        ///</summary>
        public string SupplierContacts { get; set; }

        ///<summary>
        ///供应商联系电话
        ///</summary>
        public string SupplierTel { get; set; }

        ///<summary>
        ///供应商地址
        ///</summary>
        public string SupplierAddress { get; set; }

        ///<summary>
        ///物资种类
        ///</summary>
        public string MaterialCategory { get; set; }

        ///<summary>
        ///单价
        ///</summary>
        public decimal? UnitePrice { get; set; }

        ///<summary>
        ///品名
        ///</summary>
        public string ProductName { get; set; }

        ///<summary>
        ///规格
        ///</summary>
        public string Specification { get; set; }

        ///<summary>
        ///状态：禁用1、启用0
        ///</summary>
        public int? State { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Remark { get; set; }

    }
}

