//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-08-14 15:31:40
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///EPM_CheckItem:
    ///</summary>
    public class Epm_CheckItem : BaseBusiness
    {
        ///<summary>
        ///父Id
        ///</summary>
        public long? ParentId { get; set; }

        ///<summary>
        ///父Name
        ///</summary>
        public string ParentName { get; set; }

        ///<summary>
        ///检查项名
        ///</summary>
        public string Name { get; set; }

        ///<summary>
        ///检查描述
        ///</summary>
        public string Description { get; set; }

        ///<summary>
        ///层级1,2,3
        ///</summary>
        public int? Level { get; set; }

        ///<summary>
        ///排序
        ///</summary>
        public int? Sort { get; set; }

        ///<summary>
        ///
        ///</summary>
        public int? State { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Remark { get; set; }

        ///<summary>
        ///
        ///</summary>
        public long? CrtCompanyId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string CrtCompanyName { get; set; }

        /// <summary>
        /// 整改责任人
        /// </summary>
        public string RectificationManName { get; set; }

        /// <summary>
        /// 销项人
        /// </summary>
        public string SalesPerson { get; set; }

        /// <summary>
        /// 得分
        /// </summary>
        public string ScoreRange { get; set; }

        /// <summary>
        /// 可查阅人员
        /// </summary>
        public string ConsultMan { get; set; }

        /// <summary>
        /// 得失分单位
        /// </summary>
        public string ScoreCompany { get; set; }

        /// <summary>
        /// 得失分人员
        /// </summary>
        public string ScorePerson { get; set; }

        /// <summary>
        /// 施工单位范围
        /// </summary>
        public string ConstructionUnitRange { get; set; }

        /// <summary>
        /// 角色类型
        /// </summary>
        public string RoleType { get; set; }

        public string QuestionType { get; set; }
    }
}

