//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-11-04 18:14:38
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_TzSupMatApplyList:甲供申请物资详情
    ///</summary>
    public class  Epm_TzSupMatApplyList:BaseBusiness
	{ 
		///<summary>
		///物资申请单ID
		///</summary>
		public long? SupMatApplyId { get; set; }

		///<summary>
		///物资ID
		///</summary>
		public long? SupMatManagementId { get; set; }

        ///<summary>
		///物资名称
		///</summary>
		public string SupMatManagement { get; set; }

        ///<summary>
        ///单价
        ///</summary>
        public decimal? UnitPrice { get; set; }

		///<summary>
		///品名
		///</summary>
		public string ProductName { get; set; }

		///<summary>
		///规格
		///</summary>
		public string Specification { get; set; }

		///<summary>
		///数量
		///</summary>
		public decimal? Number { get; set; }

		///<summary>
		///金额
		///</summary>
		public decimal? Money { get; set; }

        ///<summary>
        ///供应商名称
        ///</summary>
        public string SupplierName { get; set; }

        ///<summary>
        ///状态，预留
        ///</summary>
        public int? State { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }

        /// <summary>
        /// 验收数量
        /// </summary>
        public int? UseSum { get; set; }
        /// <summary>
        /// 待验收数量
        /// </summary>
        public int? StayUseSum { get; set; }
        /// <summary>
        /// 验收状态
        /// </summary>
        public bool UseType { get; set; }

    }
}

