//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2020-02-21 15:11:16
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_ProjectCountWeekly:
	///</summary>
	 public  class  Epm_ProjectCountWeekly:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public long? CompanyId { get; set; }

		///<summary>
		///
		///</summary>
		public int? BeingBuiltCount { get; set; }

		///<summary>
		///
		///</summary>
		public string CompanyName { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? StartDate { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? EndDate { get; set; }

		///<summary>
		///
		///</summary>
		public int? ProjectPolitCount { get; set; }

		///<summary>
		///
		///</summary>
		public int? CapitalTransferCount { get; set; }

		///<summary>
		///
		///</summary>
		public int? TenderingApplyCount { get; set; }

		///<summary>
		///
		///</summary>
		public int? CompletionAcceptanceCount { get; set; }

		///<summary>
		///
		///</summary>
		public int? DesignSchemeCount { get; set; }

		///<summary>
		///
		///</summary>
		public int? sort { get; set; }

		///<summary>
		///
		///</summary>
		public int? ConstructionCount { get; set; }

		///<summary>
		///
		///</summary>
		public int? AcceptanceCount { get; set; }

		///<summary>
		///
		///</summary>
		public int? FinshCount { get; set; }

		///<summary>
		///
		///</summary>
		public int? StartCount { get; set; }

		///<summary>
		///
		///</summary>
		public int? NoStartCount { get; set; }

		///<summary>
		///
		///</summary>
		public int? Count { get; set; }

		///<summary>
		///
		///</summary>
		public int? Type { get; set; }

	}
}

