//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-02-14 14:04:36
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_InspectItem:
	///</summary>
	 public  class  Epm_InspectItem:BaseBusiness
	{ 
		///<summary>
		/// 检查单Id
		///</summary>
		public long? InspectId { get; set; }

		///<summary>
		/// 检查配置表Id
		///</summary>
		public long? CheckId { get; set; }

		///<summary>
		/// 
		///</summary>
		public string CheckName { get; set; }

		///<summary>
		///
		///</summary>
		public long? CheckParentId { get; set; }

		///<summary>
		///
		///</summary>
		public string CheckParentName { get; set; }

		///<summary>
		/// 层级
		///</summary>
		public int? Level { get; set; }

		///<summary>
		/// 是否选中
		///</summary>
		public bool? Choice { get; set; }

		///<summary>
		/// 备注
		///</summary>
		public string Remark { get; set; }

        ///<summary>
        /// 整改负责人，如：TJXCFZR
        ///</summary>
        public string RectifRecordPersonKey { get; set; }

        ///<summary>
        /// 整改负责人，如：土建现场负责人
        ///</summary>
        public string RectifRecordPerson { get; set; }

		///<summary>
		/// 满分
		///</summary>
		public int? ScoreMax { get; set; }

		///<summary>
		/// 得分
		///</summary>
		public decimal? Score { get; set; }

		///<summary>
		/// 状态 待整改、已整改、整改通过、整改不通过
		///</summary>
		public int? State { get; set; }

	}
}

