//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:52
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_SupervisorLogWork:监理日志关联作业实景表
    ///</summary>
    public class Epm_SupervisorLogWork : BaseBusiness
    {
        ///<summary>
        ///项目表Id
        ///</summary>
        public long? LogId { get; set; }
        /// <summary>
        /// 危险作业Id
        /// </summary>
        public long? WorkId { get; set; }
        /// <summary>
        /// 作业实景表Id
        /// </summary>
        public long? WorkUploadId { get; set; }
        ///<summary>
        ///状态
        ///</summary>
        public int? State { get; set; }
        ///<summary>
        ///备注
        ///</summary>
        public string Remark { get; set; }
    }
}