//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-02-14 14:04:37
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_RectificationRecord:
    ///</summary>
    public class Epm_RectificationRecord : BaseBusiness
    {
        ///<summary>
        /// 整改单Id
        ///</summary>
        public long? RectficationId { get; set; }
        ///<summary>
        /// 整改项表Id
        ///</summary>
        public long? RectficationItemId { get; set; }

        ///<summary>
        /// 整改说明
        ///</summary>
        public string RectficationDescption { get; set; }

        ///<summary>
        /// 状态 待整改、已整改、整改通过、整改不通过
        ///</summary>
        public int? State { get; set; }

    }
}

