//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_Material:工器具验收
    ///</summary>
    public class  Epm_Material:BaseBusiness
	{ 
		///<summary>
		///项目表Id
		///</summary>
		public long? ProjectId { get; set; }

		///<summary>
		///项目名称
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///业主单位Id
		///</summary>
		public long? CompanyId { get; set; }

		///<summary>
		///业主单位Name
		///</summary>
		public string CompanyName { get; set; }

		///<summary>
		///验收地址
		///</summary>
		public string CheckAddress { get; set; }

		///<summary>
		///材料供应商Id
		///</summary>
		public long? SupplierId { get; set; }

		///<summary>
		///材料供应商Name
		///</summary>
		public string SupplierName { get; set; }

		///<summary>
		///验收内容
		///</summary>
		public string CheckContent { get; set; }

		///<summary>
		///是否合格【1合格，2不合格】枚举
		///</summary>
		public bool? IsQualified { get; set; }

		///<summary>
		///验收人Id
		///</summary>
		public long? CheckUserId { get; set; }

		///<summary>
		///验收人Name
		///</summary>
		public string CheckUserName { get; set; }

		///<summary>
		///验收单位Id
		///</summary>
		public long? CheckCompanyId { get; set; }

		///<summary>
		///验收单位Name
		///</summary>
		public string CheckCompanyName { get; set; }

		///<summary>
		///验收时间
		///</summary>
		public DateTime? CheckTime { get; set; }

		///<summary>
		///状态[10待处理,20审核通过,30已驳回,40已废弃]枚举
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

	}
}

