//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_MaterialDetails:工器具验收明细表
    ///</summary>
    public class  Epm_MaterialDetails:BaseBusiness
	{ 
		///<summary>
		///材料设备验收表Id
		///</summary>
		public long? MaterialCheckId { get; set; }

		///<summary>
		///材料分类Key
		///</summary>
		public string MaterialTypeNo { get; set; }

		///<summary>
		///材料分类Value
		///</summary>
		public string MaterialTypeName { get; set; }

		///<summary>
		///名称
		///</summary>
		public string Name { get; set; }

		///<summary>
		///型号
		///</summary>
		public string Model { get; set; }

		///<summary>
		///数量
		///</summary>
		public decimal? Qty { get; set; }

        /// <summary>
        /// 单位
        /// </summary>
        public string Unit { get; set; }

        ///<summary>
        ///顺序
        ///</summary>
        public int? Sort { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

	}
}

