//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:52
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_TrainDetails:培训明细表
	///</summary>
	 public  class  Epm_TrainDetails:BaseBusiness
	{ 
		///<summary>
		///培训表Id
		///</summary>
		public long? TrainId { get; set; }

		///<summary>
		///培训项名称
		///</summary>
		public string Name { get; set; }

		///<summary>
		///父级Id
		///</summary>
		public long? ParentId { get; set; }

		///<summary>
		///顺序
		///</summary>
		public int? Sort { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

	}
}

