//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-02-14 14:04:36
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_Inspect:
    ///</summary>
    public class Epm_Inspect : BaseBusiness
    {
        ///<summary>
        /// 项目Id
        ///</summary>
        public long? ProjectId { get; set; }

        ///<summary>
        /// 项目
        ///</summary>
        public string ProjectName { get; set; }

        ///<summary>
        /// 检查单名
        ///</summary>
        public string InspectName { get; set; }

        ///<summary>
        /// 检查地址
        ///</summary>
        public string InspectAddress { get; set; }

        ///<summary>
        /// 检查日期
        ///</summary>
        public DateTime? InspectDate { get; set; }

        ///<summary>
        /// 检查人Id
        ///</summary>
        public long? InspectUserId { get; set; }

        ///<summary>
        /// 检查人
        ///</summary>
        public string InspectUserName { get; set; }

        /// <summary>
        /// 1 草稿
        /// </summary>
        public bool? IsDraft { get; set; }
    }
}

