//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-10-14 17:32:46
// </auto-generated>
//------------------------------------------------------------------------------
using hc.epm.DataModel.BaseCore;
using System;
using System.Collections.Generic;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_TzResearchOfEngineering:现场工程方面调研
    ///</summary>
    public class Epm_TzResearchOfEngineering : BaseBusiness
    {
        ///<summary>
        ///所属项目ID
        ///</summary>
        public long ProjectId { get; set; }

        ///<summary>
        ///调研开始日期
        ///</summary>
        public DateTime? ResearchStartDate { get; set; }

        ///<summary>
        ///调研截止日期
        ///</summary>
        public DateTime? ResearchEndDate { get; set; }

        ///<summary>
        ///调研人ID
        ///</summary>
        public long? ResearchUserId { get; set; }

        ///<summary>
        ///调研人姓名
        ///</summary>
        public string ReaearchUserName { get; set; }

        ///<summary>
        ///调研人协同OA编码
        ///</summary>
        public string ReaearchUserXt { get; set; }

        ///<summary>
        ///职务编码(字典)
        ///</summary>
        public string JobCode { get; set; }

        ///<summary>
        ///职务名称
        ///</summary>
        public string JobName { get; set; }

        ///<summary>
        ///形象工程符合行业规划 0 符合，1基本符合，2 不符合
        ///</summary>
        public string IndustryPlanning { get; set; }

        ///<summary>
        ///罩棚面积(平米)
        ///</summary>
        public decimal? Shelter { get; set; }

        ///<summary>
        ///加油枪(台)
        ///</summary>
        public int? MachineOfOilStage { get; set; }

        ///<summary>
        ///加油枪(个)
        ///</summary>
        public int? MachineOfOil { get; set; }

        ///<summary>
        ///加气枪(台)
        ///</summary>
        public int? MachineOfGasStage { get; set; }

        ///<summary>
        ///加气枪(个)
        ///</summary>
        public int? MachineOfGas { get; set; }

        ///<summary>
        ///
        ///</summary>
        public decimal? OilTank { get; set; }

        ///<summary>
        ///站房(平米)
        ///</summary>
        public decimal? StationRoon { get; set; }

        ///<summary>
        ///储气井(方)
        ///</summary>
        public decimal? GasWells { get; set; }

        ///<summary>
        ///信息化系统
        ///</summary>
        public string HasInformationSystem { get; set; }

        ///<summary>
        ///改造必要性
        ///</summary>
        public string ReformCode { get; set; }

        ///<summary>
        ///改造必要性
        ///</summary>
        public string ReformName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public int State { get; set; }

    }
}

