//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-08-14 09:32:31
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_SupervisorLogCompany:
    ///</summary>
    public class Epm_SupervisorLogCompany : BaseBusiness
    {
        public Epm_SupervisorLogCompany()
        {
            ProjectlLogName = new List<Epm_ProjectlLogName>();
            AttendanceList = new List<Epm_AttendanceList>();
        }
        ///<summary>
        ///
        ///</summary>
        public long LogId { get; set; }
        ///<summary>
        ///
        ///</summary>
        public long ProjectId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public long CompanyId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string CompanyName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ManagerName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public int PeopleNumber { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string WorkPeopleType { get; set; }

        public string SafetyName { get; set; }

        public string Permit { get; set; }

        public string BePresent { get; set; }
        
        [NotMapped]
        public List<Epm_ProjectlLogName> ProjectlLogName { get; set; }

        [NotMapped]
        public List<Epm_AttendanceList> AttendanceList { get; set; }

    }
}

