//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-08-14 08:57:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///EPM_ProjectNature:
    ///</summary>
    public class Epm_ProjectNature : BaseBusiness
    {
        ///<summary>
        ///名称
        ///</summary>
        public string NATURE_MC { get; set; }

        ///<summary>
        ///编码
        ///</summary>
        public string NATURE_BH { get; set; }

        ///<summary>
        ///备注
        ///</summary>
        public string NATURE_BZ { get; set; }

        ///<summary>
        ///使用状态
        ///</summary>
        public string F_SYZT { get; set; }

        ///<summary>
        ///创建时间
        ///</summary>
        public string F_CRDATE { get; set; }

        ///<summary>
        ///修改时间
        ///</summary>
        public string F_CHDATE { get; set; }

    }
}

