//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-11-15 08:53:20
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///EPM_CustomProperty:
    ///</summary>
    public class EPM_CustomProperty : BaseBusiness
    {
        ///<summary>
        ///
        ///</summary>
        public long? ProjectId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public long? BimId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string externalId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string PropertyType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string PropertyKey { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string PropertyValue { get; set; }

    }
}

