//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_AdTarget:广告位表
	///</summary>
	 public  class  Epm_AdTarget:BaseBusiness
	{ 
		///<summary>
		///广告编码
		///</summary>
		public string TargetNum { get; set; }

		///<summary>
		///广告位名称
		///</summary>
		public string Name { get; set; }

		///<summary>
		///高度
		///</summary>
		public int? Hight { get; set; }

		///<summary>
		///长度
		///</summary>
		public int? Lenght { get; set; }

		///<summary>
		///广告位价格
		///</summary>
		public decimal? Price { get; set; }

		///<summary>
		///描述
		///</summary>
		public string Description { get; set; }

		///<summary>
		///显示数量
		///</summary>
		public int? ShowCount { get; set; }

		///<summary>
		///状态（1禁用 0启用）
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }
        
	}
}

