//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:52
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_QuestionUser:问题协同人员
	///</summary>
	 public  class  Epm_QuestionUser:BaseBusiness
	{ 
		///<summary>
		///问题表Id
		///</summary>
		public long? QuestionId { get; set; }

        ///<summary>
        ///协同单位Id
        ///</summary>
        public long? CompanyId { get; set; }

        ///<summary>
        ///协同单位Name
        ///</summary>
        public string CompanyName { get; set; }

        ///<summary>
        ///协同人员Id
        ///</summary>
        public long? UserId { get; set; }

		///<summary>
		///协同人员Name
		///</summary>
		public string UserName { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

        /// <summary>
        /// 公司类型
        /// </summary>
        public string CompanyType { get; set; }
    }
}

