//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-09-02 13:52:36
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_TzPeopleChgApply:
    ///</summary>
    public class  Epm_TzPeopleChgApply:BaseBusiness
	{
        public Epm_TzPeopleChgApply()
        {
            TzAttachs = new List<Epm_TzAttachs>();
            TzPeopleChgApplyItem = new List<Epm_TzPeopleChgApplyItem>();
        }

        ///<summary>
        ///标题
        ///</summary>
        public string Title { get; set; }

		///<summary>
		///所属项目
		///</summary>
		public long? ProjectId { get; set; }

		///<summary>
		///申请人
		///</summary>
		public string Applicant { get; set; }

		///<summary>
		///申请人id
		///</summary>
		public long? ApplicantId { get; set; }

		///<summary>
		///所属单位
		///</summary>
		public string CompanyName { get; set; }

		///<summary>
		///所属单位ID
		///</summary>
		public long? CompanyId { get; set; }

		///<summary>
		///所属部门
		///</summary>
		public string Department { get; set; }

		///<summary>
		///所属部门ID
		///</summary>
		public long? DepartmentId { get; set; }

		///<summary>
		///申请日期
		///</summary>
		public DateTime? ApplyDate { get; set; }

		///<summary>
		///项目名称
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///建设地址
		///</summary>
		public string ConstructionAddress { get; set; }

		///<summary>
		///施工（监理）单位
		///</summary>
		public string WorkUnit { get; set; }

		///<summary>
		///施工(监理)单位ID
		///</summary>
		public long? WorkUnitId { get; set; }

        /// <summary>
        /// 负责人
        /// </summary>
        public string Leader { get; set; }
        
        ///<summary>
        ///施工(监理)负责人
        ///</summary>
        public string WorkLeader { get; set; }

		///<summary>
		///施工(监理)负责人 ID
		///</summary>
		public long? WorkLeaderId { get; set; }

		///<summary>
		///当前状态
		///</summary>
		public string StateType { get; set; }

		///<summary>
		///状态编码
		///</summary>
		public string StateName { get; set; }

		///<summary>
		///部门负责人id
		///</summary>
		public long? DepLeaderId { get; set; }

		///<summary>
		///部门负责人
		///</summary>
		public string DepLeaderName { get; set; }

		///<summary>
		///分管领导id
		///</summary>
		public long? LeaderId { get; set; }

		///<summary>
		///分管领导
		///</summary>
		public string LeaderName { get; set; }

		///<summary>
		///签字意见
		///</summary>
		public string SignIdea { get; set; }

		///<summary>
		///流程ID
		///</summary>
		public string WorkFlowId { get; set; }

        /// <summary>
        /// 当前审批人
        /// </summary>
        public string ApprovalName { get; set; }

        /// <summary>
        /// 当前审批人Id
        /// </summary>
        public string ApprovalNameId { get; set; }

        public int State { get; set; }

        [NotMapped]
        public List<Epm_TzAttachs> TzAttachs { get; set; }

        [NotMapped]
        public List<Epm_TzPeopleChgApplyItem> TzPeopleChgApplyItem { get; set; }
    }
}

