//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-09-12 10:53:38
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_TzGcGoodsOrdersItem:
	///</summary>
	 public  class  Epm_TzGcGoodsOrdersItem:BaseBusiness
	{ 
		///<summary>
		///所属申请 ID
		///</summary>
		public long? ChangeApplyId { get; set; }

		///<summary>
		///序号
		///</summary>
		public int? Sort { get; set; }

		///<summary>
		///单位名称
		///</summary>
		public string CompanyName { get; set; }

		///<summary>
		///单位id
		///</summary>
		public long? CompanyId { get; set; }

		///<summary>
		///站名
		///</summary>
		public string StationName { get; set; }

		///<summary>
		///品名
		///</summary>
		public string ProductName { get; set; }

		///<summary>
		///规格
		///</summary>
		public string Specifications { get; set; }

		///<summary>
		///数量
		///</summary>
		public decimal? Number { get; set; }

		///<summary>
		///单价
		///</summary>
		public decimal? UnitPrice { get; set; }

		///<summary>
		///金额
		///</summary>
		public decimal? Amount { get; set; }

		///<summary>
		///到货地址
		///</summary>
		public string Address { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Note { get; set; }

	}
}

