//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-11-04 18:14:39
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_TzTenderingApply:招标申请
    ///</summary>
    public class  Epm_TzTenderingApply:BaseBusiness
	{ 
		///<summary>
		///所属项目ID
		///</summary>
		public string ProjectId { get; set; }
        
		///<summary>
		///项目名称
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///项目批复号
		///</summary>
		public string ApprovalNo { get; set; }
        
		///<summary>
		///承办部门ID
		///</summary>
		public long? UndertakeDepartmentId { get; set; }

		///<summary>
		///承办部门协同编码
		///</summary>
		public string UndertakeDepartmentCodeXt { get; set; }

		///<summary>
		///承办部门
		///</summary>
		public string UndertakeDepartment { get; set; }

		///<summary>
		///联系人ID（预留）
		///</summary>
		public long? UndertakeContactsId { get; set; }

		///<summary>
		///承办人协同编码
		///</summary>
		public string UndertakeContactsCodeXt { get; set; }

		///<summary>
		///承办联系人
		///</summary>
		public string UndertakeContacts { get; set; }

		///<summary>
		///承办联系电话
		///</summary>
		public string UndertakeTel { get; set; }

		///<summary>
		///批复文件或纪要
		///</summary>
		public string Minutes { get; set; }

		///<summary>
		///招标方式编码
		///</summary>
		public string BidType { get; set; }

		///<summary>
		///招标方式名称
		///</summary>
		public string BidName { get; set; }

		///<summary>
		///资金预算及依据
		///</summary>
		public string CapitalBudget { get; set; }

		///<summary>
		///项目概述
		///</summary>
		public string ProjectSummary { get; set; }

		///<summary>
		///邀请谈判理由
		///</summary>
		public string InvitationNegotiate { get; set; }

		///<summary>
		///潜在谈判人
		///</summary>
		public string InvitationNegotiator { get; set; }

		///<summary>
		///状态：暂存、待审核、审核通过、审核不通过、作废
		///</summary>
		public int? State { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }

        /// <summary>
        /// 招标类型
        /// </summary>
        public string TenderingType { get; set; }

        /// <summary>
        /// 招标类型名称
        /// </summary>
        public string TenderingTypeName { get; set; }

        /// <summary>
        /// 招标名称
        /// </summary>
        public string TenderingName { get; set; }

        [NotMapped]
        public List<Epm_TzAttachs> TzAttachs { get; set; }
        /// <summary>
        /// 流程申请 ID
        /// </summary>
        public string WorkFlowId { get; set; }
        ///<summary>
        ///当前状态
        ///</summary>
        public string StateType { get; set; }

        ///<summary>
        ///状态编码
        ///</summary>
        public string StateName { get; set; }

        /// <summary>
        /// 当前审批人
        /// </summary>
        public string ApprovalName { get; set; }

        /// <summary>
        /// 当前审批人Id
        /// </summary>
        public long? ApprovalNameId { get; set; }

        /// <summary>
        /// 开工报告审批时间（本次流程全部审批完成时间（年月日），若还未完成审批，不显示）
        /// </summary>
        public DateTime? WorkStartApprovalTime { get; set; }
    }
}

