//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-08-21 14:35:33
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_TzAttachs: 投资相关业务附件表
	///</summary>
	 public  class  Epm_TzAttachs:BaseBusiness
	{ 
		///<summary>
		/// 业务数据ID
		///</summary>
		public long? DataId { get; set; }

		///<summary>
		/// 业务所属表明
		///</summary>
		public string TableName { get; set; }

		///<summary>
		/// 附件名称
		///</summary>
		public string Name { get; set; }

		///<summary>
		/// 存储路径
		///</summary>
		public string FilePath { get; set; }

		///<summary>
		/// 附件类型编码
		///</summary>
		public string TypeNo { get; set; }

		///<summary>
		/// 附件类型名称
		///</summary>
		public string TypeName { get; set; }

		///<summary>
		/// 附件大小
		///</summary>
		public string Size { get; set; }

		///<summary>
		/// 排序
		///</summary>
		public int? Sort { get; set; }

		///<summary>
		/// 状态
		///</summary>
		public int? State { get; set; }

		///<summary>
		/// 备注
		///</summary>
		public string Remark { get; set; }
        ///<summary>
		/// 项目ID
		///</summary>
		public long? ProjectId { get; set; }

        ///<summary>
        ///附件属性
        ///</summary>
        public string Nature { get; set; }

        ///<summary>
        ///附件属性名称
        ///</summary>
        public string NatureName { get; set; }
        /// <summary>
        /// 附件归属（0：默认值，1：选中投资回写，2：不选中投资回写）
        /// </summary>
        public int Uploadtype { get; set; }

        [NotMapped]
        public int FilesSize { get; set; }

    }
}

