//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-08-20 16:39:48
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///站库改造:
	///</summary>
	 public  class  Epm_ReformRecord:BaseBusiness
	{

        public Epm_ReformRecord()
        {
            TzAttachs = new List<Epm_TzAttachs>();
        }


        [NotMapped]
        public List<Epm_TzAttachs> TzAttachs { get; set; }


        ///<summary>
        ///项目名称
        ///</summary>
        public string ProjectName { get; set; }

        ///<summary>
        ///项目ID
        ///</summary>
        public long? ProjectId { get; set; }

        ///<summary>
        ///项目编码_投资
        ///</summary>
        public string ProjectCodeInvest { get; set; }

        ///<summary>
        ///项目编码_一体
        ///</summary>
        public string ProjectCodeWhole { get; set; }

        ///<summary>
        ///项目编码_工程
        ///</summary>
        public string ProjectCodeProject { get; set; }

        ///<summary>
        ///改造类型
        ///</summary>
        public string RemarkType { get; set; }
        ///<summary>
        ///
        ///改造类型名称
        ///</summary>
        public string RemarkTypeName { get; set; }

        
        ///<summary>
        ///站库名称
        ///</summary>
        public string StationName { get; set; }

        ///<summary>
        ///站库ID
        ///</summary>
        public long? StationId { get; set; }

        ///<summary>
        ///站库编码_投资
        ///</summary>
        public string StationCodeInvest { get; set; }

        ///<summary>
        ///站库编码_一体
        ///</summary>
        public string StationCodeWhole { get; set; }

        ///<summary>
        ///站库编码_工程
        ///</summary>
        public string StationCodeProject { get; set; }

        ///<summary>
        ///地市公司名称
        ///</summary>
        public string CompanyName { get; set; }

        ///<summary>
        ///地市公司ID
        ///</summary>
        public long? CompanyId { get; set; }

        ///<summary>
        ///限制类别-限上/限下
        ///</summary>
        public string LimitType { get; set; }

        ///<summary>
        ///资金来源
        ///</summary>
        public string SourceFund { get; set; }

        ///<summary>
        ///投资金额
        ///</summary>
        public decimal? Investment { get; set; }

        ///<summary>
        ///立项批复文号
        ///</summary>
        public string ItemNumber { get; set; }

        ///<summary>
        ///立项批复时间
        ///</summary>
        public DateTime? ItemTime { get; set; }

        ///<summary>
        ///立项批复单位
        ///</summary>
        public string ItemUnit { get; set; }

        ///<summary>
        ///立项批复金额
        ///</summary>
        public decimal? ItemMoney { get; set; }

        ///<summary>
        ///初设批复文号
        ///</summary>
        public string InitialNumber { get; set; }

        ///<summary>
        ///初设批复金额
        ///</summary>
        public decimal? InitialMoney { get; set; }

        ///<summary>
        ///改造起始时间
        ///</summary>
        public DateTime? RemarkStartTime { get; set; }

        ///<summary>
        ///改造终止时间
        ///</summary>
        public DateTime? RemarkEndTime { get; set; }

        ///<summary>
        ///改造金额
        ///</summary>
        public decimal? RemarkMoney { get; set; }

        ///<summary>
        ///决策人
        ///</summary>
        public string DecisionMaker { get; set; }

        ///<summary>
        ///负责人
        ///</summary>
        public string LeaderPerson { get; set; }

        ///<summary>
        ///运营人
        ///</summary>
        public string Operator { get; set; }

        ///<summary>
        ///加管编码
        ///</summary>
        public string PipetteCoding { get; set; }

        ///<summary>
        ///原成品油销量
        ///</summary>
        public decimal? InitialSalesOfRefinedOil { get; set; }

        ///<summary>
        ///改造后成品油销量
        ///</summary>
        public decimal? RemarkSalesOfRefinedOil { get; set; }

        ///<summary>
        ///原气销量
        ///</summary>
        public decimal? InitialSalesOfGas { get; set; }

        ///<summary>
        ///改造后气销量
        ///</summary>
        public decimal? RemarkSalesOfGas { get; set; }

        ///<summary>
        ///内部收益率
        ///</summary>
        public decimal? IRR { get; set; }

        ///<summary>
        ///工程内容
        ///</summary>
        public string ProjectContent { get; set; }

        ///<summary>
        ///备注
        ///</summary>
        public string Remark { get; set; }

        ///<summary>
        ///附件类型
        ///</summary>
        public string AnnexType { get; set; }

        ///<summary>
        ///附件地址
        ///</summary>
        public string AnnexAddress { get; set; }

        ///<summary>
        ///0：待审批 1：审批通过 2：审批不通过
        ///</summary>
        public int? State { get; set; }

        ///<summary>
        ///审批人
        ///</summary>
        public string Approver { get; set; }

        ///<summary>
        ///
        ///</summary>
        public long? ApproverId { get; set; }

        ///<summary>
        ///审批时间
        ///</summary>
        public DateTime? ApproveTime { get; set; }

        ///<summary>
        ///审批结果 0：审批通过 1：审批不通过
        ///</summary>
        public int? ApproveResult { get; set; }

        ///<summary>
        ///审批备注
        ///</summary>
        public string ApproveRemark { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string AreaCompanyName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string AreaCompanyCode { get; set; }

        ///<summary>
        ///费用金额
        ///</summary>
        public decimal? CostAmount { get; set; }

        ///<summary>
        ///决策人ID
        ///</summary>
        public long? DecisionMakerId { get; set; }
        ///<summary>
        ///负责人ID
        ///</summary>
        public long? LeaderPersonId { get; set; }
        ///<summary>
        ///运营人ID
        ///</summary>
        public long? OperatorId { get; set; }

        ///<summary>
        ///当前状态
        ///</summary>
        public string StateType { get; set; }

        ///<summary>
        ///状态编码
        ///</summary>
        public string StateName { get; set; }

        /// <summary>
        /// 当前审批人
        /// </summary>
        public string ApprovalName { get; set; }

        /// <summary>
        /// 当前审批人Id
        /// </summary>
        public long? ApprovalNameId { get; set; }

        /// <summary>
        /// 审批时间（本次流程全部审批完成时间（年月日），若还未完成审批，不显示）
        /// </summary>
        public DateTime? WorkStartApprovalTime { get; set; }
        // <summary>
        /// 流程申请 ID
        /// </summary>
        public string WorkFlowId { get; set; }
    }
}

