//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-08-23 10:31:54
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_TzLandTalk: 土地协议出让谈判信息
    ///</summary>
    public class  Epm_TzLandTalk:BaseBusiness
	{

        public Epm_TzLandTalk()
        {
            TzAttachs = new List<Epm_TzAttachs>();
        }
        ///<summary>
        ///
        ///</summary>
        public long? ProjectId { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectCodeInvest { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectCodeWhole { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectCodeProject { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? TalkTime { get; set; }

		///<summary>
		///
		///</summary>
		public string TalkAdress { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? FirstPay { get; set; }

		///<summary>
		///
		///</summary>
		public string FirstPayTime { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? Fees { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? FeesTime { get; set; }

		///<summary>
		///
		///</summary>
		public string TalkResultType { get; set; }

		///<summary>
		///
		///</summary>
		public string TalkResultName { get; set; }

		///<summary>
		///
		///</summary>
		public string OperationTypeType { get; set; }

		///<summary>
		///
		///</summary>
		public string OperationTypeName { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///
		///</summary>
		public string StateType { get; set; }

		///<summary>
		///
		///</summary>
		public string StateName { get; set; }

		///<summary>
		///
		///</summary>
		public string Operator { get; set; }

		///<summary>
		///
		///</summary>
		public string OperatorID { get; set; }

		///<summary>
		///
		///</summary>
		public string OperatorInvest { get; set; }

		///<summary>
		///
		///</summary>
		public string OperatorWhole { get; set; }

		///<summary>
		///
		///</summary>
		public string OperatorProject { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? OperatorTime { get; set; }

		///<summary>
		///
		///</summary>
		public int? State { get; set; }

        [NotMapped]
        public List<Epm_TzAttachs> TzAttachs { get; set; }
    }
}

