//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:52
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_Project:项目表
    ///</summary>
    public class Epm_Project : BaseBusiness
    {
        ///<summary>
        ///编码
        ///</summary>
        public string Code { get; set; }

        ///<summary>
        ///预留与本省系统对接
        ///</summary>
        public string Code1 { get; set; }

        ///<summary>
        ///预留与本省系统对接
        ///</summary>
        public string Code2 { get; set; }

        ///<summary>
        ///预留与本省系统对接
        ///</summary>
        public string Code3 { get; set; }

        ///<summary>
        ///预留与本省系统对接
        ///</summary>
        public string Code4 { get; set; }

        ///<summary>
        ///预留与本省系统对接
        ///</summary>
        public string Code5 { get; set; }

        ///<summary>
        ///项目名称
        ///</summary>
        public string Name { get; set; }

        ///<summary>
        ///项目主体No
        ///</summary>
        public string SubjectNo { get; set; }

        ///<summary>
        ///项目主体Name
        ///</summary>
        public string SubjectName { get; set; }

        ///<summary>
        ///项目主体Id
        ///</summary>
        public long? ProjectSubjectId { get; set; }

        ///<summary>
        ///项目主体ShortName
        ///</summary>
        public string ProjectSubjectShortName { get; set; }

        ///<summary>
        ///项目主体Name
        ///</summary>
        public string ProjectSubjectName { get; set; }

        ///<summary>
        ///所属分公司Id
        ///</summary>
        public long? CompanyId { get; set; }

        ///<summary>
        ///所属分公司
        ///</summary>
        public string CompanyName { get; set; }

        ///<summary>
        ///建筑类型Key
        ///</summary>
        public string BuildNo { get; set; }

        ///<summary>
        ///建筑类型Value
        ///</summary>
        public string BuildName { get; set; }

        ///<summary>
        ///省
        ///</summary>
        public string Province { get; set; }

        ///<summary>
        ///市
        ///</summary>
        public string City { get; set; }

        ///<summary>
        ///区
        ///</summary>
        public string Area { get; set; }

        ///<summary>
        ///地址
        ///</summary>
        public string Address { get; set; }

        ///<summary>
        ///项目开始时间
        ///</summary>
        public DateTime? StartDate { get; set; }

        ///<summary>
        ///项目结束时间
        ///</summary>
        public DateTime? EndDate { get; set; }

        ///<summary>
        ///项目类型No
        ///</summary>
        public string ProjectTypeNo { get; set; }

        ///<summary>
        ///项目类型Name
        ///</summary>
        public string ProjectTypeName { get; set; }

        ///<summary>
        ///项目金额，单位万元
        ///</summary>
        public decimal? Amount { get; set; }

        ///<summary>
        ///简介
        ///</summary>
        public string Description { get; set; }

        ///<summary>
        ///分公司项目负责人Id
        ///</summary>
        public long? ContactUserId { get; set; }

        ///<summary>
        ///分公司项目负责人Name
        ///</summary>
        public string ContactUserName { get; set; }

        ///<summary>
        ///分公司项目负责人电话
        ///</summary>
        public string ContactPhone { get; set; }

        ///<summary>
        ///状态
        ///</summary>
        public int? State { get; set; }

        ///<summary>
        ///备注
        ///</summary>
        public string Remark { get; set; }

        ///<summary>
        ///创建单位Id
        ///</summary>
        public long? CrtCompanyId { get; set; }

        ///<summary>
        ///创建单位Name
        ///</summary>
        public string CrtCompanyName { get; set; }

        ///// <summary>
        ///// 简称
        ///// </summary>
        //public string ProjectAbbreviation { get; set; }

        /// <summary>
        /// 是否首页显示
        /// </summary>
        public bool IsHomePageShow { get; set; }

        /// <summary>
        /// 外部系统唯一标识
        /// </summary>
        public string ObjeId { get; set; }

        /// <summary>
        /// 项目所属部门 ID
        /// </summary>
        public long? OrgId { get; set; }

        /// <summary>
        /// 项目所属部门名称
        /// </summary>
        public string OrgName { get; set; }

        /// <summary>
        /// 项目性质编码
        /// </summary>
        public string ProjectNature { get; set; }

        /// <summary>
        /// 项目性质名称
        /// </summary>
        public string ProjectNatureName { get; set; }

        /// <summary>
        /// 费用来源
        /// </summary>
        public string CostCourse { get; set; }

        /// <summary>
        /// 基础平台项目状态
        /// </summary>
        public string ObjState { get; set; }

        /// <summary>
        /// 加油站编码
        /// </summary>
        public string ProjectSubjectCode { get; set; }

        /// <summary>
        /// 项目经理
        /// </summary>
        public long? PMId { get; set; }
        /// <summary>
        /// 项目经理
        /// </summary>
        public string PMName { get; set; }
        /// <summary>
        /// 项目经理电话
        /// </summary>
        public string PMPhone { get; set; }

        /// <summary>
        /// 批复文号
        /// </summary>
        public string ReplyNumber { get; set; }
        /// <summary>
        /// 工程内容
        /// </summary>
        public string ProjectContent { get; set; }

        /// <summary>
        /// 方案类型
        /// </summary>
        public string BluePrintKey { get; set; }
        /// <summary>
        /// 方案类型
        /// </summary>
        public string BluePrintValue { get; set; }
        /// <summary>
        /// 外部手续
        /// </summary>
        public bool? IsCrossings { get; set; }

        /// <summary>
        /// 实际停业时间
        /// </summary>
        public DateTime? ShutdownTime { get; set; }
        /// <summary>
        /// 计划开工时间
        /// </summary>
        public DateTime? PlanWorkStartTime { get; set; }
        /// <summary>
        /// 计划完工时间
        /// </summary>
        public DateTime? PlanWorkEndTime { get; set; }
        /// <summary>
        /// 工期
        /// </summary>
        public int? Limit { get; set; }
        /// <summary>
        /// 计划开业时间
        /// </summary>
        public DateTime? PlanOpeningTime { get; set; }
        /// <summary>
        /// 计划停业时长
        /// </summary>
        public int? PlanShutdowLimit { get; set; }

        /// <summary>
        /// 计划包装开工
        /// </summary>
        public DateTime? PlanPackStartTime { get; set; }
        /// <summary>
        /// 计划包装完工
        /// </summary>
        public DateTime? PlanPackEndTime { get; set; }
        /// <summary>
        /// 计划加固开工
        /// </summary>
        public DateTime? PlanReinforceStartTime { get; set; }
        /// <summary>
        /// 计划加固完工
        /// </summary>
        public DateTime? PlanReinforceEndTime { get; set; }

        /// <summary>
        /// 剩余金额
        /// </summary>
        public decimal? BalanceAmount { get; set; }
        /// <summary>
        /// 甲供设备金额
        /// </summary>
        public decimal? AProvideAmount { get; set; }
        /// <summary>
        /// 里程碑类型
        /// </summary>
        public string MilepostType { get; set; }
        /// <summary>
        /// 里程碑名称
        /// </summary>
        public string MilepostName { get; set; }

        /// <summary>
        /// 汽柴比
        /// </summary>
        public string GasolineDieselRatio { get; set; }

        /// <summary>
        /// 立项批复时间
        /// </summary>
        public DateTime? ReplyDate { get; set; }

        /// <summary>
        /// 站经理
        /// </summary>
        public long? StationManagerId { get; set; }
        /// <summary>
        /// 站经理
        /// </summary>
        public string StationManagerName { get; set; }

        /// <summary>
        /// 已完成施工设计 0未完成,1完成
        /// </summary>
        public int FinshDesign { get; set; }

        /// <summary>
        /// 省公司验收 0未完成,1完成
        /// </summary>
        public int ProCompanyAcceptance { get; set; }

        /// <summary>
        /// 投资管理项目Id
        /// </summary>
        public long TzProjectId { get; set; }
    }
}