//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-09-12 10:53:38
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_TzGcGoodsOrdersApply:
    ///</summary>
    public class Epm_TzGcGoodsOrdersApply : BaseBusiness
    {
        public Epm_TzGcGoodsOrdersApply()
        {
            TzGcGoodsOrdersItem = new List<Epm_TzGcGoodsOrdersItem>();
        }
        ///<summary>
        ///标题
        ///</summary>
        public string Title { get; set; }

        ///<summary>
        ///申请人
        ///</summary>
        public string Applicant { get; set; }

        ///<summary>
        ///申请人id
        ///</summary>
        public long? ApplicantId { get; set; }

        ///<summary>
        ///申请单位
        ///</summary>
        public string CompanyName { get; set; }

        ///<summary>
        ///申请单位ID
        ///</summary>
        public long? CompanyId { get; set; }

        ///<summary>
        ///申请日期
        ///</summary>
        public DateTime? ApplyDate { get; set; }

        ///<summary>
        ///申请部门
        ///</summary>
        public string Department { get; set; }

        ///<summary>
        ///申请部门ID
        ///</summary>
        public long? DepartmentId { get; set; }

        ///<summary>
        ///合同名称
        ///</summary>
        public string ContractName { get; set; }

        ///<summary>
        ///合同报审序号
        ///</summary>
        public string ContractNumber { get; set; }

        ///<summary>
        ///联系人
        ///</summary>
        public string Contact { get; set; }

        ///<summary>
        ///联系人电话
        ///</summary>
        public string ContactNumber { get; set; }

        ///<summary>
        ///项目名称
        ///</summary>
        public string ProjectName { get; set; }

        ///<summary>
        ///批文号
        ///</summary>
        public string ApprovalNo { get; set; }

        ///<summary>
        ///物资种类编号
        ///</summary>
        public string MaterialNumber { get; set; }

        ///<summary>
        ///物资种类名称
        ///</summary>
        public string MaterialName { get; set; }

        ///<summary>
        ///erp订单号
        ///</summary>
        public string ErpOrderNumber { get; set; }

        ///<summary>
        ///供应商名称
        ///</summary>
        public string SupplierName { get; set; }

        ///<summary>
        ///供应商地址
        ///</summary>
        public string SupplierAdress { get; set; }

        ///<summary>
        ///供应商邮编
        ///</summary>
        public string SupplierCode { get; set; }

        ///<summary>
        ///收件人
        ///</summary>
        public string Recipient { get; set; }

        ///<summary>
        ///电话
        ///</summary>
        public string Phone { get; set; }

        ///<summary>
        ///当前状态
        ///</summary>
        public string StateType { get; set; }

        ///<summary>
        ///状态编码
        ///</summary>
        public string StateName { get; set; }

        ///<summary>
        ///部门负责人ID
        ///</summary>
        public long? DepLeaderId { get; set; }

        ///<summary>
        ///部门负责人
        ///</summary>
        public string DepLeaderName { get; set; }

        ///<summary>
        ///分管领导ID
        ///</summary>
        public long? LeaderId { get; set; }

        ///<summary>
        ///分管领导
        ///</summary>
        public string LeaderName { get; set; }

        ///<summary>
        ///签字意见
        ///</summary>
        public string SignIdea { get; set; }

        ///<summary>
        ///流程ID
        ///</summary>
        public string WorkFlowId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ApprovalName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public long? ApprovalNameId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public int? State { get; set; }

        public decimal? Amount { get; set; }

        [NotMapped]
        public List<Epm_TzGcGoodsOrdersItem> TzGcGoodsOrdersItem { get; set; }
    }
}

