//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-07-16 14:17:15
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    public class Epm_ApproverRecord: BaseBusiness
    {
        ///<summary>
		///业务Id
		///</summary>
		public long? BusinessId { get; set; }

        ///<summary>
        ///业务名称
        ///</summary>
        public string BusinessName { get; set; }

        ///<summary>
        ///业务类型
        ///</summary>
        public string BusinessType { get; set; }

        ///<summary>
        ///业务状态
        ///</summary>
        public string BusinessState { get; set; }

        ///<summary>
        ///处理人名称
        ///</summary>
        public string HandleUserName { get; set; }

        ///<summary>
        ///处理人Id
        ///</summary>
        public long? HandleUserId { get; set; }

        ///<summary>
        ///备注
        ///</summary>
        public string Reason { get; set; }

        ///<summary>
        ///创建单位ID
        ///</summary>
        public long? CrtCompanyId { get; set; }

        ///<summary>
        ///创建单位名称
        ///</summary>
        public string CrtCompanyName { get; set; }
    }
}
