//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-08-22 16:32:49
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_TzSiteSurvey: 现场调研
    ///</summary>
    public class  Epm_TzSiteSurvey:BaseBusiness
    {
        public Epm_TzSiteSurvey()
        {
            TzAttachs = new List<Epm_TzAttachs>();
        }

        ///<summary>
        ///
        ///</summary>
        public long? ProjectId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectCodeInvest { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectCodeWhole { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectCodeProject { get; set; }

        ///<summary>
        ///
        ///</summary>
        public DateTime? InspectStTime { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string IncestPerson { get; set; }

        ///<summary>
        ///
        ///</summary>
        public long? IncestPersonId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string IncestJobType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string IncestJobName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Location { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string EnvironmentType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string EnvironmentName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string NatureType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string NatureName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string UseType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string UseName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public decimal? Area { get; set; }

        ///<summary>
        ///
        ///</summary>
        public decimal? Form { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string IsWithType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string IsWithName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public int? ExpectAmount { get; set; }

        ///<summary>
        ///
        ///</summary>
        public int? TrafficFlow { get; set; }

        ///<summary>
        ///
        ///</summary>
        public decimal? OilGuess { get; set; }

        ///<summary>
        ///
        ///</summary>
        public decimal? DieselGR { get; set; }

        ///<summary>
        ///
        ///</summary>
        public decimal? Price { get; set; }

        ///<summary>
        ///
        ///</summary>
        public decimal? GasGuess { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string LawPerson { get; set; }

        ///<summary>
        ///
        ///</summary>
        public long? LawPersonId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string LawJobType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string LawJobName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string PropertyIsType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string PropertyIsName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string QualificationIsType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string QualificationIs { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string DisputesIsType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string DisputesIsName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string LicensesTypeType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string LicensesTypeName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string EngineeringPerson { get; set; }

        ///<summary>
        ///
        ///</summary>
        public long? EngineeringPersonId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string EngineeringJobType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string EngineeringJobName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ImageIsType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ImageIsName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public decimal? Tent { get; set; }

        ///<summary>
        ///
        ///</summary>
        public int? OilT { get; set; }

        ///<summary>
        ///
        ///</summary>
        public int? OilQ { get; set; }

        ///<summary>
        ///
        ///</summary>
        public int? GasT { get; set; }

        ///<summary>
        ///
        ///</summary>
        public int? GasQ { get; set; }

        ///<summary>
        ///
        ///</summary>
        public decimal? Tank { get; set; }

        ///<summary>
        ///
        ///</summary>
        public decimal? Station { get; set; }

        ///<summary>
        ///
        ///</summary>
        public decimal? GasStorageWell { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string InforSystemType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string InforSystemName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string TranSType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string TranSName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string BusinessPerson { get; set; }

        ///<summary>
        ///
        ///</summary>
        public decimal? BusinessPersonId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string BusinessJobType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string BusinessJobName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string SalesIsType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string SalesIsName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public decimal? Distance { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Source { get; set; }

        ///<summary>
        ///
        ///</summary>
        public decimal? Oilsales { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string MethodsIsType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string MethodsIsName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public decimal? GasSales { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string SecurityPerson { get; set; }

        ///<summary>
        ///
        ///</summary>
        public long? SecurityPersonId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string SecurityJobType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string SecurityJobName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProtectionIsType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProtectionIsName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string HiddenIsType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string HiddenIsName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string MeasuresIs { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string InforPerson { get; set; }

        ///<summary>
        ///
        ///</summary>
        public long? InforPersonID { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string InforJobType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string InforJobName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Plans { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Remark { get; set; }

        ///<summary>
        ///
        ///</summary>
        public int? State { get; set; }


        [NotMapped]
        public List<Epm_TzAttachs> TzAttachs { get; set; }
    }
}

