//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-10-14 17:32:48
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_TzResearchOfSecurity:安全方面调研
	///</summary>
	 public  class  Epm_TzResearchOfSecurity:BaseBusiness
	{ 
		///<summary>
		///所属项目ID
		///</summary>
		public long? ProjectId { get; set; }

		///<summary>
		///调研开始日期
		///</summary>
		public DateTime? ResearchStartDate { get; set; }

		///<summary>
		///调研截止日期
		///</summary>
		public DateTime? ResearchEndDate { get; set; }

		///<summary>
		///调研人ID
		///</summary>
		public long? ResearchUserId { get; set; }

		///<summary>
		///调研人姓名
		///</summary>
		public string ReaearchUserName { get; set; }

		///<summary>
		///调研人协同OA编码
		///</summary>
		public string ReaearchUserXt { get; set; }

		///<summary>
		///职务编码(字典)
		///</summary>
		public string JobCode { get; set; }

		///<summary>
		///职务名称
		///</summary>
		public string JobName { get; set; }

		///<summary>
		///环保问题
		///</summary>
		public string Environmental { get; set; }

		///<summary>
		///改进措施
		///</summary>
		public string ImprovementMeasures { get; set; }

		///<summary>
		///隐患问题
		///</summary>
		public string hiddenDanger { get; set; }

		///<summary>
		///
		///</summary>
		public int State { get; set; }

		/////<summary>
		/////
		/////</summary>
		//public long? OpearateUserId { get; set; }

		/////<summary>
		/////
		/////</summary>
		//public string OpearateUserName { get; set; }

		/////<summary>
		/////
		/////</summary>
		//public DateTime? OpearateTime { get; set; }

	}
}

