//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:52
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_SpecialAcceptance:专项验收表
	///</summary>
	 public  class  Epm_SpecialAcceptance:BaseBusiness
	{ 
		///<summary>
		///项目表Id
		///</summary>
		public long? ProjectId { get; set; }

		///<summary>
		///项目名称
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///先不做维护，字典表配置几个类型，竣工验收时判断必须都有专项验收
		///</summary>
		public long? TypeId { get; set; }

		///<summary>
		///先不做维护，字典表配置几个类型，竣工验收时判断必须都有专项验收
		///</summary>
		public string TypeName { get; set; }

		///<summary>
		///验收标题
		///</summary>
		public string Title { get; set; }

		///<summary>
		///验收内容
		///</summary>
		public string Content { get; set; }

		///<summary>
		///第几次验收
		///</summary>
		public int? Num { get; set; }

		///<summary>
		///验收单位Id
		///</summary>
		public long? RecCompanyId { get; set; }

		///<summary>
		///验收单位Name
		///</summary>
		public string RecCompanyName { get; set; }

		///<summary>
		///验收人Id
		///</summary>
		public long? RecUserId { get; set; }

		///<summary>
		///验收人Name
		///</summary>
		public string RecUserName { get; set; }

		///<summary>
		///验收时间
		///</summary>
		public DateTime? RecTime { get; set; }

		///<summary>
		///验收结果【1通过、2不通过】枚举
		///</summary>
		public int? AcceptanceResult { get; set; }

		///<summary>
		///状态[10待处理,20审核通,30已驳回,40已废弃]枚举
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

	}
}

