//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-08-14 08:57:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///EPM_ProjectConstituteHistory:
    ///</summary>
    public class Epm_ProjectConstituteHistory : BaseBusiness
    {
        ///<summary>
        ///项目Id
        ///</summary>
        public long? ProjectId { get; set; }

        ///<summary>
        ///总批复构成
        ///</summary>
        public string ConstituteKey { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ConstituteValue { get; set; }

        ///<summary>
        ///是否计费
        ///</summary>
        public bool? IsCharging { get; set; }

        ///<summary>
        ///是否甲供设备 1是 0否
        ///</summary>
        public bool? IsAProvide { get; set; }

        /// <summary>
        /// 排序
        /// </summary>
        public int? Sort { get; set; }

        ///<summary>
        ///金额，单位万元
        ///</summary>
        public decimal? Amount { get; set; }

    }
}

