//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:52
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_ProjectDataSubmit:项目提交资料表
	///</summary>
	 public  class  Epm_ProjectDataSubmit:BaseBusiness
	{ 
		///<summary>
		///项目表Id
		///</summary>
		public long? ProjectId { get; set; }

		///<summary>
		///项目名称
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///里程碑表Id
		///</summary>
		public long? MilepostId { get; set; }

		///<summary>
		///里程碑名称
		///</summary>
		public string MilepostName { get; set; }

		///<summary>
		///监理日志表Id
		///</summary>
		public long? SupervisorId { get; set; }

		///<summary>
		///资料表Id
		///</summary>
		public long? FileId { get; set; }

		///<summary>
		///资料名
		///</summary>
		public string FileName { get; set; }

		///<summary>
		///文件名
		///</summary>
		public string Name { get; set; }

		///<summary>
		///上传人Id
		///</summary>
		public long? UploadUserId { get; set; }

		///<summary>
		///上传人Name
		///</summary>
		public string UploadUserName { get; set; }

		///<summary>
		///上传时间
		///</summary>
		public DateTime? UploadTime { get; set; }

		///<summary>
		///顺序
		///</summary>
		public int? Sort { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

	}
}

