//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-10-29 08:57:53
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_TzLandNegotiation:
	///</summary>
	 public  class  Epm_TzLandNegotiation:BaseBusiness
	{ 
		///<summary>
		///所属项目 ID
		///</summary>
		public long ProjectId { get; set; }

		///<summary>
		///谈判时间
		///</summary>
		public DateTime? TalkTime { get; set; }

		///<summary>
		///谈判地点
		///</summary>
		public string TalkAdress { get; set; }

		///<summary>
		///土地竞拍支付第一笔出让金
		///</summary>
		public decimal? Fees { get; set; }

		///<summary>
		///第一笔出让金日期
		///</summary>
		public DateTime? FeesTime { get; set; }

		///<summary>
		///我方谈判人
		///</summary>
		public string OurNegotiationers { get; set; }

		///<summary>
		///对方谈判人
		///</summary>
		public string OtherNegotiationers { get; set; }

		///<summary>
		///谈判结果编码
		///</summary>
		public string TalkResultType { get; set; }

		///<summary>
		///谈判结果
		///</summary>
		public string TalkResultName { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

        // <summary>
        /// 流程申请 ID
        /// </summary>
        public string WorkFlowId { get; set; }
        /// <summary>
        /// 相关附件(扩展字段)
        /// </summary>
        [NotMapped]
        public List<Epm_TzAttachs> TzAttachs { get; set; }

        ///<summary>
        ///当前状态
        ///</summary>
        public string StateType { get; set; }

        ///<summary>
        ///状态编码
        ///</summary>
        public string StateName { get; set; }

        /// <summary>
        /// 当前审批人
        /// </summary>
        public string ApprovalName { get; set; }

        /// <summary>
        /// 当前审批人Id
        /// </summary>
        public long? ApprovalNameId { get; set; }

        /// <summary>
        /// 开工报告审批时间（本次流程全部审批完成时间（年月日），若还未完成审批，不显示）
        /// </summary>
        public DateTime? WorkStartApprovalTime { get; set; }
    }
}

