//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_MonitorRectifRecord:检查整改记录表
    ///</summary>
    public class Epm_MonitorRectifRecord : BaseBusiness
    {
        ///<summary>
        ///检查ID
        ///</summary>
        public long? MonitorId { get; set; }

        ///<summary>
        ///整改内容
        ///</summary>
        public string Content { get; set; }

        ///<summary>
        ///要求整改完成日期
        ///</summary>
        public DateTime Deadline { get; set; }

        ///<summary>
        ///通过，不通过
        ///</summary>
        public int? Result { get; set; }

        ///<summary>
        ///整改完成日期
        ///</summary>
        public DateTime? FinishDate { get; set; }

        ///<summary>
        ///备注（整改意见）
        ///</summary>
        public string Remark { get; set; }

        ///<summary>
        ///状态 未整改，已整改
        ///</summary>
        public int State { get; set; }

    }
}
