//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-08-23 15:59:07
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_TzTalkRecordConfirm: 评审会投资部门确认
    ///</summary>
    public class  Epm_TzTalkRecordConfirm:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public long? DataId { get; set; }

		///<summary>
		///
		///</summary>
		public long? ProjectId { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectCodeInvest { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectCodeWhole { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectCodeProject { get; set; }

		///<summary>
		///
		///</summary>
		public string Reviewer { get; set; }

		///<summary>
		///
		///</summary>
		public string OthersType { get; set; }

		///<summary>
		///
		///</summary>
		public string OthersName { get; set; }

		///<summary>
		///
		///</summary>
		public string Idea { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///
		///</summary>
		public string OperationTypeType { get; set; }

		///<summary>
		///
		///</summary>
		public string OperationTypeName { get; set; }

		///<summary>
		///
		///</summary>
		public string StateType { get; set; }

		///<summary>
		///
		///</summary>
		public string StateName { get; set; }

		///<summary>
		///
		///</summary>
		public int? State { get; set; }

	}
}

