//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_CompletionAcceptance:
	///</summary>
	 public  class  Epm_CompletionAcceptance:BaseBusiness
	{ 
		///<summary>
		///项目表Id
		///</summary>
		public long? ProjectId { get; set; }

		///<summary>
		///项目名称
		///</summary>
		public string ProjectName { get; set; }

        public string Title { get; set; }

        ///<summary>
        ///验收内容
        ///</summary>
        public string Content { get; set; }

		///<summary>
		///第几次验收
		///</summary>
		public int? Num { get; set; }

		///<summary>
		///验收单位Id
		///</summary>
		public long? RecCompanyId { get; set; }

		///<summary>
		///验收单位Name
		///</summary>
		public string RecCompanyName { get; set; }

		///<summary>
		///验收人Id
		///</summary>
		public long? RecUserId { get; set; }

		///<summary>
		///验收人Name
		///</summary>
		public string RecUserName { get; set; }

		///<summary>
		///验收时间
		///</summary>
		public DateTime? RecTime { get; set; }

		///<summary>
		///验收结果【1通过，2不通过】枚举
		///</summary>
		public int? AcceptanceResult { get; set; }

		///<summary>
		///状态[10待处理,20审核通过,30已驳回,40已废弃]枚举
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }


        /// <summary>
        /// 整改内容
        /// </summary>
        public string RectifContent { get; set; }

    }
}

