//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-10-14 17:39:44
// </auto-generated>
//------------------------------------------------------------------------------
using hc.epm.DataModel.BaseCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_TzProjectProposal:加油站项目提出前
    ///</summary>
    public class Epm_TzProjectProposal : BaseBusiness
    {
        public Epm_TzProjectProposal()
        {
            TzAttachs = new List<Epm_TzAttachs>();
        }

        ///<summary>
        ///项目名称
        ///</summary>
        public string ProjectName { get; set; }

        ///<summary>
        ///项目编码(预留)
        ///</summary>
        public string ProjectCode { get; set; }

        ///<summary>
        ///协同OA系统编码(预留)
        ///</summary>
        public string ProjectCodeXt { get; set; }

        ///<summary>
        ///项目性质(数据字典)
        ///</summary>
        public string Nature { get; set; }

        ///<summary>
        ///项目性质名称
        ///</summary>
        public string NatureName { get; set; }

        ///<summary>
        ///加油站ID
        ///</summary>
        public long? StationId { get; set; }

        ///<summary>
        ///加油站名称
        ///</summary>
        public string StationName { get; set; }

        ///<summary>
        ///加油站编码
        ///</summary>
        public string StationCode { get; set; }

        ///<summary>
        ///协同OA 系统编码
        ///</summary>
        public string StationCodeXt { get; set; }

        ///<summary>
        ///加油站加管编码
        ///</summary>
        public string StationCodeJg { get; set; }

        ///<summary>
        ///提出时间
        ///</summary>
        public DateTime? ApplyTime { get; set; }

        ///<summary>
        ///所在省份
        ///</summary>
        public string ProvinceCode { get; set; }

        ///<summary>
        ///所在省份名称
        ///</summary>
        public string ProvinceName { get; set; }

        ///<summary>
        ///协同OA系统省份编码
        ///</summary>
        public string ProvinceCodeXt { get; set; }

        ///<summary>
        ///地市公司ID
        ///</summary>
        public long? CompanyId { get; set; }

        ///<summary>
        ///地市公司名称
        ///</summary>
        public string CompanyName { get; set; }

        ///<summary>
        ///协同OA 系统编码
        ///</summary>
        public string CompanyCodeXt { get; set; }

        ///<summary>
        ///推荐人
        ///</summary>
        public string Recommender { get; set; }

        ///<summary>
        ///推荐人职务
        ///</summary>
        public string RecommenderJob { get; set; }

        ///<summary>
        ///推荐人单位
        ///</summary>
        public string RecommenderDept { get; set; }

        ///<summary>
        ///申报人
        ///</summary>
        public string DeclarerUser { get; set; }

        ///<summary>
        ///地理位置编码
        ///</summary>
        public string PositionType { get; set; }

        ///<summary>
        ///地理位置
        ///</summary>
        public string Position { get; set; }

        ///<summary>
        ///项目地理位置
        ///</summary>
        public string ProjectAddress { get; set; }

        ///<summary>
        ///加油站类别
        ///</summary>
        public string StationType { get; set; }

        ///<summary>
        ///加油站类别名称
        ///</summary>
        public string StationTypeName { get; set; }

        ///<summary>
        ///估计金额
        ///</summary>
        public decimal? PredictMoney { get; set; }

        ///<summary>
        ///估计气日销量(CNG)/单位：千方
        ///</summary>
        public decimal? CNG { get; set; }

        ///<summary>
        ///估计气日销量(LNG)/单位：千方
        ///</summary>
        public decimal? LNG { get; set; }

        ///<summary>
        ///估计油日销量
        ///</summary>
        public decimal? OilSalesTotal { get; set; }

        ///<summary>
        ///项目批复文号(项目批复后回写此字段)
        ///</summary>
        public string ApprovalNo { get; set; }

        ///<summary>
        ///备注(预留字段)
        ///</summary>
        public string Remark { get; set; }

        ///<summary>
        ///项目状态
        ///</summary>
        public int State { get; set; }

        /// <summary>
        /// 相关附件(扩展字段)
        /// </summary>
        [NotMapped]
        public List<Epm_TzAttachs> TzAttachs { get; set; }

        /// <summary>
        /// 项目阶段(扩展字段)
        /// </summary>
        [NotMapped]
        public string ProjectStage { get; set; }

        /// <summary>
        /// 项目对应业务阶段状态
        /// </summary>
        [NotMapped]
        public string OperateType { get; set; }

        /// <summary>
        /// 项目对应业务阶段状态名称
        /// </summary>
        [NotMapped]
        public string OperateTypeName { get; set; }

        /// <summary>
        /// 生成批复（请示）文号(扩展字段)
        /// </summary>
        [NotMapped]
        public string Titanic { get; set; }

        // <summary>
        /// 流程申请 ID
        /// </summary>
        public string WorkFlowId { get; set; }

        public string ProjectType { get; set; }

        ///<summary>
        ///当前状态
        ///</summary>
        public string StateType { get; set; }

        ///<summary>
        ///状态编码
        ///</summary>
        public string StateName { get; set; }

        /// <summary>
        /// 当前审批人
        /// </summary>
        public string ApprovalName { get; set; }

        /// <summary>
        /// 当前审批人Id
        /// </summary>
        public long? ApprovalNameId { get; set; }

        /// <summary>
        /// 开工报告审批时间（本次流程全部审批完成时间（年月日），若还未完成审批，不显示）
        /// </summary>
        public DateTime? WorkStartApprovalTime { get; set; }

        /// <summary>
        /// 申报人Id(多个用逗号隔开)
        /// </summary>
        public string DeclarerUserIds { get; set; }

    }
}

