//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2020-02-21 15:11:16
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_ProjectWeekly:
	///</summary>
	 public  class  Epm_ProjectWeekly:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string Code { get; set; }

		///<summary>
		///
		///</summary>
		public string Name { get; set; }

		///<summary>
		///
		///</summary>
		public long? CompanyId { get; set; }

		///<summary>
		///
		///</summary>
		public string CompanyName { get; set; }

		///<summary>
		///
		///</summary>
		public string Address { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? StartDate { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? EndDate { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? Amount { get; set; }

		///<summary>
		///
		///</summary>
		public long? ContactUserId { get; set; }

		///<summary>
		///
		///</summary>
		public string ContactUserName { get; set; }

		///<summary>
		///
		///</summary>
		public string ContactPhone { get; set; }

		///<summary>
		///
		///</summary>
		public int? State { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectState { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectNature { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectNatureName { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectSubjectCode { get; set; }

		///<summary>
		///
		///</summary>
		public long? PMId { get; set; }

		///<summary>
		///
		///</summary>
		public string PMName { get; set; }

		///<summary>
		///
		///</summary>
		public string PMPhone { get; set; }

		///<summary>
		///
		///</summary>
		public string ReplyNumber { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? PlanWorkStartTime { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? PlanWorkEndTime { get; set; }

		///<summary>
		///
		///</summary>
		public int? Limit { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? ReplyDate { get; set; }

		///<summary>
		///
		///</summary>
		public int? ConsumptionPeriod { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? ProjectPolitTime { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? BidResultTime { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? DesignSchemeTime { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? FinanceTime { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? ReplyTime { get; set; }

		///<summary>
		///
		///</summary>
		public string ApprovalNo { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? GasDailySales { get; set; }

		///<summary>
		///
		///</summary>
		public string DesignUnit { get; set; }

		///<summary>
		///
		///</summary>
		public long? TzProjectId { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? RecTime { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? InvestMoney { get; set; }

		///<summary>
		///
		///</summary>
		public string SupervisorUnitName { get; set; }

		///<summary>
		///
		///</summary>
		public string SupervisorUnit { get; set; }

		///<summary>
		///
		///</summary>
		public string WorkUnitPMName { get; set; }

		///<summary>
		///
		///</summary>
		public string WorkUnit { get; set; }

		///<summary>
		///
		///</summary>
		public int? WorkSchedule { get; set; }

		///<summary>
		///
		///</summary>
		public int? SurplusLimit { get; set; }

		///<summary>
		///
		///</summary>
		public int? FinalLimit { get; set; }

		///<summary>
		///
		///</summary>
		public string ProblemNum { get; set; }

		///<summary>
		///
		///</summary>
		public string SupervisorLogNum { get; set; }

		///<summary>
		///
		///</summary>
		public string SecurityCheckNum { get; set; }

		///<summary>
		///
		///</summary>
		public string QualityCheckNum { get; set; }

		///<summary>
		///
		///</summary>
		public string ScheduleRatio { get; set; }

		///<summary>
		///
		///</summary>
		public string BuildPhone { get; set; }

		///<summary>
		///
		///</summary>
		public string BuildUserName { get; set; }

		///<summary>
		///
		///</summary>
		public string SupervisorPhone { get; set; }

		///<summary>
		///
		///</summary>
		public string SupervisorUserName { get; set; }

		///<summary>
		///
		///</summary>
		public int? Type { get; set; }

		///<summary>
		///
		///</summary>
		public long? StateType { get; set; }

	}
}

