//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-08-15 09:04:34
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_WorkMainPoints:
    ///</summary>
    public class Epm_WorkMainPoints : BaseBusiness
    {
        ///<summary>
        ///工程内容
        ///</summary>
        public string DicKey { get; set; }

        ///<summary>
        ///工程内容
        ///</summary>
        public string DicValue { get; set; }

        ///<summary>
        ///工程内容项
        ///</summary>
        public string WorkMain { get; set; }

        ///<summary>
        ///工程内容值
        ///</summary>
        public string WorkMainValues { get; set; }

        ///<summary>
        ///单位
        ///</summary>
        public string Unit { get; set; }

        ///<summary>
        ///排序
        ///</summary>
        public int? Sort { get; set; }

    }
}

