//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:52
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_WorkUploadRealScene:作业实景表
    ///</summary>
    public class Epm_WorkUploadRealScene : BaseBusiness
    {
        /// <summary>
        /// 项目Id
        /// </summary>
        public long? ProjectId { get; set; }
        /// <summary>
        /// 危险作业Id
        /// </summary>
        public long? WorkId { get; set; }
        /// <summary>
        /// 危险作业名称
        /// </summary>
        public string WorkName { get; set; }
        /// <summary>
        /// 作业实景上传时间
        /// </summary>
        public DateTime? UploadTime { get; set; }
        ///<summary>
        ///状态
        ///</summary>
        public int? State { get; set; }
        ///<summary>
        ///备注
        ///</summary>
        public string Remark { get; set; }


    }
}