//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-09-02 13:52:36
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_TzDevResourceReportItem:
	///</summary>
	 public  class  Epm_TzDevResourceReportItem:BaseBusiness
	{ 
		///<summary>
		///所属申请 ID
		///</summary>
		public long? ApplyId { get; set; }

		///<summary>
		///地市编码
		///</summary>
		public string CityCode { get; set; }

		///<summary>
		///地市
		///</summary>
		public string Cities { get; set; }

		///<summary>
		///区县
		///</summary>
		public string County { get; set; }

		///<summary>
		///项目名称
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///项目位置
		///</summary>
		public string ProjectAdress { get; set; }

		///<summary>
		///项目性质编码
		///</summary>
		public string ProjectType { get; set; }

		///<summary>
		///项目性质
		///</summary>
		public string ProjectTypeName { get; set; }

		///<summary>
		///预计总投资额（万元）
		///</summary>
		public decimal? ProjectedInvestment { get; set; }

		///<summary>
		///可研销售
		///</summary>
		public decimal? ResearchSales { get; set; }

		///<summary>
		///汽柴比
		///</summary>
		public decimal? GasFuelRatio { get; set; }

		///<summary>
		///列为意向站时间
		///</summary>
		public DateTime? FixHour { get; set; }

		///<summary>
		///计划立项时间
		///</summary>
		public DateTime? PlanningTime { get; set; }

		///<summary>
		///业主姓名
		///</summary>
		public string OwnerName { get; set; }

		///<summary>
		///业主电话
		///</summary>
		public string OwnerPhone { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

	}
}

