//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_Change:变更表
	///</summary>
	 public  class  Epm_Change:BaseBusiness
	{ 
		///<summary>
		///项目表Id
		///</summary>
		public long? ProjectId { get; set; }

		///<summary>
		///项目名称
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///变更号
		///</summary>
		public string ChangeNo { get; set; }

		///<summary>
		///变更名称
		///</summary>
		public string ChangeName { get; set; }

		///<summary>
		///变更内容
		///</summary>
		public string ChangeContent { get; set; }

		///<summary>
		///变更原因
		///</summary>
		public string ChangeReason { get; set; }

		///<summary>
		///变更金额，单位万元
		///</summary>
		public decimal? ChangeAmount { get; set; }

		///<summary>
		///变更开始时间
		///</summary>
		public DateTime? ChangeStartTime { get; set; }

		///<summary>
		///变更结束时间
		///</summary>
		public DateTime? ChangeEndTime { get; set; }

		///<summary>
		///变更工期，单位天
		///</summary>
		public int? ChangeDays { get; set; }

		///<summary>
		///发起人Id
		///</summary>
		public long? SubmitUserId { get; set; }

		///<summary>
		///发起人Name
		///</summary>
		public string SubmitUserName { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

        /// <summary>
        /// 项目总金额
        /// </summary>
        public decimal? TotalAmount { get; set; }

        /// <summary>
        /// 调增额
        /// </summary>
        public decimal? AddAmount { get; set; }

        /// <summary>
        /// 调减额
        /// </summary>
        public decimal? ReduceAmount { get; set; }

    }
}

