//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-08-26 11:30:17
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_TzDesiginChangeApply:
    ///</summary>
    public class Epm_TzDesiginChangeApply : BaseBusiness
    {
        public Epm_TzDesiginChangeApply()
        {
            TzAttachs = new List<Epm_TzAttachs>();
        }

        ///<summary>
        ///【工程项目】项目ID
        ///</summary>
        public long? DataId { get; set; }

        ///<summary>
        ///标题
        ///</summary>
        public string Title { get; set; }

        ///<summary>
        ///标题ID
        ///</summary>
        public long? TitleID { get; set; }

        ///<summary>
        ///申请人
        ///</summary>
        public string Applicant { get; set; }

        ///<summary>
        ///申请人id
        ///</summary>
        public long? ApplicantID { get; set; }

        ///<summary>
        ///所属单位
        ///</summary>
        public string Unit { get; set; }

        ///<summary>
        ///所属单位ID
        ///</summary>
        public long? UnitID { get; set; }

        ///<summary>
        ///所属部门
        ///</summary>
        public string Department { get; set; }

        ///<summary>
        ///所属部门ID
        ///</summary>
        public long? DepartmentID { get; set; }

        ///<summary>
        ///申请日期
        ///</summary>
        public DateTime? ApplyDate { get; set; }

        ///<summary>
        ///工程名称
        ///</summary>
        public string ProjectName { get; set; }

        ///<summary>
        ///投资计划或合同造价（万元）
        ///</summary>
        public decimal? InvestmentCost { get; set; }

        ///<summary>
        ///变更增、减造价（万元）
        ///</summary>
        public decimal? ChangeCost { get; set; }

        ///<summary>
        ///建设单位
        ///</summary>
        public string ConstructionUnit { get; set; }

        public long? ConstructionUnitID { get; set; }
        ///<summary>
        ///建设单位联系人
        ///</summary>
        public string ConstructionUnitPeople { get; set; }

        ///<summary>
        ///建设单位电话
        ///</summary>
        public string ConstructionUnitPhone { get; set; }

        ///<summary>
        ///施工单位
        ///</summary>
        public string WorkUnit { get; set; }

        ///<summary>
        ///施工单位联系人
        ///</summary>
        public string WorkUnitPeople { get; set; }

        ///<summary>
        ///施工单位电话
        ///</summary>
        public string WorkUnitPhone { get; set; }

        ///<summary>
        ///监理单位
        ///</summary>
        public string SupervisionUnit { get; set; }

        ///<summary>
        ///监理单位联系人
        ///</summary>
        public string SupervisionUnitPeople { get; set; }

        ///<summary>
        ///监理单位电话
        ///</summary>
        public string SupervisionUnitPhone { get; set; }

        ///<summary>
        ///设计单位
        ///</summary>
        public string DesignUnit { get; set; }

        ///<summary>
        ///设计单位联系人
        ///</summary>
        public string DesignUnitPeople { get; set; }

        ///<summary>
        ///设计单位电话
        ///</summary>
        public string DesignUnitPhone { get; set; }

        ///<summary>
        ///变更的原因或依据
        ///</summary>
        public string ChangeCause { get; set; }

        ///<summary>
        ///变更的内容及范围
        ///</summary>
        public string ChangeContent { get; set; }

        ///<summary>
        ///工程量及工程造价的增减
        ///</summary>
        public string ProjectChange { get; set; }

        ///<summary>
        ///变更对工期等相关工作的影响
        ///</summary>
        public string Impact { get; set; }

        ///<summary>
        ///部门负责人id
        ///</summary>
        public long? HeaderID { get; set; }

        ///<summary>
        ///部门负责人
        ///</summary>
        public string HeaderName { get; set; }

        ///<summary>
        ///分管领导id
        ///</summary>
        public long? LeaderID { get; set; }

        ///<summary>
        ///分管领导
        ///</summary>
        public string LeaderName { get; set; }

        ///<summary>
        ///签字意见
        ///</summary>
        public string SignIdea { get; set; }

        ///<summary>
        ///当前状态
        ///</summary>
        public string StateType { get; set; }

        ///<summary>
        ///状态编码
        ///</summary>
        public string StateName { get; set; }

        /// <summary>
        /// 当前审批人
        /// </summary>
        public string ApprovalName { get; set; }

        /// <summary>
        /// 当前审批人Id
        /// </summary>
        public long? ApprovalNameId { get; set; }

        /// <summary>
        /// 状态 参考枚举：XtBusinessDataState
        /// </summary>
        public int? State { get; set; }

        /// <summary>
        /// 流程 ID
        /// </summary>
        public string WorkFlowId { get; set; }
        
        [NotMapped]
        public List<Epm_TzAttachs> TzAttachs { get; set; }
    }
}

