//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_NoticeUser:公告接收人员
    ///</summary>
    public class Epm_NoticeUser : BaseBusiness
    {
        ///<summary>
        ///公告表Id
        ///</summary>
        public long? NoticeId { get; set; }

        ///<summary>
        ///接收人Id
        ///</summary>
        public long? UserId { get; set; }

        ///<summary>
        ///接收人Name
        ///</summary>
        public string UserName { get; set; }

        ///<summary>
        ///状态 1 启用 0 禁用
        ///</summary>
        public int? State { get; set; }

        ///<summary>
        ///备注
        ///</summary>
        public string Remark { get; set; }
    }
}
