//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:49:35
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
	///<summary>
	///Epm_Template:模板表
	///</summary>
	 public  class  Epm_Template:BaseBusiness
    {
		///<summary>
		///模板类型Key
		///</summary>
		public long? TemplateTypeId { get; set; }

		///<summary>
		///模板类型Value
		///</summary>
		public string TemplateTypeName { get; set; }

		///<summary>
		///标题
		///</summary>
		public string Title { get; set; }

		///<summary>
		///说明
		///</summary>
		public string Description { get; set; }

		///<summary>
		///验收/培训单位Id
		///</summary>
		public long? TrainCompanyId { get; set; }

		///<summary>
		///验收/培训单位Name
		///</summary>
		public string TrainCompanyName { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///创建单位Id
		///</summary>
		public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

    }
}

