//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:52
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_ProjectStateTrack:项目最新状态表
	///</summary>
	 public  class  Epm_ProjectStateTrack:BaseBusiness
	{ 
		///<summary>
		///项目表Id
		///</summary>
		public long? ProjectId { get; set; }

		///<summary>
		///状态跟踪类型No
		///</summary>
		public string StateTrackNo { get; set; }

		///<summary>
		///状态跟踪类型Name
		///</summary>
		public string StateTrackName { get; set; }

		///<summary>
		///数量，也可文本
		///</summary>
		public string Qty { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

		///<summary>
		///备注
		///</summary>
		public string Remark { get; set; }

        ///<summary>
		///单位Id
		///</summary>
		public long? CompanyId { get; set; }

        ///<summary>
        ///单位Name
        ///</summary>
        public string CompanyName { get; set; }

        ///<summary>
        ///创建单位Id
        ///</summary>
        public long? CrtCompanyId { get; set; }

		///<summary>
		///创建单位Name
		///</summary>
		public string CrtCompanyName { get; set; }

	}
}

