//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-08-08 11:07:13
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Epm_ProjectAuditRecord:
	///</summary>
	 public  class  Epm_ProjectAuditRecord:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public long? ProjectId { get; set; }

		///<summary>
		///
		///</summary>
		public long? ApprovalId { get; set; }

		///<summary>
		///
		///</summary>
		public string StepId { get; set; }

		///<summary>
		///
		///</summary>
		public string StepName { get; set; }

		///<summary>
		///
		///</summary>
		public long? AuditUserId { get; set; }

		///<summary>
		///
		///</summary>
		public string AuditUserCode { get; set; }

		///<summary>
		///
		///</summary>
		public string AuditName { get; set; }

		///<summary>
		///
		///</summary>
		public string AuditState { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? AuditTime { get; set; }

		///<summary>
		///
		///</summary>
		public string AuditRemark { get; set; }

		///<summary>
		///
		///</summary>
		public string AuditSign { get; set; }

		///<summary>
		///
		///</summary>
		public int? State { get; set; }

        ///<summary>
		///下一步审批人ID
		///</summary>
		public long? NextAuditUserId { get; set; }

        ///<summary>
        ///下一步审批人编码
        ///</summary>
        public string NextAuditUserCode { get; set; }

        ///<summary>
        ///下一步审批人名称
        ///</summary>
        public string NextAuditName { get; set; }

        /// <summary>
        /// 下一步审批步骤ID
        /// </summary>
        public string NextStepId { get; set; }

        /// <summary>
        /// 下一步审批步骤名称
        /// </summary>
        public string NextStepName { get; set; }

        /// <summary>
        /// 审批最终状态 等于 1 审核完成
        /// </summary>
        public int ApprovalState { get; set; }

        /// <summary>
        /// 流程 ID
        /// </summary>
        public string WorkFlowId { get; set; }
    }
}

