//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-02-27 14:26:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    public class EPM_UnconventionalWork : BaseBusiness
    {
        ///<summary>
		///
		///</summary>
		public long? InspectId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public long? CheckParentId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public long? CheckId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Name { get; set; }

        ///<summary>
        ///
        ///</summary>
        public int? Score { get; set; }

        ///<summary>
        ///
        ///</summary>
        public int? Level { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ScoreRang { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Remark { get; set; }

        ///<summary>
        ///
        ///</summary>
        public long? CrtCompanyId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string CrtCompanyName { get; set; }

        public string Type { get; set; }
    }
}
