//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2018-05-14 14:26:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///Epm_MaterielDetails:材料设备验收明细表
    ///</summary>
    public class  Epm_MaterielDetails:BaseBusiness
	{
        ///<summary>
        ///材料设备验收表Id
        ///</summary>
        public long? MaterielReceiveId { get; set; }

        ///<summary>
        ///材料设备验收分类Key
        ///</summary>
        public string MaterielTypeNo { get; set; }

        ///<summary>
        ///材料设备验收分类Value
        ///</summary>
        public string MaterielTypeName { get; set; }

		///<summary>
		///名称
		///</summary>
		public string Name { get; set; }

		///<summary>
		///型号
		///</summary>
		public string Model { get; set; }

		///<summary>
		///数量
		///</summary>
		public decimal? Qty { get; set; }

        /// <summary>
        /// 验收数量
        /// </summary>
        public int? UseSum { get; set; }

        /// <summary>
        /// 待验收数量
        /// </summary>
        public int? StayUseSum { get; set; }

        /// <summary>
        /// 总验收数量
        /// </summary>
        [NotMapped]
        public int? TotalUseSum { get; set; }

        /// <summary>
        /// 供应商名称
        /// </summary>
        public string Unit { get; set; }

        ///<summary>
        ///顺序
        ///</summary>
        public int? Sort { get; set; }

		///<summary>
		///状态
		///</summary>
		public int? State { get; set; }

        ///<summary>
        ///备注
        ///</summary>
        public string Remark { get; set; }

        /// <summary>
        /// 甲供物资详情Id
        /// </summary>
        public long? SupMatApplyListId { get; set; }

        /// <summary>
        /// 甲供物资申请Id
        /// </summary>
        public long? SupMatApplyId { get; set; }
    }
}

