//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-12-19 14:31:22
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///OMADS_ProjectInfo:
	///</summary>
	 public  class  OMADS_ProjectInfo:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string ProjectTypeName { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectNatureName { get; set; }

		///<summary>
		///
		///</summary>
		public string Code { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectLeaderName { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectAddress { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectDecisionerName { get; set; }

		///<summary>
		///
		///</summary>
		public string WriterName { get; set; }

		///<summary>
		///
		///</summary>
		public string username { get; set; }

		///<summary>
		///
		///</summary>
		public string companys { get; set; }

		///<summary>
		///
		///</summary>
		public string FilePath { get; set; }

		///<summary>
		///
		///</summary>
		public int? FileNumber { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteMark { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteResult { get; set; }

		///<summary>
		///
		///</summary>
		public string FollowOperate { get; set; }

	}
}

