//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2020-01-07 11:01:55
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///OMADS_TzDesignScheme:
	///</summary>
	 public  class  OMADS_TzDesignScheme:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///
		///</summary>
		public string ApprovalNo { get; set; }

		///<summary>
		///
		///</summary>
		public string NatureName { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? ApplyTime { get; set; }

		///<summary>
		///
		///</summary>
		public string StationName { get; set; }

		///<summary>
		///
		///</summary>
		public string CompanyName { get; set; }

		///<summary>
		///
		///</summary>
		public string DesignUnit { get; set; }

		///<summary>
		///
		///</summary>
		public string StandarName { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? Estimate { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? TotalInvestment { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? OtheInvestment { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? InviteTime { get; set; }

		///<summary>
		///
		///</summary>
		public string DesignUnitCharge { get; set; }

		///<summary>
		///
		///</summary>
		public string DesignJob { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectManager { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectJob { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? LandArea { get; set; }

		///<summary>
		///
		///</summary>
		public int? MachineofOilStage { get; set; }

		///<summary>
		///
		///</summary>
		public int? MachineofGasStage { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? GasWells { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? OilTank { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? Shelter { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? StationRoom { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? ConvenienceRoom { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? ReleaseInvestmentAmount { get; set; }

		///<summary>
		///
		///</summary>
		public string OtherProject { get; set; }

		///<summary>
		///
		///</summary>
		public string IsSynchro { get; set; }

		///<summary>
		///
		///</summary>
		public int? State { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectCode { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteMark { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteResult { get; set; }

		///<summary>
		///
		///</summary>
		public string FollowOperate { get; set; }

		///<summary>
		///
		///</summary>
		public int? FileNumber { get; set; }

		///<summary>
		///
		///</summary>
		public string FilePath { get; set; }

		///<summary>
		///
		///</summary>
		public string username { get; set; }

		///<summary>
		///
		///</summary>
		public int? status1 { get; set; }

		///<summary>
		///
		///</summary>
		public int? status2 { get; set; }

		///<summary>
		///
		///</summary>
		public int? status3 { get; set; }

	}
}

