//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-12-27 11:28:25
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///OMADS_ReformRecordHX:
	///</summary>
	 public  class  OMADS_ReformRecordHX:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///
		///</summary>
		public string RemarkType { get; set; }

		///<summary>
		///
		///</summary>
		public string StationName { get; set; }

		///<summary>
		///
		///</summary>
		public string CompanyName { get; set; }

		///<summary>
		///
		///</summary>
		public string LimitType { get; set; }

		///<summary>
		///
		///</summary>
		public string SourceFund { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? Investment { get; set; }

		///<summary>
		///
		///</summary>
		public string ItemNumber { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? ItemTime { get; set; }

		///<summary>
		///
		///</summary>
		public string ItemUnit { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? ItemMoney { get; set; }

		///<summary>
		///
		///</summary>
		public string InitialNumber { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? InitialMoney { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? RemarkStartTime { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? RemarkEndTime { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? RemarkMoney { get; set; }

		///<summary>
		///
		///</summary>
		public string DecisionMaker { get; set; }

		///<summary>
		///
		///</summary>
		public string LeaderPerson { get; set; }

		///<summary>
		///
		///</summary>
		public string Operator { get; set; }

		///<summary>
		///
		///</summary>
		public string PipetteCoding { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? InitialSalesOfRefinedOil { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? RemarkSalesOfRefinedOil { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? InitialSalesOfGas { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? RemarkSalesOfGas { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? IRR { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectContent { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///
		///</summary>
		public string AnnexType { get; set; }

		///<summary>
		///
		///</summary>
		public string Approver { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? ApproveTime { get; set; }

		///<summary>
		///
		///</summary>
		public string ApproveResult { get; set; }

		///<summary>
		///
		///</summary>
		public string ApproveRemark { get; set; }

		///<summary>
		///
		///</summary>
		public string AreaCompanyName { get; set; }

		///<summary>
		///
		///</summary>
		public string AreaCompanyCode { get; set; }

		///<summary>
		///
		///</summary>
		public string username { get; set; }

		///<summary>
		///
		///</summary>
		public string FilePath { get; set; }

		///<summary>
		///
		///</summary>
		public int? FileNumber { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteMark { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteResult { get; set; }

		///<summary>
		///
		///</summary>
		public string FollowOperate { get; set; }

	}
}

