//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-12-27 14:17:03
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///OMADS_CompletionInfo:
	///</summary>
	 public  class  OMADS_CompletionInfo:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public decimal? Settlement { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? CompletionDate { get; set; }

		///<summary>
		///
		///</summary>
		public string IsSynchron { get; set; }

		///<summary>
		///
		///</summary>
		public string username { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteMark { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteResult { get; set; }

		///<summary>
		///
		///</summary>
		public string FollowOperate { get; set; }

	}
}

