//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-12-02 14:14:27
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///OMADS_TzProjectApprovalHX:
    ///</summary>
    public class OMADS_TzProjectApprovalHX : BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string ApplyName { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? ApplyTime { get; set; }

		///<summary>
		///
		///</summary>
		public string LimitTypeType { get; set; }

		///<summary>
		///
		///</summary>
		public string Drafter { get; set; }

		///<summary>
		///
		///</summary>
		public string SignPeople { get; set; }

		///<summary>
		///
		///</summary>
		public string Signer { get; set; }

		///<summary>
		///
		///</summary>
		public string Titanic { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///
		///</summary>
		public string username { get; set; }

		///<summary>
		///
		///</summary>
		public string companys { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteMark { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteResult { get; set; }

		///<summary>
		///
		///</summary>
		public string FollowOperate { get; set; }

		///<summary>
		///
		///</summary>
		public string FilePath { get; set; }

        public int FileNumber { get; set; }

		public string ProjectName { get; set; }
	}
}

