//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2020-01-07 11:01:55
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///OMADS_ConstructionInfo:
	///</summary>
	 public  class  OMADS_ConstructionInfo:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string IsShortlistSJ { get; set; }

		///<summary>
		///
		///</summary>
		public string IsApprovalSJ { get; set; }

		///<summary>
		///
		///</summary>
		public string EngineeringMM { get; set; }

		///<summary>
		///
		///</summary>
		public string DesignUnit { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectManagerSJ { get; set; }

		///<summary>
		///
		///</summary>
		public string IsShortlistSG { get; set; }

		///<summary>
		///
		///</summary>
		public string IsApprovalSG { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? PlanStartTime { get; set; }

		///<summary>
		///
		///</summary>
		public string ConstructionName { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectManagerSG { get; set; }

		///<summary>
		///
		///</summary>
		public string IsShortlistJL { get; set; }

		///<summary>
		///
		///</summary>
		public string IsApprovalJL { get; set; }

		///<summary>
		///
		///</summary>
		public string SupervisionUnit { get; set; }

		///<summary>
		///
		///</summary>
		public string SupervisionEngineer { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? ConstructionBudget { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? TenderingDateSG { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? TenderingDateJL { get; set; }

		///<summary>
		///
		///</summary>
		public string OilingMachineSource { get; set; }

		///<summary>
		///
		///</summary>
		public string LiquidLevelSource { get; set; }

		///<summary>
		///
		///</summary>
		public string OilTankSource { get; set; }

		///<summary>
		///
		///</summary>
		public string IsSynchro { get; set; }

		///<summary>
		///
		///</summary>
		public string StartProcedures { get; set; }

		///<summary>
		///
		///</summary>
		public string MeasureTD { get; set; }

		///<summary>
		///
		///</summary>
		public string MeasureJZ { get; set; }

		///<summary>
		///
		///</summary>
		public string MeasureXF { get; set; }

		///<summary>
		///
		///</summary>
		public string MeasureHJ { get; set; }

		///<summary>
		///
		///</summary>
		public string MeasureAQ { get; set; }

		///<summary>
		///
		///</summary>
		public string MeasureGC { get; set; }

		///<summary>
		///
		///</summary>
		public string MeasureKG { get; set; }

		///<summary>
		///
		///</summary>
		public string TestProcedures { get; set; }

		///<summary>
		///
		///</summary>
		public string MeasureTDSY { get; set; }

		///<summary>
		///
		///</summary>
		public string MeasureXFYS { get; set; }

		///<summary>
		///
		///</summary>
		public string MeasureHJYS { get; set; }

		///<summary>
		///
		///</summary>
		public string MeasureZL { get; set; }

		///<summary>
		///
		///</summary>
		public string MeasureAQSC { get; set; }

		///<summary>
		///
		///</summary>
		public string username { get; set; }

		///<summary>
		///
		///</summary>
		public string FilePath { get; set; }

		///<summary>
		///
		///</summary>
		public int? FileNumber { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteMark { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteResult { get; set; }

		///<summary>
		///
		///</summary>
		public string FollowOperate { get; set; }

	}
}

