//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-12-02 14:14:26
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{
    ///<summary>
    ///OMADS_TzConDrawing:
    ///</summary>
    public class OMADS_TzConDrawing : BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string ProjectTypeName { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? ReviewTime { get; set; }

		///<summary>
		///
		///</summary>
		public string ReviewAddress { get; set; }

		///<summary>
		///
		///</summary>
		public string Moderator { get; set; }

		///<summary>
		///
		///</summary>
		public string ReviewExperts { get; set; }

		///<summary>
		///
		///</summary>
		public string Participants { get; set; }

		///<summary>
		///
		///</summary>
		public string Conclusion { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///
		///</summary>
		public string username { get; set; }

		///<summary>
		///
		///</summary>
		public string companys { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteMark { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteResult { get; set; }

		///<summary>
		///
		///</summary>
		public string FollowOperate { get; set; }

		///<summary>
		///
		///</summary>
		public string FilePath { get; set; }
        public int FileNumber { get; set; }


    }
}

