//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-12-02 14:14:25
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///RPA_FieldInvestigation:
	///</summary>
	 public  class  RPA_FieldInvestigation:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public DateTime? ResearchStartDate { get; set; }

		///<summary>
		///
		///</summary>
		public string ResearchUserNameT { get; set; }

		///<summary>
		///
		///</summary>
		public string JobNameT { get; set; }

		///<summary>
		///
		///</summary>
		public string Address { get; set; }

		///<summary>
		///
		///</summary>
		public string EnvironmentTypeName { get; set; }

		///<summary>
		///
		///</summary>
		public string LandNatureName { get; set; }

		///<summary>
		///
		///</summary>
		public string LandUseName { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? LandArea { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? LandShape { get; set; }

		///<summary>
		///
		///</summary>
		public string IsMeetAreaPlan { get; set; }

		///<summary>
		///
		///</summary>
		public int? AroundCarCount { get; set; }

		///<summary>
		///
		///</summary>
		public int? DailyTraffic { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? OilSaleTotal { get; set; }

		///<summary>
		///
		///</summary>
		public string DieselGasolineRatio { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? LandPrice { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? GasSaleTotal { get; set; }

		///<summary>
		///
		///</summary>
		public string ResearchUserNameF { get; set; }

		///<summary>
		///
		///</summary>
		public string JobNameF { get; set; }

		///<summary>
		///
		///</summary>
		public string PropertyRights { get; set; }

		///<summary>
		///
		///</summary>
		public string AssetSubject { get; set; }

		///<summary>
		///
		///</summary>
		public string DisputesJudgment { get; set; }

		///<summary>
		///
		///</summary>
		public string License { get; set; }

		///<summary>
		///
		///</summary>
		public string ResearchUserNameG { get; set; }

		///<summary>
		///
		///</summary>
		public string JobNameG { get; set; }

		///<summary>
		///
		///</summary>
		public string IndustryPlanning { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? Shelter { get; set; }

		///<summary>
		///
		///</summary>
		public int? MachineOfOilStage { get; set; }

		///<summary>
		///
		///</summary>
		public int? MachineOfOil { get; set; }

		///<summary>
		///
		///</summary>
		public int? MachineOfGasStage { get; set; }

		///<summary>
		///
		///</summary>
		public int? MachineOfGas { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? OilTank { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? StationRoon { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? GasWells { get; set; }

		///<summary>
		///
		///</summary>
		public string HasInformationSystem { get; set; }

		///<summary>
		///
		///</summary>
		public string ReformName { get; set; }

		///<summary>
		///
		///</summary>
		public string ResearchUserNameJ { get; set; }

		///<summary>
		///
		///</summary>
		public string JobName { get; set; }

		///<summary>
		///
		///</summary>
		public string SalesRealizability { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? CargoDistance { get; set; }

		///<summary>
		///
		///</summary>
		public string SourceOfOil { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? CurrentSalesVolume { get; set; }

		///<summary>
		///
		///</summary>
		public string SalesMeans { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? GasDailySales { get; set; }

		///<summary>
		///
		///</summary>
		public string ResearchUserNameA { get; set; }

		///<summary>
		///
		///</summary>
		public string JobNameA { get; set; }

		///<summary>
		///
		///</summary>
		public string Environmental { get; set; }

		///<summary>
		///
		///</summary>
		public string hiddenDanger { get; set; }

		///<summary>
		///
		///</summary>
		public string ImprovementMeasures { get; set; }

		///<summary>
		///
		///</summary>
		public string ResearchUserNameX { get; set; }

		///<summary>
		///
		///</summary>
		public string JobNameX { get; set; }

		///<summary>
		///
		///</summary>
		public string Improvement { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteMark { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteResult { get; set; }

		///<summary>
		///
		///</summary>
		public string FollowOperate { get; set; }

		///<summary>
		///
		///</summary>
		public string username { get; set; }

		///<summary>
		///
		///</summary>
		public string companys { get; set; }

		///<summary>
		///
		///</summary>
		public string FilePath { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///
		///</summary>
		public string Auditor { get; set; }
        public int FileNumber { get; set; }

		public int status1 { get; set; }

	}
}

