//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-12-02 14:14:26
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///RPA_ProjectProposal:
	///</summary>
	 public  class  RPA_ProjectProposal:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///
		///</summary>
		public long? DataId { get; set; }

		///<summary>
		///
		///</summary>
		public string TableName { get; set; }

		///<summary>
		///
		///</summary>
		public long? ProjectId { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectCode { get; set; }

		///<summary>
		///
		///</summary>
		public string NatureName { get; set; }

		///<summary>
		///
		///</summary>
		public string StationName { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? ApplyTime { get; set; }

		///<summary>
		///
		///</summary>
		public string CompanyName { get; set; }

		///<summary>
		///
		///</summary>
		public string ProvincesName { get; set; }

		///<summary>
		///
		///</summary>
		public string Recommender { get; set; }

		///<summary>
		///
		///</summary>
		public string RecommenderJob { get; set; }

		///<summary>
		///
		///</summary>
		public string RecommenderCompany { get; set; }

		///<summary>
		///
		///</summary>
		public string Declarer { get; set; }

		///<summary>
		///
		///</summary>
		public string Position { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectAddress { get; set; }

		///<summary>
		///
		///</summary>
		public string StationCode { get; set; }

		///<summary>
		///
		///</summary>
		public string StationType { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? PredictMoney { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? PredictDayGas { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? PredictDayOil { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteMark { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteResult { get; set; }

		///<summary>
		///
		///</summary>
		public string FollowOperate { get; set; }

		///<summary>
		///
		///</summary>
		public string username { get; set; }

		///<summary>
		///
		///</summary>
		public string companys { get; set; }

		///<summary>
		///
		///</summary>
		public string FilePath { get; set; }

		///<summary>
		///
		///</summary>
		public string Auditor { get; set; }
        public int FileNumber { get; set; }
        /// <summary>
        /// 项目类型
        /// </summary>
        public string ProjectType { get; set; }
        public int status1 { get; set; }
    }
}

