//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-12-02 14:14:26
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///RPA_TzFirstNegotiation:
	///</summary>
	 public  class  RPA_TzFirstNegotiation: BaseBusiness
    { 
		///<summary>
		///
		///</summary>
		public DateTime? TalkTime { get; set; }

		///<summary>
		///
		///</summary>
		public string TalkAdress { get; set; }

		///<summary>
		///
		///</summary>
		public decimal? Fees { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? FeesTime { get; set; }

		///<summary>
		///
		///</summary>
		public string OurNegotiators { get; set; }

		///<summary>
		///
		///</summary>
		public string OtherNegotiators { get; set; }

		///<summary>
		///
		///</summary>
		public string TalkResultName { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteMark { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteResult { get; set; }

		///<summary>
		///
		///</summary>
		public string FollowOperate { get; set; }

		///<summary>
		///
		///</summary>
		public string username { get; set; }

		///<summary>
		///
		///</summary>
		public string companys { get; set; }

		///<summary>
		///
		///</summary>
		public string FilePath { get; set; }

        public int FileNumber { get; set; }

        public string ProjectName { get; set; }
        public int status1 { get; set; }
    }
}

