//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-12-02 14:14:27
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///RPA_TzFormTalkFileHX:
	///</summary>
	 public  class  RPA_TzFormTalkFileHX:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string ProjectLeaderName { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectDecisionerName { get; set; }

		///<summary>
		///
		///</summary>
		public string WriterName { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///
		///</summary>
		public string username { get; set; }

		///<summary>
		///
		///</summary>
		public string companys { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteMark { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteResult { get; set; }

		///<summary>
		///
		///</summary>
		public string FollowOperate { get; set; }

		///<summary>
		///
		///</summary>
		public string FilePath { get; set; }
        public int FileNumber { get; set; }
        public string ProjectName { get; set; }
        public int status1 { get; set; }
        public int status2 { get; set; }
    }
}

