//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2020-01-07 11:01:56
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///TEMP_TzProjectReveiews:
	///</summary>
	 public  class  TEMP_TzProjectReveiews:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? ReveiewDate { get; set; }

		///<summary>
		///
		///</summary>
		public string HostUser { get; set; }

		///<summary>
		///
		///</summary>
		public string Address { get; set; }

		///<summary>
		///
		///</summary>
		public string ConclusionName { get; set; }

		///<summary>
		///
		///</summary>
		public string InvitedExperts { get; set; }

		///<summary>
		///
		///</summary>
		public string Attendees { get; set; }

		///<summary>
		///
		///</summary>
		public string FilePath { get; set; }

		///<summary>
		///
		///</summary>
		public int? FileNumber { get; set; }

		///<summary>
		///
		///</summary>
		public int? status1 { get; set; }

		///<summary>
		///
		///</summary>
		public int? status2 { get; set; }

		///<summary>
		///
		///</summary>
		public int? status3 { get; set; }

		///<summary>
		///
		///</summary>
		public int? status4 { get; set; }

		///<summary>
		///
		///</summary>
		public int? status5 { get; set; }

		///<summary>
		///
		///</summary>
		public int? status6 { get; set; }

		///<summary>
		///
		///</summary>
		public int? status7 { get; set; }

		///<summary>
		///
		///</summary>
		public int? status8 { get; set; }

		///<summary>
		///
		///</summary>
		public int? UserId { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteMark { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteResult { get; set; }

		///<summary>
		///
		///</summary>
		public int? FollowOperate { get; set; }

		///<summary>
		///
		///</summary>
		public string username { get; set; }

	}
}

