//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-12-19 14:31:23
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///TEMP_CompanyProjectReveiews:
	///</summary>
	 public  class  TEMP_CompanyProjectReveiews:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///
		///</summary>
		public DateTime? ReveiewDate { get; set; }

		///<summary>
		///
		///</summary>
		public string HostUser { get; set; }

		///<summary>
		///
		///</summary>
		public string Address { get; set; }

		///<summary>
		///
		///</summary>
		public string Attendees { get; set; }

		///<summary>
		///
		///</summary>
		public string FilePath { get; set; }

		///<summary>
		///
		///</summary>
		public int? FileNumber { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteMark { get; set; }

		///<summary>
		///
		///</summary>
		public int? WriteResult { get; set; }

		///<summary>
		///
		///</summary>
		public string FollowOperate { get; set; }

        public string username { get; set; }
        ///<summary>
		///
		///</summary>
		public string InvitedExperts { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ConclusionName { get; set; }
        public int status1 { get; set; }
    }
}

