//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-04 08:45:08
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Basic
{ 
	///<summary>
	///Base_HistoryPassword:历史密码
	///</summary>
	 public  class  Base_HistoryPassword:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string Num { get; set; }

		///<summary>
		///密码
		///</summary>
		public string Password { get; set; }

		///<summary>
		///用户Id
		///</summary>
		public long UserId { get; set; }

		///<summary>
		///原密码
		///</summary>
		public string OldPassword { get; set; }

	}
}

