//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-04 08:45:08
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Basic
{ 
	///<summary>
	///Base_Log:日志
	///</summary>
	 public  class  Base_Log:BaseBusiness
	{ 
		///<summary>
		///用户ID
		///</summary>
		public long UserId { get; set; }

		///<summary>
		///用户帐号
		///</summary>
		public string UserAcct { get; set; }

		///<summary>
		///客户端IP
		///</summary>
		public string ClientIP { get; set; }

		///<summary>
		///服务IP
		///</summary>
		public string ServiceServerIP { get; set; }

		///<summary>
		///web服务器地址
		///</summary>
		public string WebServerIP { get; set; }

		///<summary>
		///模版名称
		///</summary>
		public string ModuleName { get; set; }

		///<summary>
		///功能名称
		///</summary>
		public string ActionDesc { get; set; }

		///<summary>
		///操作描述
		///</summary>
		public string Contents { get; set; }

	}
}

