//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-04 08:45:08
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Basic
{ 
	///<summary>
	///Base_Role:角色
	///</summary>
	 public  class  Base_Role:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string RoleName { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }
        
		///<summary>
		///角色归属
		///</summary>
		public string Belong { get; set; }

		///<summary>
		///所属企业
		///</summary>
		public long CompanyId { get; set; }

	}
}

