//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-04 08:45:08
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Basic
{ 
	///<summary>
	///Base_Region:
	///</summary>
	 public  class  Base_Region:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string RegionCode { get; set; }

		///<summary>
		///
		///</summary>
		public string RegionName { get; set; }

		///<summary>
		///
		///</summary>
		public string ParentCode { get; set; }

		///<summary>
		///
		///</summary>
		public bool IsActive { get; set; }

		///<summary>
		///
		///</summary>
		public string Fullname { get; set; }

		///<summary>
		///
		///</summary>
		public int? Sort { get; set; }

		///<summary>
		///
		///</summary>
		public int? AreaNum { get; set; }

		///<summary>
		///
		///</summary>
		public string AreaName { get; set; }

	}
}

