//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-04 08:45:08
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Basic
{
    ///<summary>
    ///Base_Company:企业
    ///</summary>
    public class Base_VideoManage : BaseBusiness
    {
        /// <summary>
        /// 项目ID 
        /// </summary>
        public long? Projectid { get; set; }
        /// <summary>
        /// 项目名称 
        /// </summary>
        public string ProjectName { get; set; }
        /// <summary>
        /// 设备名称 
        /// </summary>
        public string CameraName { get; set; }
        /// <summary>
        /// 设备状态 0 未激活， 1 激活
        /// </summary>
        public string CameraState { get; set; }
        /// <summary>
        /// 供应商ID 
        /// </summary>
        public long? Companyid { get; set; }
        /// <summary>
        /// 供应商名称 
        /// </summary>
        public string Companyname { get; set; }
        /// <summary>
        /// 设备负责人 
        /// </summary>
        public string CompanyPerson { get; set; }
        /// <summary>
        /// 设备序列号
        /// </summary>
        public string DeviceSequence { get; set; }
        /// <summary>
        ///  设备验证码 
        /// </summary>
        public string VerificationCode { get; set; }
        /// <summary>
        /// 描述信息 
        /// </summary>
        public string DescribeInfo { get; set; }
        /// <summary>
        /// URL 
        /// </summary>
        public string UrlAddress { get; set; }

    }
}

