//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-04 08:45:07
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Basic
{ 
	///<summary>
	///Base_StatusLog:状态日志
	///</summary>
	 public  class  Base_StatusLog:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string TableName { get; set; }

		///<summary>
		///表中某条数据
		///</summary>
		public long TableId { get; set; }

		///<summary>
		///变更后状态
		///</summary>
		public string State { get; set; }

		///<summary>
		///变更前状态
		///</summary>
		public string OldState { get; set; }

	}
}

