//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-04 08:45:08
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Basic
{ 
	///<summary>
	///Base_Dep:部门
	///</summary>
	 public  class  Base_Dep:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public string PreCode { get; set; }

		///<summary>
		///上级单位名称
		///</summary>
		public string PreName { get; set; }

		///<summary>
		///单位编码
		///</summary>
		public string Code { get; set; }

		///<summary>
		///单位名称
		///</summary>
		public string Name { get; set; }

		///<summary>
		///启用禁用
		///</summary>
		public bool IsEnable { get; set; }

		///<summary>
		///是否确认
		///</summary>
		public bool IsConfirm { get; set; }

		///<summary>
		///
		///</summary>
		public long CompanyId { get; set; }

		///<summary>
		///上级部门Id
		///</summary>
		public string PreId { get; set; }

	}
}

