//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-04 08:45:08
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Basic
{ 
	///<summary>
	///Base_UserRole:用户角色
	///</summary>
	 public  class  Base_UserRole:BaseBusiness
	{ 
		///<summary>
		///
		///</summary>
		public long UserId { get; set; }

		///<summary>
		///
		///</summary>
		public long RoleId { get; set; }

        public string Belong { get; set; }

    }
}

