//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-04 08:45:08
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Basic
{ 
	///<summary>
	///Base_Config:系统配置
	///</summary>
	 public  class  Base_Config:BaseBusiness
	{ 
		///<summary>
		///公司名称
		///</summary>
		public string Name { get; set; }

		///<summary>
		///简称
		///</summary>
		public string ShortName { get; set; }

		///<summary>
		///版权所有
		///</summary>
		public string CopyRight { get; set; }

		///<summary>
		///
		///</summary>
		public string LowRecord { get; set; }

		///<summary>
		///
		///</summary>
		public string ContractTel { get; set; }

		///<summary>
		///
		///</summary>
		public string Logo { get; set; }

	}
}

