//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-04 08:45:08
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Basic
{
    ///<summary>
    ///Base_RoleRight:角色权限
    ///</summary>
    public class Base_RoleRight : BaseBusiness
    {
        ///<summary>
        ///
        ///</summary>
        public long RoleId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public long RightId { get; set; }

        //public virtual Base_Right Right { get; set; }


    }
}

