//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2017-08-10 16:43:02
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
namespace hc.epm.DataModel.Basic
{
    ///<summary>
    ///Base_Right:权限
    ///</summary>
    public class Base_Right : BaseBusiness
    {
        ///<summary>
        ///
        ///</summary>
        public string Belong { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string RightType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public long ParentId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ParentName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ParentCode { get; set; }


        public bool IsMenu { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Code { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Name { get; set; }
        
        public string ShortName { get; set; }
        ///<summary>
        ///url地址
        ///</summary>
        public string URL { get; set; }

        ///<summary>
        ///提示
        ///</summary>
        public string Tips { get; set; }

        ///<summary>
        ///图标
        ///</summary>
        public string Icon { get; set; }

        ///<summary>
        ///排序，数字越小越靠前
        ///</summary>
        public int Sort { get; set; }

        ///<summary>
        ///备注
        ///</summary>
        public string Remark { get; set; }
        
        /// <summary>
        /// 显示名称
        /// </summary>
        public string DisplayName { get; set; }

        /// <summary>
        /// 打开方式
        /// </summary>
        public string Target { get; set; }

        /// <summary>
        /// css样式类名
        /// </summary>
        public string CssClass { get; set; }

    }
}

