//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-09-02 11:50:00
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations;

namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Temp_TzSiteSurvey:
	///</summary>
	 public  class  Temp_TzSiteSurvey
	{
        [Key]
        public long Id { get; set; }
        ///<summary>
        ///
        ///</summary>
        public string ProjectId { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectCodeInvest { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectCodeWhole { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectCodeProject { get; set; }

		///<summary>
		///
		///</summary>
		public string InspectStTime { get; set; }

		///<summary>
		///
		///</summary>
		public string IncestPerson { get; set; }

		///<summary>
		///
		///</summary>
		public string IncestPersonId { get; set; }

		///<summary>
		///
		///</summary>
		public string IncestJobType { get; set; }

		///<summary>
		///
		///</summary>
		public string IncestJobName { get; set; }

		///<summary>
		///
		///</summary>
		public string Location { get; set; }

		///<summary>
		///
		///</summary>
		public string EnvironmentType { get; set; }

		///<summary>
		///
		///</summary>
		public string EnvironmentName { get; set; }

		///<summary>
		///
		///</summary>
		public string NatureType { get; set; }

		///<summary>
		///
		///</summary>
		public string NatureName { get; set; }

		///<summary>
		///
		///</summary>
		public string UseType { get; set; }

		///<summary>
		///
		///</summary>
		public string UseName { get; set; }

		///<summary>
		///
		///</summary>
		public string Area { get; set; }

		///<summary>
		///
		///</summary>
		public string Form { get; set; }

		///<summary>
		///
		///</summary>
		public string IsWithType { get; set; }

		///<summary>
		///
		///</summary>
		public string IsWithName { get; set; }

		///<summary>
		///
		///</summary>
		public string ExpectAmount { get; set; }

		///<summary>
		///
		///</summary>
		public string TrafficFlow { get; set; }

		///<summary>
		///
		///</summary>
		public string OilGuess { get; set; }

		///<summary>
		///
		///</summary>
		public string DieselGR { get; set; }

		///<summary>
		///
		///</summary>
		public string Price { get; set; }

		///<summary>
		///
		///</summary>
		public string GasGuess { get; set; }

		///<summary>
		///
		///</summary>
		public string LawPerson { get; set; }

		///<summary>
		///
		///</summary>
		public string LawPersonId { get; set; }

		///<summary>
		///
		///</summary>
		public string LawJobType { get; set; }

		///<summary>
		///
		///</summary>
		public string LawJobName { get; set; }

		///<summary>
		///
		///</summary>
		public string PropertyIsType { get; set; }

		///<summary>
		///
		///</summary>
		public string PropertyIsName { get; set; }

		///<summary>
		///
		///</summary>
		public string QualificationIsType { get; set; }

		///<summary>
		///
		///</summary>
		public string QualificationIs { get; set; }

		///<summary>
		///
		///</summary>
		public string DisputesIsType { get; set; }

		///<summary>
		///
		///</summary>
		public string DisputesIsName { get; set; }

		///<summary>
		///
		///</summary>
		public string LicensesTypeType { get; set; }

		///<summary>
		///
		///</summary>
		public string LicensesTypeName { get; set; }

		///<summary>
		///
		///</summary>
		public string EngineeringPerson { get; set; }

		///<summary>
		///
		///</summary>
		public string EngineeringPersonId { get; set; }

		///<summary>
		///
		///</summary>
		public string EngineeringJobType { get; set; }

		///<summary>
		///
		///</summary>
		public string EngineeringJobName { get; set; }

		///<summary>
		///
		///</summary>
		public string ImageIsType { get; set; }

		///<summary>
		///
		///</summary>
		public string ImageIsName { get; set; }

		///<summary>
		///
		///</summary>
		public string Tent { get; set; }

		///<summary>
		///
		///</summary>
		public string OilT { get; set; }

		///<summary>
		///
		///</summary>
		public string OilQ { get; set; }

		///<summary>
		///
		///</summary>
		public string GasT { get; set; }

		///<summary>
		///
		///</summary>
		public string GasQ { get; set; }

		///<summary>
		///
		///</summary>
		public string Tank { get; set; }

		///<summary>
		///
		///</summary>
		public string Station { get; set; }

		///<summary>
		///
		///</summary>
		public string GasStorageWell { get; set; }

		///<summary>
		///
		///</summary>
		public string InforSystemType { get; set; }

		///<summary>
		///
		///</summary>
		public string InforSystemName { get; set; }

		///<summary>
		///
		///</summary>
		public string TranSType { get; set; }

		///<summary>
		///
		///</summary>
		public string TranSName { get; set; }

		///<summary>
		///
		///</summary>
		public string BusinessPerson { get; set; }

		///<summary>
		///
		///</summary>
		public string BusinessPersonId { get; set; }

		///<summary>
		///
		///</summary>
		public string BusinessJobType { get; set; }

		///<summary>
		///
		///</summary>
		public string BusinessJobName { get; set; }

		///<summary>
		///
		///</summary>
		public string SalesIsType { get; set; }

		///<summary>
		///
		///</summary>
		public string SalesIsName { get; set; }

		///<summary>
		///
		///</summary>
		public string Distance { get; set; }

		///<summary>
		///
		///</summary>
		public string Source { get; set; }

		///<summary>
		///
		///</summary>
		public string Oilsales { get; set; }

		///<summary>
		///
		///</summary>
		public string MethodsIsType { get; set; }

		///<summary>
		///
		///</summary>
		public string MethodsIsName { get; set; }

		///<summary>
		///
		///</summary>
		public string GasSales { get; set; }

		///<summary>
		///
		///</summary>
		public string SecurityPerson { get; set; }

		///<summary>
		///
		///</summary>
		public string SecurityPersonId { get; set; }

		///<summary>
		///
		///</summary>
		public string SecurityJobType { get; set; }

		///<summary>
		///
		///</summary>
		public string SecurityJobName { get; set; }

		///<summary>
		///
		///</summary>
		public string ProtectionIsType { get; set; }

		///<summary>
		///
		///</summary>
		public string ProtectionIsName { get; set; }

		///<summary>
		///
		///</summary>
		public string HiddenIsType { get; set; }

		///<summary>
		///
		///</summary>
		public string HiddenIsName { get; set; }

		///<summary>
		///
		///</summary>
		public string MeasuresIs { get; set; }

		///<summary>
		///
		///</summary>
		public string InforPerson { get; set; }

		///<summary>
		///
		///</summary>
		public string InforPersonID { get; set; }

		///<summary>
		///
		///</summary>
		public string InforJobType { get; set; }

		///<summary>
		///
		///</summary>
		public string InforJobName { get; set; }

		///<summary>
		///
		///</summary>
		public string Plans { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///
		///</summary>
		public int? State { get; set; }

        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public DateTime CreateTime { get; set; }
    }
}

