//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-09-02 11:49:58
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations;

namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Temp_TzProjectPolit:
	///</summary>
	 public  class  Temp_TzProjectPolit
	{
        [Key]
        public long Id { get; set; }
        ///<summary>
        ///
        ///</summary>
        public string ProjectId { get; set; }

		///<summary>
		///
		///</summary>
		public string CompanyId { get; set; }

		///<summary>
		///
		///</summary>
		public string CompanyName { get; set; }

		///<summary>
		///
		///</summary>
		public string StartDate { get; set; }

		///<summary>
		///
		///</summary>
		public string EndDate { get; set; }

		///<summary>
		///
		///</summary>
		public string AcceptDate { get; set; }

		///<summary>
		///
		///</summary>
		public string RectFinishDate { get; set; }

		///<summary>
		///
		///</summary>
		public string FinalDate { get; set; }

		///<summary>
		///
		///</summary>
		public string AuditDate { get; set; }

		///<summary>
		///
		///</summary>
		public string FullFiles { get; set; }

		///<summary>
		///
		///</summary>
		public string AcceptOpinion { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///
		///</summary>
		public int? State { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectName { get; set; }

        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public DateTime CreateTime { get; set; }
    }
}

