//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-09-02 11:49:57
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations;

namespace hc.epm.DataModel.Business
{ 
    ///<summary>
    ///Temp_ReformRecord:
    ///</summary>
     public  class  Temp_ReformRecord
    {
        [Key]
        public int Id { get; set; }
        ///<summary>
        ///
        ///</summary>
        public string ProjectName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectCodeInvest { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectCodeWhole { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectCodeProject { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string RemarkType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string StationName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string StationId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string StationCodeInvest { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string StationCodeWhole { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string StationCodeProject { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string CompanyName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string CompanyId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string LimitType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string SourceFund { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Investment { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ItemNumber { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ItemTime { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ItemUnit { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ItemMoney { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string InitialNumber { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string InitialMoney { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string RemarkStartTime { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string RemarkEndTime { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string RemarkMoney { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string DecisionMaker { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string LeaderPerson { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Operator { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string PipetteCoding { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string InitialSalesOfRefinedOil { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string RemarkSalesOfRefinedOil { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string InitialSalesOfGas { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string RemarkSalesOfGas { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string IRR { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectContent { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Remark { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string AnnexType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string AnnexAddress { get; set; }

        ///<summary>
        ///
        ///</summary>
        public int? State { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Approver { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ApproverId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public DateTime? ApproveTime { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ApproveResult { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ApproveRemark { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string AreaCompanyName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string AreaCompanyCode { get; set; }

        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public DateTime? CreateTime { get; set; }

    }
}

