//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-09-02 11:49:57
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations;

namespace hc.epm.DataModel.Business
{ 
    ///<summary>
    ///Temp_TzProjectProposal:
    ///</summary>
     public  class  Temp_TzProjectProposal
    {
        [Key]
        public long Id { get; set; }
        ///<summary>
        ///
        ///</summary>
        public string ProjectId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectCodeInvest { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectCodeWhole { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectCodeProject { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectNatureType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectNatureTypeName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string StationId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string StationName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string StationCodeInvest { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string StationCodeWhole { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string StationCodeProject { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ApplyTime { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string CompanyId { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string CompanyName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string CompanyCodeInvest { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string CompanyCodeWhole { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string CompanyCodeProject { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProvinceCode { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProvinceName { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProvinceCodeInvest { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProvinceCodeWhole { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProvinceCodeProject { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Recommender { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string RecommenderJob { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string RecommenderCompany { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Declarer { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Position { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string PositionType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string ProjectPosition { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string StationType { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string StationTypeCode { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string PredictMoney { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string PredictDayGas { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string PredictDayOil { get; set; }

        ///<summary>
        ///
        ///</summary>
        public string Remark { get; set; }

        ///<summary>
        ///
        ///</summary>
        public int? State { get; set; }


        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public DateTime CreateTime { get; set; }

    }
}

