//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-09-02 11:49:57
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations;

namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Temp_TzLandTalk:
	///</summary>
	 public  class  Temp_TzLandTalk
	{
        [Key]
        public long Id { get; set; }
        ///<summary>
        ///
        ///</summary>
        public string ProjectId { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectName { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectCodeInvest { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectCodeWhole { get; set; }

		///<summary>
		///
		///</summary>
		public string ProjectCodeProject { get; set; }

		///<summary>
		///
		///</summary>
		public string TalkTime { get; set; }

		///<summary>
		///
		///</summary>
		public string TalkAdress { get; set; }

		///<summary>
		///
		///</summary>
		public string FirstPay { get; set; }

		///<summary>
		///
		///</summary>
		public string FirstPayTime { get; set; }

		///<summary>
		///
		///</summary>
		public string Fees { get; set; }

		///<summary>
		///
		///</summary>
		public string FeesTime { get; set; }

		///<summary>
		///
		///</summary>
		public string TalkResultType { get; set; }

		///<summary>
		///
		///</summary>
		public string TalkResultName { get; set; }

		///<summary>
		///
		///</summary>
		public string OperationTypeType { get; set; }

		///<summary>
		///
		///</summary>
		public string OperationTypeName { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }

		///<summary>
		///
		///</summary>
		public string StateType { get; set; }

		///<summary>
		///
		///</summary>
		public string StateName { get; set; }

		///<summary>
		///
		///</summary>
		public string Operator { get; set; }

		///<summary>
		///
		///</summary>
		public string OperatorID { get; set; }

		///<summary>
		///
		///</summary>
		public string OperatorInvest { get; set; }

		///<summary>
		///
		///</summary>
		public string OperatorWhole { get; set; }

		///<summary>
		///
		///</summary>
		public string OperatorProject { get; set; }

		///<summary>
		///
		///</summary>
		public string OperatorTime { get; set; }

		///<summary>
		///
		///</summary>
		public int? State { get; set; }

		///<summary>
		///
		///</summary>
		public string OurNegotiator { get; set; }

		///<summary>
		///
		///</summary>
		public string Negotiator { get; set; }

        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public DateTime CreateTime { get; set; }
    }
}

