//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由华春网络代码生成工具生成
// version 1.0
// author hanshiwei 2017.07.24
// auto create time:2019-09-02 11:49:57
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using hc.epm.DataModel.BaseCore;
using System.ComponentModel.DataAnnotations;

namespace hc.epm.DataModel.Business
{ 
	///<summary>
	///Temp_TzAttachs:
	///</summary>
	 public  class  Temp_TzAttachs
	{
        [Key]
        public int Id { get; set; }
        ///<summary>
        ///
        ///</summary>
        public string DataId { get; set; }

		///<summary>
		///
		///</summary>
		public string TableName { get; set; }

		///<summary>
		///
		///</summary>
		public string Name { get; set; }

		///<summary>
		///
		///</summary>
		public string FilePath { get; set; }

		///<summary>
		///
		///</summary>
		public string TypeNo { get; set; }

		///<summary>
		///
		///</summary>
		public string TypeName { get; set; }

		///<summary>
		///
		///</summary>
		public string Size { get; set; }

		///<summary>
		///
		///</summary>
		public int? Sort { get; set; }

		///<summary>
		///
		///</summary>
		public int? State { get; set; }

		///<summary>
		///
		///</summary>
		public string Remark { get; set; }
        
        public DateTime? CreateTime { get; set; }
    }
}

